# More R {#more-R}


## RStudio Project setup

Here are the ready made empty folders and Project files (compressed in a zip file you need to unzip -- {{% staticref "files/Insights_projects.zip" "newtab" %}}Insights_projects.zip{{% /staticref %}}) mentioned in *Insights* (the book) section *Projects in RStudio*

## Base and tidyverse comparison

A section on translation between base and modern R (Use table 3.2 from GSwR
Add pull)

## Multiple graphs in one figure

We showed how to make multiple facets in one graph, but what about if we'd like to arrange multiple different `ggplot` graphs in one figure. There are a number of approaches to doing this 

https://patchwork.data-imaginist.com/index.html

## Simulating data

https://www.r-bloggers.com/the-birthday-paradox-puzzle-tidy-simulation-in-r/

## Avoiding "loops"

do()
Used I think in the fish diet restriction workflow demo.


## Syntax highlighting

From the book:

```{block, type="info"}
Throughout this book you will see that different parts of our R commands have different colours. We could here explain all the different parts and different colours. But then we would have to explain the grammar and syntax in more detail than we feel is currently useful for you. In case you wonder, however, please look on the Insights companion website (http://insightsfromdata.io).
```



## summarise

a bit about other summarise functions, such as summarise all. And the other option of doing a gather and group_by and summarise.