<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Are diets more diverse in more democratic countries? | Insights from Data</title>
  <meta name="description" content="To be completed" />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Are diets more diverse in more democratic countries? | Insights from Data" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="To be completed" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Are diets more diverse in more democratic countries? | Insights from Data" />
  
  <meta name="twitter:description" content="To be completed" />
  

<meta name="author" content="Owen Petchey, Andrew Beckerman, Natalie Cooper, Dylan Childs" />


<meta name="date" content="2020-01-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="additional-concepts.html">
<link rel="next" href="WFD-3.html">
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Insights from Data Website</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#introduction-1"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#workflowchecklist"><i class="fa fa-check"></i><b>1.2</b> Workflow/checklist</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#r-project-setup"><i class="fa fa-check"></i><b>1.3</b> R-project setup</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#for-instructors"><i class="fa fa-check"></i><b>1.4</b> For instructors</a><ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#live-data-demo"><i class="fa fa-check"></i><b>1.4.1</b> Live data analysis demonstration</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#datasets"><i class="fa fa-check"></i><b>1.5</b> Datasets</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#more-case-studies"><i class="fa fa-check"></i><b>1.6</b> More case studies</a><ul>
<li class="chapter" data-level="1.6.1" data-path="index.html"><a href="index.html#hungry-ladybirds"><i class="fa fa-check"></i><b>1.6.1</b> Hungry ladybirds</a></li>
<li class="chapter" data-level="1.6.2" data-path="index.html"><a href="index.html#seal-suppers"><i class="fa fa-check"></i><b>1.6.2</b> Seal suppers</a></li>
<li class="chapter" data-level="1.6.3" data-path="index.html"><a href="index.html#more-bat-poop"><i class="fa fa-check"></i><b>1.6.3</b> More bat poop</a></li>
<li class="chapter" data-level="1.6.4" data-path="index.html"><a href="index.html#marten-isotopes"><i class="fa fa-check"></i><b>1.6.4</b> Marten isotopes</a></li>
<li class="chapter" data-level="1.6.5" data-path="index.html"><a href="index.html#snake-diets"><i class="fa fa-check"></i><b>1.6.5</b> Snake diets</a></li>
<li class="chapter" data-level="1.6.6" data-path="index.html"><a href="index.html#desert-bat-diets"><i class="fa fa-check"></i><b>1.6.6</b> Desert bat diets</a></li>
<li class="chapter" data-level="1.6.7" data-path="index.html"><a href="index.html#desert-bat-diets-1"><i class="fa fa-check"></i><b>1.6.7</b> Desert bat diets</a></li>
<li class="chapter" data-level="1.6.8" data-path="index.html"><a href="index.html#birds-eating-insects"><i class="fa fa-check"></i><b>1.6.8</b> Birds eating insects</a></li>
<li class="chapter" data-level="1.6.9" data-path="index.html"><a href="index.html#diets-of-predatory-fish"><i class="fa fa-check"></i><b>1.6.9</b> Diets of predatory fish</a></li>
<li class="chapter" data-level="1.6.10" data-path="index.html"><a href="index.html#cervical-spine-compression-and-mri-not-food-related"><i class="fa fa-check"></i><b>1.6.10</b> Cervical spine compression and MRI (not food related)</a></li>
<li class="chapter" data-level="1.6.11" data-path="index.html"><a href="index.html#lots-of-other-datasets-here"><i class="fa fa-check"></i><b>1.6.11</b> Lots of other datasets here:</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#related-books"><i class="fa fa-check"></i><b>1.7</b> Related reading</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="insights-workflow.html"><a href="insights-workflow.html"><i class="fa fa-check"></i><b>2</b> Insights Workflow</a></li>
<li class="chapter" data-level="3" data-path="before-touching-rrstudio.html"><a href="before-touching-rrstudio.html"><i class="fa fa-check"></i><b>3</b> Before touching R/RStudio</a></li>
<li class="chapter" data-level="4" data-path="after-we-read-the-datafiles-into-r.html"><a href="after-we-read-the-datafiles-into-r.html"><i class="fa fa-check"></i><b>4</b> After we read the datafile(s) into R:</a></li>
<li class="chapter" data-level="5" data-path="after-data-tidying-and-cleaning.html"><a href="after-data-tidying-and-cleaning.html"><i class="fa fa-check"></i><b>5</b> After data tidying and cleaning</a></li>
<li class="chapter" data-level="6" data-path="additional-r.html"><a href="additional-r.html"><i class="fa fa-check"></i><b>6</b> Additional R</a></li>
<li class="chapter" data-level="7" data-path="additional-concepts.html"><a href="additional-concepts.html"><i class="fa fa-check"></i><b>7</b> Additional concepts</a></li>
<li class="chapter" data-level="8" data-path="WFD-2.html"><a href="WFD-2.html"><i class="fa fa-check"></i><b>8</b> Are diets more diverse in more democratic countries?</a><ul>
<li class="chapter" data-level="8.1" data-path="WFD-2.html"><a href="WFD-2.html#about-this-case-study"><i class="fa fa-check"></i><b>8.1</b> About this case study</a></li>
<li class="chapter" data-level="8.2" data-path="WFD-2.html"><a href="WFD-2.html#introduction-to-the-study-and-data"><i class="fa fa-check"></i><b>8.2</b> Introduction to the study and data</a></li>
<li class="chapter" data-level="8.3" data-path="WFD-2.html"><a href="WFD-2.html#a-little-preparation"><i class="fa fa-check"></i><b>8.3</b> A little preparation</a></li>
<li class="chapter" data-level="8.4" data-path="WFD-2.html"><a href="WFD-2.html#polity-data-origins-acquire-import-clean-tidy-nas-duplicates"><i class="fa fa-check"></i><b>8.4</b> Polity data: origins, acquire, import, clean, tidy, NAs, duplicates</a><ul>
<li class="chapter" data-level="8.4.1" data-path="WFD-2.html"><a href="WFD-2.html#data-origins-and-acquisition"><i class="fa fa-check"></i><b>8.4.1</b> Data origins and acquisition</a></li>
<li class="chapter" data-level="8.4.2" data-path="WFD-2.html"><a href="WFD-2.html#data-import"><i class="fa fa-check"></i><b>8.4.2</b> Data import</a></li>
<li class="chapter" data-level="8.4.3" data-path="WFD-2.html"><a href="WFD-2.html#tidy-and-clean"><i class="fa fa-check"></i><b>8.4.3</b> Tidy and clean</a></li>
<li class="chapter" data-level="8.4.4" data-path="WFD-2.html"><a href="WFD-2.html#deal-with-nas"><i class="fa fa-check"></i><b>8.4.4</b> Deal with NAs</a></li>
<li class="chapter" data-level="8.4.5" data-path="WFD-2.html"><a href="WFD-2.html#deal-with-innapropriate-duplicates"><i class="fa fa-check"></i><b>8.4.5</b> Deal with innapropriate duplicates</a></li>
<li class="chapter" data-level="8.4.6" data-path="WFD-2.html"><a href="WFD-2.html#check-ranges-of-numeric-variables"><i class="fa fa-check"></i><b>8.4.6</b> Check ranges of numeric variables</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="WFD-2.html"><a href="WFD-2.html#first-insights-from-the-polity-data"><i class="fa fa-check"></i><b>8.5</b> First insights from the polity data</a></li>
<li class="chapter" data-level="8.6" data-path="WFD-2.html"><a href="WFD-2.html#acquire-import-check-the-fao-food-balance-sheet-data"><i class="fa fa-check"></i><b>8.6</b> Acquire, import, check the FAO Food balance sheet data</a><ul>
<li class="chapter" data-level="8.6.1" data-path="WFD-2.html"><a href="WFD-2.html#tidying-FAO"><i class="fa fa-check"></i><b>8.6.1</b> Tidy the FAO data</a></li>
<li class="chapter" data-level="8.6.2" data-path="WFD-2.html"><a href="WFD-2.html#clean-the-fao-data"><i class="fa fa-check"></i><b>8.6.2</b> Clean the FAO data</a></li>
<li class="chapter" data-level="8.6.3" data-path="WFD-2.html"><a href="WFD-2.html#calculating-our-response-variables"><i class="fa fa-check"></i><b>8.6.3</b> Calculating our response variables</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="WFD-2.html"><a href="WFD-2.html#merge-the-two-datasets"><i class="fa fa-check"></i><b>8.7</b> Merge the two datasets</a></li>
<li class="chapter" data-level="8.8" data-path="WFD-2.html"><a href="WFD-2.html#tidying-up"><i class="fa fa-check"></i><b>8.8</b> Tidying up</a></li>
<li class="chapter" data-level="8.9" data-path="WFD-2.html"><a href="WFD-2.html#shapes"><i class="fa fa-check"></i><b>8.9</b> Shapes</a></li>
<li class="chapter" data-level="8.10" data-path="WFD-2.html"><a href="WFD-2.html#relationships"><i class="fa fa-check"></i><b>8.10</b> Relationships</a></li>
<li class="chapter" data-level="8.11" data-path="WFD-2.html"><a href="WFD-2.html#wrapping-up"><i class="fa fa-check"></i><b>8.11</b> Wrapping up</a></li>
<li class="chapter" data-level="8.12" data-path="WFD-2.html"><a href="WFD-2.html#some-questions"><i class="fa fa-check"></i><b>8.12</b> Some questions</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="WFD-3.html"><a href="WFD-3.html"><i class="fa fa-check"></i><b>9</b> Are more diverse diets better?</a><ul>
<li class="chapter" data-level="9.1" data-path="WFD-3.html"><a href="WFD-3.html#going-to-the-next-level"><i class="fa fa-check"></i><b>9.1</b> Going to the next level</a></li>
<li class="chapter" data-level="9.2" data-path="WFD-3.html"><a href="WFD-3.html#introduction-to-the-study-and-data-1"><i class="fa fa-check"></i><b>9.2</b> Introduction to the study and data</a></li>
<li class="chapter" data-level="9.3" data-path="WFD-3.html"><a href="WFD-3.html#what-type-of-response-variable"><i class="fa fa-check"></i><b>9.3</b> What type of response variable?</a></li>
<li class="chapter" data-level="9.4" data-path="WFD-3.html"><a href="WFD-3.html#a-little-preparation-1"><i class="fa fa-check"></i><b>9.4</b> A little preparation</a></li>
<li class="chapter" data-level="9.5" data-path="WFD-3.html"><a href="WFD-3.html#acquire-the-dataset"><i class="fa fa-check"></i><b>9.5</b> Acquire the dataset</a></li>
<li class="chapter" data-level="9.6" data-path="WFD-3.html"><a href="WFD-3.html#import-the-dataset"><i class="fa fa-check"></i><b>9.6</b> Import the dataset</a></li>
<li class="chapter" data-level="9.7" data-path="WFD-3.html"><a href="WFD-3.html#checking-the-import-worked-correctly"><i class="fa fa-check"></i><b>9.7</b> Checking the import worked correctly</a></li>
<li class="chapter" data-level="9.8" data-path="WFD-3.html"><a href="WFD-3.html#cleaning-and-tidying"><i class="fa fa-check"></i><b>9.8</b> Cleaning and tidying</a><ul>
<li class="chapter" data-level="9.8.1" data-path="WFD-3.html"><a href="WFD-3.html#recode-some-names"><i class="fa fa-check"></i><b>9.8.1</b> Recode some names</a></li>
<li class="chapter" data-level="9.8.2" data-path="WFD-3.html"><a href="WFD-3.html#make-the-prey_composition-variable-a-factor-with-specific-order"><i class="fa fa-check"></i><b>9.8.2</b> Make the <code>prey_composition</code> variable a factor with specific order</a></li>
<li class="chapter" data-level="9.8.3" data-path="WFD-3.html"><a href="WFD-3.html#fix-those-variable-names"><i class="fa fa-check"></i><b>9.8.3</b> Fix those variable names</a></li>
<li class="chapter" data-level="9.8.4" data-path="WFD-3.html"><a href="WFD-3.html#calculate-an-important-variable"><i class="fa fa-check"></i><b>9.8.4</b> Calculate an important variable</a></li>
<li class="chapter" data-level="9.8.5" data-path="WFD-3.html"><a href="WFD-3.html#remove-nas"><i class="fa fa-check"></i><b>9.8.5</b> Remove NAs</a></li>
<li class="chapter" data-level="9.8.6" data-path="WFD-3.html"><a href="WFD-3.html#checking-some-specifics"><i class="fa fa-check"></i><b>9.8.6</b> Checking some specifics</a></li>
<li class="chapter" data-level="9.8.7" data-path="WFD-3.html"><a href="WFD-3.html#a-closer-look-at-the-data"><i class="fa fa-check"></i><b>9.8.7</b> A closer look at the data</a></li>
<li class="chapter" data-level="9.8.8" data-path="WFD-3.html"><a href="WFD-3.html#calculate-the-three-response-variables"><i class="fa fa-check"></i><b>9.8.8</b> Calculate the three response variables</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="WFD-3.html"><a href="WFD-3.html#shapes-1"><i class="fa fa-check"></i><b>9.9</b> Shapes</a></li>
<li class="chapter" data-level="9.10" data-path="WFD-3.html"><a href="WFD-3.html#relationships-1"><i class="fa fa-check"></i><b>9.10</b> Relationships</a><ul>
<li class="chapter" data-level="9.10.1" data-path="WFD-3.html"><a href="WFD-3.html#maximum-predator-density"><i class="fa fa-check"></i><b>9.10.1</b> Maximum predator density</a></li>
<li class="chapter" data-level="9.10.2" data-path="WFD-3.html"><a href="WFD-3.html#predator-population-variability-cv"><i class="fa fa-check"></i><b>9.10.2</b> Predator population variability (CV)</a></li>
<li class="chapter" data-level="9.10.3" data-path="WFD-3.html"><a href="WFD-3.html#predator-persistence-time"><i class="fa fa-check"></i><b>9.10.3</b> Predator persistence time</a></li>
<li class="chapter" data-level="9.10.4" data-path="WFD-3.html"><a href="WFD-3.html#all-three-at-once"><i class="fa fa-check"></i><b>9.10.4</b> All three at once</a></li>
</ul></li>
<li class="chapter" data-level="9.11" data-path="WFD-3.html"><a href="WFD-3.html#wrapping-up-1"><i class="fa fa-check"></i><b>9.11</b> Wrapping up</a></li>
<li class="chapter" data-level="9.12" data-path="WFD-3.html"><a href="WFD-3.html#some-questions-1"><i class="fa fa-check"></i><b>9.12</b> Some questions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="WFD-4.html"><a href="WFD-4.html"><i class="fa fa-check"></i><b>10</b> Effects of dietary restriction</a><ul>
<li class="chapter" data-level="10.1" data-path="WFD-4.html"><a href="WFD-4.html#before-working-in-r"><i class="fa fa-check"></i><b>10.1</b> Before working in R</a></li>
<li class="chapter" data-level="10.2" data-path="WFD-4.html"><a href="WFD-4.html#after-importing-the-data-into-r"><i class="fa fa-check"></i><b>10.2</b> After importing the data into R</a><ul>
<li class="chapter" data-level="10.2.1" data-path="WFD-4.html"><a href="WFD-4.html#checking-for-duplicates"><i class="fa fa-check"></i><b>10.2.1</b> Checking for duplicates</a></li>
<li class="chapter" data-level="10.2.2" data-path="WFD-4.html"><a href="WFD-4.html#nas-variable-entries-e.g.levels-of-characters-ranges-of-numerics-numbers-of-things"><i class="fa fa-check"></i><b>10.2.2</b> NAs, variable entries, e.g. levels of characters, ranges of numerics, numbers of “things”*</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="WFD-4.html"><a href="WFD-4.html#independence"><i class="fa fa-check"></i><b>10.3</b> Independence</a></li>
<li class="chapter" data-level="10.4" data-path="WFD-4.html"><a href="WFD-4.html#balance-in-experimental-design"><i class="fa fa-check"></i><b>10.4</b> Balance in experimental design</a></li>
<li class="chapter" data-level="10.5" data-path="WFD-4.html"><a href="WFD-4.html#calculate-response-variables-if-required"><i class="fa fa-check"></i><b>10.5</b> Calculate response variable(s) (if required)</a><ul>
<li class="chapter" data-level="10.5.1" data-path="WFD-4.html"><a href="WFD-4.html#time-of-death"><i class="fa fa-check"></i><b>10.5.1</b> Time of death</a></li>
<li class="chapter" data-level="10.5.2" data-path="WFD-4.html"><a href="WFD-4.html#change-in-length"><i class="fa fa-check"></i><b>10.5.2</b> Change in length</a></li>
<li class="chapter" data-level="10.5.3" data-path="WFD-4.html"><a href="WFD-4.html#change-in-condition"><i class="fa fa-check"></i><b>10.5.3</b> Change in condition</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="WFD-4.html"><a href="WFD-4.html#merge-all-datasets-together-and-check-for-correct-number-of-rows"><i class="fa fa-check"></i><b>10.6</b> Merge all datasets together and check for correct number of rows</a></li>
<li class="chapter" data-level="10.7" data-path="WFD-4.html"><a href="WFD-4.html#super-sleuth-questions"><i class="fa fa-check"></i><b>10.7</b> Super sleuth questions</a></li>
<li class="chapter" data-level="10.8" data-path="WFD-4.html"><a href="WFD-4.html#inspect-shapes-distributions"><i class="fa fa-check"></i><b>10.8</b> Inspect shapes (distributions)</a></li>
<li class="chapter" data-level="10.9" data-path="WFD-4.html"><a href="WFD-4.html#inspect-relationships"><i class="fa fa-check"></i><b>10.9</b> Inspect relationships</a></li>
<li class="chapter" data-level="10.10" data-path="WFD-4.html"><a href="WFD-4.html#moatt-et-al-data-s1-mortality-data"><i class="fa fa-check"></i><b>10.10</b> Moatt et al Data S1 – Mortality Data</a></li>
<li class="chapter" data-level="10.11" data-path="WFD-4.html"><a href="WFD-4.html#moatt-et-al-data-s5-courtship-data"><i class="fa fa-check"></i><b>10.11</b> Moatt et al Data S5 – Courtship Data</a></li>
<li class="chapter" data-level="10.12" data-path="WFD-4.html"><a href="WFD-4.html#moatt-et-al-data-s6-eggs-data"><i class="fa fa-check"></i><b>10.12</b> Moatt et al Data S6 – Eggs Data</a></li>
<li class="chapter" data-level="10.13" data-path="WFD-4.html"><a href="WFD-4.html#moatt-et-al-data-s15-length-weight-and-condition-index-data"><i class="fa fa-check"></i><b>10.13</b> Moatt et al Data S15 – Length, Weight and Condition Index Data</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="summing-up.html"><a href="summing-up.html"><i class="fa fa-check"></i><b>11</b> Summing up</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Insights from Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="WFD-2" class="section level1">
<h1><span class="header-section-number">Chapter 8</span> Are diets more diverse in more democratic countries?</h1>
<div id="about-this-case-study" class="section level2">
<h2><span class="header-section-number">8.1</span> About this case study</h2>
<p>This case study is primarily meant to supplement the material in the book <em>Insights from Data</em> by Petchey, Beckerman, Childs, and Cooper. If you don’t understand something in the case study, have a look at that book (perhaps again), or search for help, or get in touch with us.</p>
</div>
<div id="introduction-to-the-study-and-data" class="section level2">
<h2><span class="header-section-number">8.2</span> Introduction to the study and data</h2>
<p>In this case study we will look at the diversity of food available to people living in countries around the world. And we will explore one potential influence of this diversity—the political system (e.g. democratic) of the country. Why this? Why not? There are likely lots of factors governing the diversity of food available to the population of a country, and political system is just one. We could also look at gross domestic product, location, population size, and so on. But let’s keep things relatively simple and straightforward for the moment. You can make things more complex if you choose to look further into the question, and it may be essential to do so. Just wait until after you’ve mastered the simpler though perhaps still challenging material in this case study.</p>
<p>To be clear, we are asking the question of whether the diversity of food available to the population of a country is associated with the political system of that country. We hypothesise that more freedom will result in more diversity of food availability (figure XXa – illustrate the hypothesis). We will restrict ourselves to two variables: diversity of food available and political system. Let’s use a measure diversity known as the Shannon index, which is greater if there are more food types and if the amount of each is more evenly distributed among them (figure XXb – illustrate shannon in 2x2). As far as we know, the analyses are novel. Any insights will be new! Though, since the findings are not published / peer reviewed, they should be treated as preliminary and (as usual) be critically assessed.</p>
<p>The data about what food is available to the people of a country is from the <em>FAO Food balance data</em> and that about the political system is from the <em>Polity™ IV Project dataset</em>. Hence there will be something fundamentally new in this case study: importing two different datasets and then merging them together.</p>
<p>As you work through this chapter, try following along with the <a href="http://r4all.org/posts/workflow-checklist-for-data-analysis/">workflow/checklist on this web page</a>.</p>
</div>
<div id="a-little-preparation" class="section level2">
<h2><span class="header-section-number">8.3</span> A little preparation</h2>
<p>Make a new folder for this case study, and in it a folder called in <code>data</code> (this will contain any datasets for this case study/project). In <em>RStudio</em> create an <em>RStudio</em> project and save it in the project folder (not the <code>data</code> folder). Close <em>RStudio</em> and double click on the project file to re-open <em>RStudio</em>. Create a new R script file. In this new script file make a comment about what it will contains, and then load all the libraries we so far used. Then save the file and give it a filename that is intuitive, unique, and memorable, so it is easy to search for and find.</p>
<div class="action">
<p>
Install the <code>vegan</code> and <code>ggbeeswarm</code> library if you have not already done so, otherwise <code>library(vegan)</code> and <code>library(ggbeeswarm)</code> will not work. Look at the <strong>Packages</strong> section of the Getting Acquainted chapter if you need help with installation.
</p>
</div>
</div>
<div id="polity-data-origins-acquire-import-clean-tidy-nas-duplicates" class="section level2">
<h2><span class="header-section-number">8.4</span> Polity data: origins, acquire, import, clean, tidy, NAs, duplicates</h2>
<div id="data-origins-and-acquisition" class="section level3">
<h3><span class="header-section-number">8.4.1</span> Data origins and acquisition</h3>
<p>A <em>Polity</em> is a political entity. The Polity™ IV Project aimed to code the characteristics of states in the world for the purposes of comparative quantitative analysis (i.e. what we’re about to do!). The project and resulting datasets are used for monitoring regime change and for studying effects of regime authority. Nevertheless, the data “should be treated and interpreted with due caution. Its primary utility is in investigative research which should be augmented by more detailed analysis.”; quoted from page 16 of the <a href="https://www.systemicpeace.org/inscr/p4manualv2016.pdf">Dataset User’s Manual</a> by Monty G. Marshall, Ted Robert Gurr, and Keith Jaggers. Find out more about the project at the <a href="http://www.systemicpeace.org/polityproject.html">Center for Systemic Peace</a> website.</p>
<p>You can acquire the complete dataset from <a href="http://www.systemicpeace.org/inscrdata.html">this web page of the Center for Systemic Peace</a>. Scroll down to the section <em>Polity IV: Regime Authority Characteristics and Transitions Datasets</em> and click on the <em>Excel Series</em> link to the right of the <em>Polity IV Annual Time-Series, 1800-2017</em> box. The downloaded file is an Excel spreadsheet. We recommend you open this in Excel and save it as a <code>csv</code> file, but we’ll also show below how to read the Excel file into R.</p>
<p>Looking at the dataset in Excel or something similar, you will see that the dataset has 17’061 observations and 36 variables. We will work with only three of the variables:</p>
<ul>
<li><strong>country</strong> - a character variable containing the country name.</li>
<li><strong>year</strong> - a numeric variable containing the year.</li>
<li><strong>polity2</strong> - a numeric variable giving the <em>revised combined polity score</em> from +10 (strongly democratic) to -10 (strongly autocratic).</li>
</ul>
<p>The <em>revised combined polity score</em>, according to the <em>Dataset User’s Manual</em> is a score varying from -10 for the most autocratic of polities, up to +10 for the most democratic, that “provides a convenient avenue for examining general regime effects in analyses”. (The manual also states a number of reasons for treating the variable with caution.)</p>
</div>
<div id="data-import" class="section level3">
<h3><span class="header-section-number">8.4.2</span> Data import</h3>
<p>If you did the preparation mentioned above, made a project, made a <code>csv</code> file from the Excel file, and put the data file in the data folder of that project, and you started R by double clicking on the RProject file (or switching to this project), the following code should import the data:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(<span class="dt">list =</span> <span class="kw">ls</span>())
pol &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/p4v2015.csv&quot;</span>)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   scode = col_character(),
##   country = col_character()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<p>If you want to read direct from the Excel file, use this:</p>
<pre class="sourceCode r"><code class="sourceCode r">pol &lt;-<span class="st"> </span>readxl<span class="op">::</span><span class="kw">read_excel</span>(<span class="st">&quot;data/p4v2015.xls&quot;</span>)</code></pre>
<p>Is RStudio showing the correct number of rows and columns? Is it showing the appropriate variable types for each of the three variables? The <code>Country</code> variable should be a character variable, the other two should be numeric).</p>
</div>
<div id="tidy-and-clean" class="section level3">
<h3><span class="header-section-number">8.4.3</span> Tidy and clean</h3>
<p>We only want to work with three of the 36 variables, so we use the <code>select</code> function to keep only these, and that the same time rename them to standardise the variable names by making them all begin with an upper case letter and then have lower case:</p>
<pre class="sourceCode r"><code class="sourceCode r">pol &lt;-<span class="st"> </span>pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="dt">Country =</span> country, <span class="dt">Year =</span> year, <span class="dt">Polity2 =</span> polity2)</code></pre>
<p>Because we assign the result of this operation to <code>pol</code> we are getting rid of the previous version of <code>pol</code> with this new one.</p>
<p>The data set has only one observation (of Polity) per row, so it is already tidy… we do not need to gather observations from multiple columns into one.</p>
</div>
<div id="deal-with-nas" class="section level3">
<h3><span class="header-section-number">8.4.4</span> Deal with NAs</h3>
<p>As usual, we should see if there are any NAs in the data, understand what they might result from, and decide what how to treat them. The next code makes a new dataset <code>pol_nas</code> that contains the rows that contain a missing value in any of the three variables.</p>
<pre class="sourceCode r"><code class="sourceCode r">pol_nas &lt;-<span class="st"> </span>pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter_all</span>(<span class="kw">any_vars</span>(<span class="kw">is.na</span>(.))) </code></pre>
<p>This dataset contains 235 rows, and viewing it we see that it is only the <code>polity2</code> variables that contains NAs. I.e. there are 235 missing <code>Polity2</code> values.</p>
<p>A brief perusal of the <em>Dataset User’s Manual</em> reveals a clue about why some of all of these NAs exist: “Cases of foreign “interruption” are treated as “system missing.”</p>
<p>Let us decide to treat these missing values as unimportant for further analyses, and to not include them in any further analyses, by removing them from the dataset. We know this should leave us with 17,061 - 235 = 16,826 rows of data:</p>
<pre class="sourceCode r"><code class="sourceCode r">pol &lt;-<span class="st"> </span><span class="kw">na.omit</span>(pol)</code></pre>
<p>You should see that we do, indeed, now have 16,826 rows of data.</p>
<p>We might now like to clean up a little, by removing the <code>pol_nas</code> dataset from R (you will see it dissapear from the <em>Environment</em> pane):</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(pol_nas)</code></pre>
</div>
<div id="deal-with-innapropriate-duplicates" class="section level3">
<h3><span class="header-section-number">8.4.5</span> Deal with innapropriate duplicates</h3>
<p>We expect there to not exist any more than one Polity score per country per year. We check this by first selecting only the <code>Country</code> and <code>Year</code> variables, then getting any duplicate rows with the <code>duplicated</code> function. The <code>duplicated</code> function returns a vector of TRUE and FALSE, where TRUE means a row is a duplicate. We can then get the <code>sum</code> of this vector to count the number of TRUEs (i.e. number of duplicated rows).</p>
<pre class="sourceCode r"><code class="sourceCode r">pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Country, Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">duplicated</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">sum</span>()</code></pre>
<pre><code>## [1] 2</code></pre>
<p>Interesting. There are two cases that contain duplicates. Let’s see which Country-Year combinations these are:</p>
<pre class="sourceCode r"><code class="sourceCode r">pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Country, Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="kw">duplicated</span>(.))</code></pre>
<pre><code>## # A tibble: 2 x 2
##   Country     Year
##   &lt;chr&gt;      &lt;dbl&gt;
## 1 Ethiopia    1993
## 2 Yugoslavia  1991</code></pre>
<p>And look at the duplicated cases:</p>
<pre class="sourceCode r"><code class="sourceCode r">pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(Country <span class="op">==</span><span class="st"> &quot;Yugoslavia&quot;</span>, Year <span class="op">==</span><span class="st"> </span><span class="dv">1991</span>)</code></pre>
<pre><code>## # A tibble: 2 x 3
##   Country     Year Polity2
##   &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt;
## 1 Yugoslavia  1991      -5
## 2 Yugoslavia  1991      -5</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(Country <span class="op">==</span><span class="st"> &quot;Ethiopia&quot;</span>, Year <span class="op">==</span><span class="st"> </span><span class="dv">1993</span>)</code></pre>
<pre><code>## # A tibble: 2 x 3
##   Country   Year Polity2
##   &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 Ethiopia  1993       0
## 2 Ethiopia  1993       1</code></pre>
<p>Looking through the <em>Dataset User’s Manual</em> does not readily shed light on these duplicates. Let’s remove both cases of duplication by taking the average <code>Polity2</code> score. This should result in a dataset with 16,824 rows.</p>
<pre class="sourceCode r"><code class="sourceCode r">pol &lt;-<span class="st"> </span>pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Country, Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Polity2 =</span> <span class="kw">mean</span>(Polity2)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>(pol)</code></pre>
<div class="warning">
<p>
We just made a decision about how to deal with the duplicated scores for Ethiopia in 1993. We took the mean. There are other things we could have done (e.g. use a different measure of central tendency, such as the median). So we have made an arbitrary choice in our analysis pathway. We went down one path when we could have chosen another. We need to 1) recognise and record when we make decisions like this, and 2) check to see if our conclusions are robust to variation in what we choose to do. (Here, conclusions would not be affected by using the median, as there are only two values being averaged.)
</p>
</div>
<p>Let us again check for duplicate Country-Year combinations:</p>
<pre class="sourceCode r"><code class="sourceCode r">pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Country, Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">duplicated</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">sum</span>()</code></pre>
<pre><code>## [1] 0</code></pre>
<p>Good, there are now no duplicated cases.</p>
</div>
<div id="check-ranges-of-numeric-variables" class="section level3">
<h3><span class="header-section-number">8.4.6</span> Check ranges of numeric variables</h3>
<p>Its a good idea to check if numeric variables contain any weird values. From the <em>Dataset User’s Manual</em> we expect the <code>Year</code> variable to be values including the 19th, 20th, and 21st centuries, and the <code>Polity2</code> variable to have a minimum of -10 and maximum of 10. Write code to check these are true in the imported data.</p>
<pre class="sourceCode r"><code class="sourceCode r">pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">min_year =</span> <span class="kw">min</span>(Year),
            <span class="dt">max_year =</span> <span class="kw">max</span>(Year),
            <span class="dt">min_pol =</span> <span class="kw">min</span>(Polity2),
            <span class="dt">max_pol =</span> <span class="kw">max</span>(Polity2))</code></pre>
<pre><code>## # A tibble: 1 x 4
##   min_year max_year min_pol max_pol
##      &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1     1800     2015     -10      10</code></pre>
</div>
</div>
<div id="first-insights-from-the-polity-data" class="section level2">
<h2><span class="header-section-number">8.5</span> First insights from the polity data</h2>
<p>Before we move on to the FAO dataset, lets have quick look at some features of the Polity data.</p>
<p>Let’s look at the frequency distributions of the two numeric variables. We will do this efficiently by first gathering the information in the two variables into one, then plotting. This is the method used and described in detail in the <em>Insights</em> book.</p>
<pre class="sourceCode r"><code class="sourceCode r">pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(<span class="dt">key =</span> Variable, <span class="dt">value =</span> Value, <span class="dv">2</span><span class="op">:</span><span class="dv">3</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Value)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">21</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>( <span class="op">~</span><span class="st"> </span>Variable, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="dt">nrow =</span> <span class="dv">2</span>)</code></pre>
<p><img src="insights_website_files/figure-html/unnamed-chunk-23-1.svg" width="336" style="display: block; margin: auto;" /></p>
<p>The <code>Polity2</code> variable is numeric with a minimum values of -10 and a maximum of 10 (as we already knew). The most common polity score is very democratic (+10), there are relatively few moderately democratic polity score, and there are a number of several levels of autocratic polity scores. That is, the distribution appears somewhat bimodial. We must be aware, that these are distributions of each score, with many scores for each country.</p>
<p>The <code>Year</code> variable is distributed with more values in the later years than earlier years—it makes some sense that we have more information about the recent than about the distant past. None of the three variables have any missing values, so we expect to see no warnings about excluded data points, and to not have to deal with any other issues caused by missing values. Great!</p>
<p>Try to write code to find out each of these:</p>
<ul>
<li>Number of countries in the dataset.</li>
<li>Number of years in the dataset, and first year, and last year.</li>
<li>How many records (years of data) for each country.</li>
<li>First and last year of data for each country.</li>
<li>Whether there are gaps (years without data) in each country.</li>
<li>Number of countries with gaps.</li>
<li>Number of countries with records in each year.</li>
<li>Temporal change in polity in some countries that interest you.</li>
<li>Graphs to visualise these where appropriate.</li>
</ul>
<p>Number of countries, years, first year and last year:</p>
<pre class="sourceCode r"><code class="sourceCode r">pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num_countries =</span> <span class="kw">length</span>(<span class="kw">unique</span>(Country)),
            <span class="dt">num_years =</span> <span class="kw">length</span>(<span class="kw">unique</span>(Year)),
            <span class="dt">first_year =</span> <span class="kw">min</span>(Year),
            <span class="dt">last_year =</span> <span class="kw">max</span>(Year))</code></pre>
<pre><code>## # A tibble: 1 x 4
##   num_countries num_years first_year last_year
##           &lt;int&gt;     &lt;int&gt;      &lt;dbl&gt;     &lt;dbl&gt;
## 1           193       216       1800      2015</code></pre>
<p>For each country, number of years of records, first year, last year, number of years between first and last, and if there are gaps of no data:</p>
<pre class="sourceCode r"><code class="sourceCode r">per_country_pol &lt;-<span class="st"> </span>pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Country) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num_years =</span> <span class="kw">length</span>(<span class="kw">unique</span>(Year)),
            <span class="dt">first_year =</span> <span class="kw">min</span>(Year),
            <span class="dt">last_year =</span> <span class="kw">max</span>(Year),
            <span class="dt">years_interval =</span> last_year <span class="op">-</span><span class="st"> </span>first_year <span class="op">+</span><span class="dv">1</span>,
            <span class="dt">gaps =</span> num_years <span class="op">!=</span><span class="st"> </span>years_interval)</code></pre>
<p>Number of countries with gappy information:</p>
<pre class="sourceCode r"><code class="sourceCode r">per_country_pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="kw">sum</span>(gaps))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `sum(gaps)`
##         &lt;int&gt;
## 1          46</code></pre>
<p>A graph of the number of countries with records in each year:</p>
<p>Change in polity in some countries of interest (to the authors at least):</p>
<pre class="sourceCode r"><code class="sourceCode r">countries_of_interest &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Bhutan&quot;</span>, <span class="st">&quot;Brasil&quot;</span>, <span class="st">&quot;Cuba&quot;</span>, <span class="st">&quot;Cambodia&quot;</span>,
                           <span class="st">&quot;Estonia&quot;</span>, <span class="st">&quot;Yugoslavia&quot;</span>, <span class="st">&quot;Australia&quot;</span>)
pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(Country <span class="op">%in%</span><span class="st"> </span>countries_of_interest) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Year, <span class="dt">y=</span>Polity2, <span class="dt">col=</span>Country)) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>Country) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>()</code></pre>
<p><img src="insights_website_files/figure-html/unnamed-chunk-28-1.svg" width="336" style="display: block; margin: auto;" /></p>
<p><em>Insight</em> That the polity score of a country can change so greatly has implications for our subsequent analyses. For example, calculating and using a mean polity score for each country (average across years) may be unwise as it would ignore such temporal change.</p>
</div>
<div id="acquire-import-check-the-fao-food-balance-sheet-data" class="section level2">
<h2><span class="header-section-number">8.6</span> Acquire, import, check the FAO Food balance sheet data</h2>
<p>This data shows, for various <em>Areas</em> in the world, such as countries and continents, the annual supply and use of various food <em>Items</em> such as “Wheat and products”, “Honey”, and “Crustaceans”. Supply and use includes what are called <em>Elements</em> of the food supply equation; elements such as “Production”, Import Quantity“, and”Food supply quantity (kg/capita/yr)&quot;. The words <em>Area</em>, <em>Item</em>, and <em>Element</em> are emphasised because they are variables in the dataset, as described further below. There is a lot of important information about this data available on the <a href="http://www.fao.org/faostat/en/#data/FBS/metadata">FAO Food Balance Sheet Metadata</a> web page web page. And even more in the <a href="http://www.fao.org/economic/ess/fbs/ess-fbs02/en/">Food Balance Sheet Methodology Handbook</a>.</p>
<p>The full dataset is about 210MB and can be downloaded from the FAO web page. Importing this takes about 4 seconds on a reasonably fast laptop. As you will see below, we will make a smaller dataset (about 15MB) and save it, so we don’t have to work with the full dataset.</p>
<p>The full dataset has 238,560 rows and 113 variables. The first nine variables are:</p>
<ul>
<li><strong>Area.code</strong> - A numeric variable containing number codes for the <em>Area</em> variable.</li>
<li><strong>Area</strong> - A character variable containing the geographic area that a row is about, for example, a country name or a continent name.</li>
<li><strong>Item.code</strong> - A numeric variable containing number codes for the food items in the <em>Item</em> variable.</li>
<li><strong>Item</strong> - A character variable containing the food item a row is about.</li>
<li><strong>Element.code</strong> - A numeric variable contains number codes for the <em>Element</em> variable.</li>
<li><strong>Element</strong> - A character variable showing the particular supply or utlilisation element a row is about. These are the elements of the food balance equation.</li>
<li><strong>Unit</strong> - The units of measure of the quantity in the row.</li>
<li><strong>Y1961</strong> - A numeric variable giving the quantity in year 1961</li>
<li><strong>Y1961F</strong> - A character variable giving information about the data (F is for Flag), such as “Official data”, “FAO data”, etc.</li>
</ul>
<p>The <em>Definitions and standard button</em> on this web page <a href="http://www.fao.org/faostat/en/#data/FBS/metadata" class="uri">http://www.fao.org/faostat/en/#data/FBS/metadata</a> leads to much much more information about the variables and entries.</p>
<p>You could get the FAO food balance data from the <a href="http://www.fao.org/faostat/en/#data/FBS/metadata">FAO website</a>. The datafile you would get is called <code>FoodBalanceSheets_E_All_Data.csv</code> and is 206MB, i.e. it is quite big. We need, however, only a small amount of the information in this dataset. So to make things easier for ourselves and for you, we created a smaller dataset containing only the data we need, and saved it as an <code>Rdata</code> file. This file type fits more data into a smaller space—the resulting file <code>FoodBalanceSheets_E_All_Data_reduced.Rdata</code> is 1.9MB. We put this smaller data file on the <a href="insightsfromdata.io">Insights Website</a>, so if you don’t want to make it yourself, please get it from there.</p>
<p>If you do want to go through this process, feel free to use the code immediately below, otherwise skip over this. It’s pretty straightforward, apart from two things. First, we give the <code>read_csv</code> an argument you didn’t previously see: <code>encoding</code>. This helps <code>read_csv</code> properly recognise otherwise problematic symbols. In this case, it ensure that country names such as <em>Côte d’Ivoire</em> don’t cause problems (the ô can do so). Second, the penultimate line saves the produced tibble <code>ff</code> to a <code>Rdata</code> type of data file; though even that new type of instruction should be quite transparent to you by now.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">## Get the full food balance sheet dataset *All data* from the FAO website:</span>
<span class="co">## http://www.fao.org/faostat/en/#data/FBS/metadata.</span>
<span class="co">## Reduce the size of the FAO data, so easier to deal with</span>
<span class="co">## import FAO data</span>
ff &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/FoodBalanceSheets_E_All_Data.csv&quot;</span>,
               <span class="dt">locale =</span> <span class="kw">locale</span>(<span class="dt">encoding =</span> <span class="st">&#39;ISO-8859-1&#39;</span>))
<span class="co">## First fix some variable names:</span>
<span class="kw">names</span>(ff) &lt;-<span class="st"> </span><span class="kw">str_replace_all</span>(<span class="kw">names</span>(ff), <span class="kw">c</span>(<span class="st">&quot; &quot;</span> =<span class="st"> &quot;_&quot;</span>))
<span class="co">## Remove all non-countries</span>
ff &lt;-<span class="st"> </span><span class="kw">filter</span>(ff, Country_Code <span class="op">&lt;</span><span class="st"> </span><span class="dv">5000</span>)
<span class="co">## keep only some of the elements</span>
ff &lt;-<span class="st"> </span><span class="kw">filter</span>(ff, Element <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Food supply quantity (kg/capita/yr)&quot;</span>))
<span class="co">## remove some other variables that won&#39;t be used</span>
ff &lt;-<span class="st"> </span><span class="kw">select</span>(ff, <span class="op">-</span>Country_Code, <span class="op">-</span>Item_Code,
             <span class="op">-</span>Element_Code, <span class="op">-</span>Element, <span class="op">-</span>Unit,
             <span class="op">-</span><span class="kw">ends_with</span>(<span class="st">&quot;F&quot;</span>))
<span class="co">## save the reduced file</span>
<span class="kw">saveRDS</span>(ff, <span class="st">&quot;data/FoodBalanceSheets_E_All_Data_reduced.Rdata&quot;</span>)
<span class="kw">rm</span>(ff)</code></pre>
<p>The next line reads in that smaller dataset:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#rm(list = ls())</span>
fbs &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;data/FoodBalanceSheets_E_All_Data_reduced.Rdata&quot;</span>)</code></pre>
<p>Feel free to have a look at the whole dataset with the <code>skim</code> function. We <code>select</code> a few columns first, as otherwise the output is rather long due to there being 112 variables in the dataset.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#select(fbs, Country, Item, Y1961, Y1971, Y1981, Y1991, Y2001, Y2011) %&gt;%</span>
<span class="co">#  skim()</span></code></pre>
<p>There are 17’953 observations/rows in the tibble. There are 182 countries, so 11 fewer than in the Polity data. We will later check which ones are not in the Polity data, and if any in the Polity data are not in the FAO data. There are 114 food <code>Items</code>… wow, that’s a lot of different types of food! Take a look at some of the values… it’s quite interesting to see what’s recorded. Both the <code>Country</code> variable and the <code>Item</code> variable are characters type variables as expected. If the data contained every possible combination of country and item we would expect 182 * 114 = 20’748 observations. That there are only 17’953 tells us that some combinations are missing. We will find out which these are.</p>
<p>The six year variables are, as expected numeric—they are amounts of food available (food supply quantities in kg per capita per year). We see there are quite a lot of missing values in the earlier years, and fewer in the later years. This might be expected if development of methods and adoption of them becomes more complete through time.</p>
<div id="tidying-FAO" class="section level3">
<h3><span class="header-section-number">8.6.1</span> Tidy the FAO data</h3>
<p>The FAO data is not tidy. You should be able to figure out in what respect it is “dirty”. Yes, the same information is spread across multiple columns/variables, such that there are multiple observations in each row. More specifically, the data for each year is in a separate column—data for different years are spread across columns—each row contains lots of observations each from a different year.</p>
<p>Before we make the data tidy, let’s try to figure out how many rows it should have when tidy. We will gather all the information that is currently spread across columns and put it in one column. A visualisation of a simplified version of the dataset is in Figure <a href="WFD-2.html#fig:long-wide">8.1</a>. The answer is the amount of information that’s in the columns that we want to gather into a single column. In the untidy/wide data there are 55 variables containing the data we wish to gather (because we are not gathering the information from <code>Country</code> or <code>Item</code>). Each of those variables has 17,953 rows, so we expect the long/tidy data to have 55 * 17,953 = 987,415 rows.</p>
<div class="figure" style="text-align: center"><span id="fig:long-wide"></span>
<img src="images/long_wide.jpg" alt="The same data (a) in long/tidy format and (b) in wide format, with colours and arrows linking the same data in the two different formats." width="100%" />
<p class="caption">
FIGURE 8.1: The same data (a) in long/tidy format and (b) in wide format, with colours and arrows linking the same data in the two different formats.
</p>
</div>
<p>Let’s now make the data tidy, and clean up the year variable. We first gather all the same data from columns three through 57 (<code>3:57</code>) into a new variable called <code>Food_Supply_Quantity</code> and put the information about which year each observation belongs to in a new variable called <code>Year</code>. Because the column names begin with Y (e.g. <code>Y1961</code>) we then need to keep only the 2nd through to 5th character in the <code>Year</code> variable (using the <code>substr</code> function), and convert the result to a numeric type variable (with the <code>as.numeric</code> function), doing all this within a <code>mutate</code> in order to replace the old year variable with the converted one. Let’s then take a look at the data with <code>skim</code>. Here’s the code for all that:</p>
<pre class="sourceCode r"><code class="sourceCode r">fbs_long &lt;-<span class="st"> </span>fbs <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(<span class="dt">key =</span> Year, <span class="dt">value =</span> Food_Supply_Quantity, <span class="dv">3</span><span class="op">:</span><span class="dv">57</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Year =</span> <span class="kw">as.numeric</span>(<span class="kw">substr</span>(Year, <span class="dv">2</span>, <span class="dv">5</span>)))
<span class="co">#skim(fbs_long)</span></code></pre>
<p>We see that as expected the new tibble contains 987,415. Excellent! This near-magical gather function has done a lot of very tedious work for us, very quickly. There are still the same number of countries (182) and food items (114). Now we see that the data covers from year 1961 to 2015. We also get the distribution of the food supply quantity variable… it looks to have lots of small values, and a few large. Is this what you would expect? Perhaps supply is large for a few basic foods (e.g. grains) and then there are lots of relatively rare food items. But beware that at present we are looking at the distribution including data from across years and countries. We will soon look more closely at this distribution. The <code>skim</code> also tells us that only the food supply quantity variable contains any missing values, and that there are 158,307 of them.</p>
</div>
<div id="clean-the-fao-data" class="section level3">
<h3><span class="header-section-number">8.6.2</span> Clean the FAO data</h3>
<p>Are all the years represented in the dataset? Let’s look at the unique values of the year variable:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(<span class="kw">pull</span>(fbs_long, Year))</code></pre>
<pre><code>##  [1] 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970
## [11] 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980
## [21] 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990
## [31] 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000
## [41] 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010
## [51] 2011 2012 2013 2014 2015</code></pre>
<p>Yes, every year from 1961 to 2015 is represented (by at least one observation). There are 15 years in the dataset.</p>
<p>Another good check to do on a dataset is for duplicated rows, if one can reasonably conclude that there should be none. Do we think there can be any duplicated rows in this dataset? That would be the exactly the same value of Country, Item, Year, and Food Supply Quantity.</p>
<p>Finding any duplicated rows is fairly straightforward thanks to the <code>duplicated</code> function, which returns a TRUE or FALSE for each row of a dataset, TRUE if the row is duplicated somewhere, or FALSE otherwise. Then we can <code>filter</code> the rows by these TRUE/FALSE values to give only the duplicated rows:</p>
<pre class="sourceCode r"><code class="sourceCode r">duplicated_records &lt;-<span class="st"> </span><span class="kw">filter</span>(fbs_long, <span class="kw">duplicated</span>(fbs_long))</code></pre>
<p>Note that the resulting tibble contains only one example of each duplicate (look at the data with <code>View(duplicated_rows)</code>.</p>
<p>There are, in fact, 9,287 rows that are duplicated (not unique). Let’s assume that these are mistaken duplicate entries, and so reduce to a dataset with only unique rows:</p>
<pre class="sourceCode r"><code class="sourceCode r">fbs_long &lt;-<span class="st"> </span><span class="kw">unique</span>(fbs_long)</code></pre>
<p>Now, if we’re being really paranoid, we might wonder if there were ever two different values of food supply recorded for the same country in the same year. Put another way, if we look at only the Country, Year, and Item variables, do we see duplicated rows?</p>
<pre class="sourceCode r"><code class="sourceCode r">part_duplicated_records &lt;-<span class="st"> </span>fbs_long <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Country, Item, Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">duplicated</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(fbs_long, .)</code></pre>
<p>Looking at the result we see there are 10,733 rows with duplicated Country, Year, and Item. This is weird. And that these duplicates are only for food items “Eggs” and “Milk - Excluding Butter”. We have no idea why there are multiple entries for these two items! Here’s an example of one of the duplicates:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(fbs_long,
       Country <span class="op">==</span><span class="st"> &quot;Albania&quot;</span>,
       Item <span class="op">==</span><span class="st"> &quot;Eggs&quot;</span>,
       Year <span class="op">==</span><span class="st"> </span><span class="dv">1961</span>)</code></pre>
<pre><code>## # A tibble: 2 x 4
##   Country Item   Year Food_Supply_Quantity
##   &lt;chr&gt;   &lt;chr&gt; &lt;dbl&gt;                &lt;dbl&gt;
## 1 Albania Eggs   1961                  1.5
## 2 Albania Eggs   1961                  1.8</code></pre>
<p>In the same year for the same country there are two values of Food_Supply_Quantity: 1.5 and 1.8. But it’s quite reasonable to think there can be only one. Let’s solve this problem by rather arbitrarily calculating one value, the average, of these duplicated records:</p>
<pre class="sourceCode r"><code class="sourceCode r">fbs_long &lt;-<span class="st"> </span>fbs_long <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Country, Year, Item) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Food_Supply_Quantity =</span> <span class="kw">mean</span>(Food_Supply_Quantity)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>(fbs_long)</code></pre>
<div class="info">
<p>
Time to tell the truth. It took us a long long time to realise there were duplicated records in the FAO dataset. We did not pro-actively think to check for duplicates. We only realised there must be duplicates when we tried to get the numbers to add up below. They did not before we removed the duplicates, and this led us to find the duplicates. Once we found them, we removed them above. Now it looks like we were really smart to think they might occur, check for them, find them, and remove them. In reality we were not so smart. What we were, however, was **absolutely determined* to understand why the numbers did not add up. You must also be as strict in your work. After we found the duplicates in this dataset, we also looked in the Polity data, found some, and then decided to add a check for duplicates to all case studies, and to advise you to make this a standard sanity check when you start looking at a dataset.
</p>
</div>
<p>That was a major step forward. Now we know our dataset has only unique observations.</p>
<p>Now let’s do another sanity check. Because there are 182 countries and 114 food items we know there could be 20,748 observations for each year. Let’s see how many there really are:</p>
<pre class="sourceCode r"><code class="sourceCode r">obs_per_year &lt;-<span class="st"> </span>fbs_long <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num =</span> <span class="kw">n</span>())</code></pre>
<p>There are only 17,589 observation per year. Either not all countries reported in all years, not all items were reported by each country in each year, or both!</p>
<p>First let’s see how many countries there are per year:</p>
<pre class="sourceCode r"><code class="sourceCode r">countries_per_year &lt;-<span class="st"> </span>fbs_long <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num =</span> <span class="kw">length</span>(<span class="kw">unique</span>(Country)))</code></pre>
<p>There are indeed 182 countries per year. All countries are included in all years.</p>
<p>Let’s see how many Items each country reported (across all years):</p>
<pre class="sourceCode r"><code class="sourceCode r">items_per_country &lt;-<span class="st"> </span>fbs_long <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Country) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num =</span> <span class="kw">length</span>(<span class="kw">unique</span>(Item)))</code></pre>
<p>Aha. Not all items were reported by all countries. Turkmenistan reported on the fewest (62), while China reported on the most (110). Let’s see if the sum of the number of items reported by each country is the number of observations per year.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">pull</span>(items_per_country, num))</code></pre>
<pre><code>## [1] 17589</code></pre>
<p>Yes! This is the same as the number of observations per year. All this pretty much guarantees that each country consistently (across all years) reported on a constant set of the items, or there is an observation for this set of items in each year.</p>
<div class="safety">
<p>
We didn’t just now find out anything new about the data, but we did confirm that we understand it properly. Checks and balances increase confidence.
</p>
</div>
<p>Now let’s look at the missing values:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#skim(fbs_long)</span></code></pre>
<p>We still have 155,003 missing values. Why? Where are they coming from?</p>
<p>Let’s dig a bit deeper by getting the number of observations per year, and the number and proportion of these that are missing values:</p>
<pre class="sourceCode r"><code class="sourceCode r">obs_per_year &lt;-<span class="st"> </span>fbs_long <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num =</span> <span class="kw">n</span>(),
            <span class="dt">num_na =</span> <span class="kw">sum</span>(<span class="kw">is.na</span>(Food_Supply_Quantity)),
            <span class="dt">prop_na =</span> num_na <span class="op">/</span><span class="st"> </span>num)</code></pre>
<p>And take a look at the data using <code>View(obs_per_year)</code>. We can also see quite a bit if we plot the summary data (<a href="WFD-2.html#fig:long-wide">8.1</a>) with the following code:</p>
<div class="figure" style="text-align: center"><span id="fig:fao-pol1"></span>
<img src="insights_website_files/figure-html/fao-pol1-1.svg" alt="The number of observations, the number of missing values and the proportion of missing values in each year of the data." width="100%" />
<p class="caption">
FIGURE 8.2: The number of observations, the number of missing values and the proportion of missing values in each year of the data.
</p>
</div>
<p>We see that from 1961 to 1989 there are 2,592 (14.74%) missing values per year. In 1990 and 1991 there are 2,493 (14.17%) missing values per year. From 1992 to 2011 less than 5% of the values are missing, and from 2012 to 2015 (the last year in the dataset) most or all the values are missing. Can you think of why there might be fewer missing values after 1991? Let’s look at one country (its identity might give you a clue)… Belarus. Let’s get the number of values, missing values, and proportion of missing values for Belarus in each year.</p>
<pre class="sourceCode r"><code class="sourceCode r">Belarus_obs_per_year &lt;-<span class="st"> </span>fbs_long <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(Country <span class="op">==</span><span class="st"> &quot;Belarus&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num =</span> <span class="kw">n</span>(),
            <span class="dt">num_na =</span> <span class="kw">sum</span>(<span class="kw">is.na</span>(Food_Supply_Quantity)),
            <span class="dt">prop_na =</span> num_na <span class="op">/</span><span class="st"> </span>num)</code></pre>
<p>Looking at this dataset we see that all values are missing until 1992, and then there are no missing values until 2012, when all are again missing. it’s probably clear by now that all values are missing until 1992 because Belarus only became an independent state in 1991. Likely there are lots of other countries in the dataset that have missing values for this reason.</p>
<p>There’s some other weird stuff going on here: Belgium and Luxembourg did not separately report data during the period 1992-1999, and instead reported jointly. Then from 2000 until 2011 reported separately, so there we have lots of missing values. Then we have some countries that ceased to exist in their former state, e.g. Czechoslovakia after 1993 contains only missing values due to its dissolution into the Czech Republic and Slovakia. Similarly, USSR reports only missing values after 1991 when the USSR collapsed.</p>
<p>And why more missing values from 2012 to 2015? Actually, the description of the data on the FAO web site says the data is from 1961 to only 2013, so it’s not surprising that 2014 and 2015 are empty. We will remove these years. We don’t know why there are more missing values in 2012 and 2013, so let’s also remove those:</p>
<pre class="sourceCode r"><code class="sourceCode r">fbs_long &lt;-<span class="st"> </span><span class="kw">filter</span>(fbs_long, Year <span class="op">&lt;</span><span class="st"> </span><span class="dv">2012</span>)
<span class="co">#skim(fbs_long)</span></code></pre>
<p><strong>What are we going to do???</strong> This seems very messy! Let’s aim for a dataset that contains only country/year combinations where a country actually existed (i.e. there were not all NAs reported), and also where there is an entry for all 114 food items for each country year combination (by putting zeros in for no reported item).</p>
<p>First we get a list of years in which each country does not contain all missing values. This we will use as a master list of years and countries to include in our analysis. We will not include year/country combinations where there were only missing values (the reason we need to be this specific is that we will soon turn the missing values into zeros). Let’s get that list of country/year combinations to include:</p>
<pre class="sourceCode r"><code class="sourceCode r">country_year_not_all_missing &lt;-<span class="st"> </span>fbs_long <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Country, Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">keep =</span> <span class="kw">n</span>() <span class="op">!=</span><span class="st"> </span><span class="kw">sum</span>(<span class="kw">is.na</span>(Food_Supply_Quantity))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(keep) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>keep) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>()</code></pre>
<p>Does that look rather complicated? The difficult(ish) line is the summarise, in which we create a new variable <code>keep</code> that is TRUE or FALSE depending if all values of <code>Food_Supply_Quantity</code> are NA or not. The <code>n()</code> give the number of values, the <code>sum(is.na(Food_Supply_Quantity))</code> gives the number of NAs, and the <code>!=</code> asks if the two are not the same, and returns TRUE if so. The other lines should be possible for you to work out (though not necessarily easy).</p>
<p>Note that there are 8,272 combinations of years and countries in the dataset. This is an important number. It is the number of data points we should have data for after we calculate the diversity of food available in each country in each year.</p>
<p>Now we must decide what to assume when a country did not report a value for an item. We will assume that this means there was always zero supply of that food item, so the country did not bother ever including it, i.e. it’s really a zero. Hence we’re going to pad out the data so that all countries report on all 114 items, with zero <code>Food Supply Quantity</code> for the items they did not report.</p>
<p>First we make a dataset the all combinations of <code>Country</code>, <code>Year</code>, and <code>Item</code>. It should have 182 * 51 * 182 = 1,058,148 rows. We use the quite lovely <code>expand.grid</code> function, which creates all possible combinations of the variables it’s given. We give it all the unique values of <code>Country</code>, <code>Year</code>, and <code>Item</code>, and it expands them to give all possible combinations. Each argument to <code>expand.grid</code> should be a name-value pair, and the name should be the same in the original data, to aid further operations:</p>
<pre class="sourceCode r"><code class="sourceCode r">all_cases &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(<span class="dt">Country =</span> <span class="kw">unique</span>(<span class="kw">pull</span>(fbs_long, Country)),
                         <span class="dt">Year =</span> <span class="kw">unique</span>(<span class="kw">pull</span>(fbs_long, Year)),
                         <span class="dt">Item =</span> <span class="kw">unique</span>(<span class="kw">pull</span>(fbs_long, Item))) </code></pre>
<p>Super. This has 1,058,148 rows as expected. Now we want to only keep from this the country/year combinations for which we already found there were countries that existed. There are 8,272 of these and each should have 114 items, so we should get 943,008 observations. We do this with a <code>left_join</code> to keep only the cases of the join that have values in the first (left) dataset in the join:</p>
<pre class="sourceCode r"><code class="sourceCode r">temp2 &lt;-<span class="st"> </span><span class="kw">left_join</span>(country_year_not_all_missing, all_cases)</code></pre>
<pre><code>## Joining, by = c(&quot;Country&quot;, &quot;Year&quot;)</code></pre>
<pre><code>## Warning: Column `Country` joining character vector and
## factor, coercing into character vector</code></pre>
<p>We get a warning, and know that we should never ignore warnings. The warning is <em>Column <code>Country</code> joining character vector and factor, coercing into character vector</em>. This is caused because <code>expand.grid</code> automatically converts character variables to factors. We can stop this happening (by adding the argument <code>stringsAsFactors = FALSE</code> in our call to <code>expand.grid</code> and hopefully the remove the warning:</p>
<pre class="sourceCode r"><code class="sourceCode r">all_cases &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(<span class="dt">Country =</span> <span class="kw">unique</span>(<span class="kw">pull</span>(fbs_long, Country)),
                         <span class="dt">Year =</span> <span class="kw">unique</span>(<span class="kw">pull</span>(fbs_long, Year)),
                         <span class="dt">Item =</span> <span class="kw">unique</span>(<span class="kw">pull</span>(fbs_long, Item)),
                         <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)
temp2 &lt;-<span class="st"> </span><span class="kw">left_join</span>(country_year_not_all_missing, all_cases)</code></pre>
<pre><code>## Joining, by = c(&quot;Country&quot;, &quot;Year&quot;)</code></pre>
<p>Perfect… and we have the expected number of 943,008 observations.</p>
<p>Next we do another left join to add the food supply quantity data (in <code>fbs_long</code>) to the cases/observations we want to keep (in <code>temp2</code>)</p>
<pre class="sourceCode r"><code class="sourceCode r">temp3 &lt;-<span class="st"> </span><span class="kw">left_join</span>(temp2, fbs_long)</code></pre>
<pre><code>## Joining, by = c(&quot;Country&quot;, &quot;Year&quot;, &quot;Item&quot;)</code></pre>
<p>Good, we still have 943’008 observations.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#skim(temp3)</span></code></pre>
<p>The number of missing values is now 139,252. Each of these is a case when a country reported values for some items in a year, but did not report values for others, and these others are given a value of NA. As we said above, we’re going to assume these are real zeros, and so we need to turn them all into zeros:</p>
<pre class="sourceCode r"><code class="sourceCode r">fao_final &lt;-<span class="st"> </span>temp3 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Food_Supply_Quantity =</span> <span class="kw">ifelse</span>(<span class="op">!</span><span class="kw">is.na</span>(Food_Supply_Quantity),
                                       Food_Supply_Quantity,
                                       <span class="dv">0</span>))
<span class="co">#skim(fao_final)</span></code></pre>
<p>No missing values now. And we have a dataset that we very well understand. Let’s check again though.</p>
<p>We should have 114 items reported per country per year:</p>
<pre class="sourceCode r"><code class="sourceCode r">items_per_country_per_year &lt;-<span class="st"> </span>fao_final <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Country, Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num =</span> <span class="kw">length</span>(<span class="kw">unique</span>(Item)))</code></pre>
<p>And we should have varying numbers of countries per year:</p>
<pre class="sourceCode r"><code class="sourceCode r">countries_per_year &lt;-<span class="st"> </span>fao_final <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num =</span> <span class="kw">length</span>(<span class="kw">unique</span>(Country)))</code></pre>
<p>And the sum of the number of countries per year multiplied by 114 should equal 943,008:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">pull</span>(countries_per_year, num)) <span class="op">*</span><span class="st"> </span><span class="dv">114</span></code></pre>
<pre><code>## [1] 943008</code></pre>
<p>Yes! Wow! Can you believe so much effort was needed to make a solid foundation of data! And we’re not even there yet… we still have wrangling work to do: we need to merge/join the FAO and the Polity datasets. But first…</p>
</div>
<div id="calculating-our-response-variables" class="section level3">
<h3><span class="header-section-number">8.6.3</span> Calculating our response variables</h3>
<p>The final step of preparation of the FAO data is to calculate our response variables. Our question is about food diversity so we need response variables that quantify this. We will use number of items available per year, and diversity of items available per year, where diversity accounts for the amount of each item as well as number of items using the Shannon index.</p>
<pre class="sourceCode r"><code class="sourceCode r">fao_div &lt;-<span class="st"> </span>fao_final <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Country, Year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">diversity =</span> <span class="kw">diversity</span>(Food_Supply_Quantity,
                                        <span class="dt">index =</span> <span class="st">&quot;shannon&quot;</span>),
            <span class="dt">richness =</span> <span class="kw">sum</span>(Food_Supply_Quantity<span class="op">&gt;</span><span class="dv">0</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>(fao_div)</code></pre>
<p>Excellent. We have 8,272 data points, exactly as we should. (We previously saw this was the number of combinations of country and year for which not all data was NA. I.e. the number of rows in <code>country_year_not_all_missing</code>).</p>
</div>
</div>
<div id="merge-the-two-datasets" class="section level2">
<h2><span class="header-section-number">8.7</span> Merge the two datasets</h2>
<p>The final step of data preparation is to merge the Polity and FAO data. One nasty issue we must deal with before we do the merge is to check the country names in the two datasets. It’s quite possible, even likely, there are instances of the same country having different names in the two. The following code gets the country names from each, looks for ones that appear in one and not the other, and vice versa, and writes these to csv files.</p>
<pre class="sourceCode r"><code class="sourceCode r">pol_countries &lt;-<span class="st"> </span><span class="kw">unique</span>(<span class="kw">pull</span>(pol, Country))
fao_countries &lt;-<span class="st"> </span><span class="kw">unique</span>(<span class="kw">pull</span>(fao_div, Country))
in_pol &lt;-<span class="st"> </span><span class="kw">setdiff</span>(pol_countries, fao_countries)
in_fao &lt;-<span class="st"> </span><span class="kw">setdiff</span>(fao_countries, pol_countries)
<span class="kw">write_csv</span>(<span class="kw">tibble</span>(in_pol), <span class="st">&quot;data/in_pol.csv&quot;</span>)
<span class="kw">write_csv</span>(<span class="kw">tibble</span>(in_fao), <span class="st">&quot;data/in_fao.csv&quot;</span>)</code></pre>
<p>Then it’s a matter of some manual spreadsheet work to find the matches, and to put these in a data file, and bring that matching back into R. You can get the country matching data file <code>countryname_map.csv</code> from <a href="http://insightsfromdata.io" class="uri">http://insightsfromdata.io</a>.</p>
<pre class="sourceCode r"><code class="sourceCode r">countryname_map &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/countryname_map.csv&quot;</span>,
                            <span class="dt">locale =</span> <span class="kw">locale</span>(<span class="dt">encoding =</span> <span class="st">&#39;ISO-8859-1&#39;</span>))</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   in_fao = col_character(),
##   in_pol = col_character()
## )</code></pre>
<p>Then we use a <code>left_join</code> to match the Country names in the Polity data to the those in the mapping dataset, which in effect adds a variable to the polity data that is the name of the countries in the FAO data. We then replace the Country variable with one that contains the FAO names if they exist, otherwise the Polity name:</p>
<pre class="sourceCode r"><code class="sourceCode r">pol1 &lt;-<span class="st"> </span><span class="kw">left_join</span>(pol, countryname_map, <span class="dt">by =</span><span class="kw">c</span> (<span class="st">&quot;Country&quot;</span> =<span class="st"> &quot;in_pol&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Country =</span> <span class="kw">ifelse</span>(<span class="kw">is.na</span>(in_fao),
                                Country,
                                in_fao)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>in_fao)
<span class="co">#skim(pol1)</span></code></pre>
<p>And let’s check the effect of this renaming of countries on the number of NAs. Here is the merge of the FAO and Polity data on the original Polity country names:</p>
<pre class="sourceCode r"><code class="sourceCode r">fao_pol &lt;-<span class="st"> </span><span class="kw">left_join</span>(fao_div, pol)</code></pre>
<pre><code>## Joining, by = c(&quot;Country&quot;, &quot;Year&quot;)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">is.na</span>(<span class="kw">pull</span>(fao_pol, Polity2)))</code></pre>
<pre><code>## [1] 2607</code></pre>
<p>We get 2,607 missing polity values. And here after the renaming:</p>
<pre class="sourceCode r"><code class="sourceCode r">dd1 &lt;-<span class="st"> </span><span class="kw">left_join</span>(fao_div, pol1)</code></pre>
<pre><code>## Joining, by = c(&quot;Country&quot;, &quot;Year&quot;)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">is.na</span>(<span class="kw">pull</span>(dd1, Polity2)))</code></pre>
<pre><code>## [1] 1819</code></pre>
<p>Now we have 1,819 missing polity values. Fewer, but still quite a lot. These are countries in the FAO data that we couldn’t find in the Polity data. This is a bit unsatisfactory, but we’ll go with what we have. By the way, some of these missing values are despite the country being in the Polity data, e.g. there were no Polity records for Afghanistan from 1979 to 1988, but there were for other years.</p>
<p>One last thing: let’s remove the NAs from the dataset:</p>
<pre class="sourceCode r"><code class="sourceCode r">fao_pol &lt;-<span class="st"> </span><span class="kw">na.omit</span>(fao_pol)</code></pre>
</div>
<div id="tidying-up" class="section level2">
<h2><span class="header-section-number">8.8</span> Tidying up</h2>
<p>We have a lot of objects in R’s brain. We only need one: <code>fao_pol</code>. We can remove all the other variables. We don’t need to run all the code above every time we do an analysis. In this situation we can save the <code>fao_pol</code> dataset, remove everything from R’s brain using <code>rm(list = ls())</code> or by clicking the little broom icon in RStudio, and load it again:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">saveRDS</span>(fao_pol, <span class="st">&quot;data/fao_pol.Rdata&quot;</span>)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(<span class="dt">list =</span> <span class="kw">ls</span>())
fao_pol &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;data/fao_pol.Rdata&quot;</span>)</code></pre>
</div>
<div id="shapes" class="section level2">
<h2><span class="header-section-number">8.9</span> Shapes</h2>
<p>As usual we look at the distribution of our variables. First the distribution of number of food items available in each country, across all countries and all years. The code for this you are quite familiar with by now, using <code>ggplot</code> and <code>geom_histogram</code> (Figure <a href="WFD-2.html#fig:fao-pol2">8.3</a>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(fao_pol, <span class="kw">aes</span>(<span class="dt">x =</span> richness)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:fao-pol2"></span>
<img src="insights_website_files/figure-html/fao-pol2-1.svg" alt="Frequency distribution of richness of food items across all countries and years." width="75%" />
<p class="caption">
FIGURE 8.3: Frequency distribution of richness of food items across all countries and years.
</p>
</div>
<p>Some countries in some years have only between 30 and 40 food items available, others have over 90. This is a large difference. The most common number is around 80. The distribution is somewhat left skewed, with a longer tail of smaller values. The distribution is not, however, horribly asymmetric.</p>
<p>And looking at the distribution of diversity of food item quantities with the following code (Figure <a href="WFD-2.html#fig:fao-pol3">8.4</a>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(fao_pol, <span class="kw">aes</span>(<span class="dt">x =</span> diversity)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:fao-pol3"></span>
<img src="insights_website_files/figure-html/fao-pol3-1.svg" alt="Frequency distribution of diversity of food items across all countries and years." width="75%" />
<p class="caption">
FIGURE 8.4: Frequency distribution of diversity of food items across all countries and years.
</p>
</div>
<p>The diversity distribution is quite similar to the richness distribution, with a bit of left skew, but not too much. The values of diversity are rather arbitrary—not as intuitive as richness. Higher values indicate some combination of high richness and high evenness in the quantities of the items.</p>
<p>And looking at the distribution of the Polity variable with the following code (Figure <a href="WFD-2.html#fig:fao-pol3x">8.5</a>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(fao_pol, <span class="kw">aes</span>(<span class="dt">x =</span> Polity2)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:fao-pol3x"></span>
<img src="insights_website_files/figure-html/fao-pol3x-1.svg" alt="Frequency distribution of Polity2 all countries and years." width="75%" />
<p class="caption">
FIGURE 8.5: Frequency distribution of Polity2 all countries and years.
</p>
</div>
<p>Is this what you were expecting? A rather bimodal distribution with most countries either very autocratic (low scores) or very democratic (high scores). Perhaps this in itself is an interesting pattern, though political scientists may find it obvious. Probably the creators of the Polity2 data have commented on it.</p>
</div>
<div id="relationships" class="section level2">
<h2><span class="header-section-number">8.10</span> Relationships</h2>
<p>First we’ll look at the relationship between richness and diversity. We might imagine that they’re quite closely associated since 1) diversity includes richness, and 2) their distributions look quite similar. By now the following code to make a scatter plot of richness against diversity should be familiar, though we add some transparency to the points since lots lie on top of each other (Figure <a href="WFD-2.html#fig:fao-pol4">8.6</a>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(fao_pol, <span class="kw">aes</span>(<span class="dt">x =</span> richness, <span class="dt">y =</span> diversity)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.05</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:fao-pol4"></span>
<img src="insights_website_files/figure-html/fao-pol4-1.svg" alt="Relationship between the two response variables, richness of items and diversity of items, across all countries and years." width="75%" />
<p class="caption">
FIGURE 8.6: Relationship between the two response variables, richness of items and diversity of items, across all countries and years.
</p>
</div>
<p>Not quite as close a relationship as we expected. There is certainly enough spread that we could get different insights from looking at each of the variables separately… they don’t have to tell the same story.</p>
<p>And now, drum-roll, for the answer to our question. Is there a relationship between the political system of a country and the richness of food available for human consumption. Again, by now the R-code is hopefully no challenge for you (and gives Figure <a href="WFD-2.html#fig:fao-pol5">8.7</a>):</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(fao_pol, <span class="kw">aes</span>(<span class="dt">x =</span> Polity2, <span class="dt">y =</span> richness)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.05</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:fao-pol5"></span>
<img src="insights_website_files/figure-html/fao-pol5-1.svg" alt="Richness of food items available versus Polity score, across all countries and all available years." width="75%" />
<p class="caption">
FIGURE 8.7: Richness of food items available versus Polity score, across all countries and all available years.
</p>
</div>
<p>What do you think? Is there a relationship? And how confident are you that the relationship is not just the result of chance? Before we conclude, let’s look at the relationship for diversity of food items (Figure <a href="WFD-2.html#fig:fao-pol6">8.8</a>).</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(fao_pol, <span class="kw">aes</span>(<span class="dt">x =</span> Polity2, <span class="dt">y =</span> diversity)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.05</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:fao-pol6"></span>
<img src="insights_website_files/figure-html/fao-pol6-1.svg" alt="Diversit of food items available versus Polity score, across all countries and all available years." width="75%" />
<p class="caption">
FIGURE 8.8: Diversit of food items available versus Polity score, across all countries and all available years.
</p>
</div>
<p>Well, to our eyes, it certainly looks like the countries with high Polity scores have higher richness and diversity of food available than the countries with low Polity scores. There is also <em>a lot</em> of variation, such that any country (regardless of Polity) can have nearly the highest or lowest observed diversity of richness.</p>
<p>We are being a little bit naughty, however. Each country can be contributing multiple data points to these graphs, one for each year it is present in the dataset. Countries with more years will tend to influence our conclusions more than those with fewer years. And the different years of data from one country are not independent… they are repeated measures. Let’s remove this non-independence and differential contributions of different countries in one of the crudest (though very simple and effective) ways—by getting the average value for each country. The <code>group_by</code>, <code>summarise</code> we use should be familiar:</p>
<pre class="sourceCode r"><code class="sourceCode r">dd_year &lt;-<span class="st"> </span>fao_pol <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Country) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Polity2 =</span> <span class="kw">mean</span>(Polity2),
            <span class="dt">richness =</span> <span class="kw">mean</span>(richness),
            <span class="dt">diversity =</span> <span class="kw">mean</span>(diversity))</code></pre>
<p>We have gone from a dataset with 5,665 observations to one with 133, one data point for each country in the data. Here’s the code for the graphs of Polity score and richness/diversity for this country level data:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dd_year, <span class="kw">aes</span>(<span class="dt">x =</span> Polity2, <span class="dt">y =</span> richness)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre>
<div class="figure" style="text-align: center"><span id="fig:fao-pol7"></span>
<img src="insights_website_files/figure-html/fao-pol7-1.svg" alt="Richness of food items available versus Polity score; average value for each country." width="75%" />
<p class="caption">
FIGURE 8.9: Richness of food items available versus Polity score; average value for each country.
</p>
</div>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dd_year, <span class="kw">aes</span>(<span class="dt">x =</span> Polity2, <span class="dt">y =</span> diversity)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre>
<div class="figure" style="text-align: center"><span id="fig:fao-pol8"></span>
<img src="insights_website_files/figure-html/fao-pol8-1.svg" alt="Diversity of food items available versus Polity score; average value for each country." width="75%" />
<p class="caption">
FIGURE 8.10: Diversity of food items available versus Polity score; average value for each country.
</p>
</div>
<p>The country level data (Figures <a href="WFD-2.html#fig:fao-pol7">8.9</a> and <a href="WFD-2.html#fig:fao-pol8">8.10</a>) appear to show stronger evidence of a positive relationship between polity score and richness/diversity of food available, with more democratic countries (higher polity scores) having more diversity of food available than less democratic ones.</p>
<p>Let’s look at the data another way, by categorising the Polity score. To do this we make a new variable using <code>mutate</code> and use the <code>cut</code> function to cut the Polity scores into five categories, and we name the categories:</p>
<pre class="sourceCode r"><code class="sourceCode r">dd_year &lt;-<span class="st"> </span>dd_year <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Polity2_cat =</span> <span class="kw">cut</span>(Polity2,
                           <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="op">-</span><span class="dv">11</span>, <span class="dv">11</span>, <span class="dt">length =</span> <span class="dv">6</span>),
                           <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Very autocratic&quot;</span>,
                                      <span class="st">&quot;Quite autocratic&quot;</span>,
                                      <span class="st">&quot;Neutral&quot;</span>,
                                      <span class="st">&quot;Quite democratic&quot;</span>,
                                      <span class="st">&quot;Very democratic&quot;</span>)))</code></pre>
<p>Here, we will only show the figure for the richness of food items (Figures <a href="WFD-2.html#fig:fao-pol7">8.9</a>) and not diversity (you can make that graph yourself):</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dd_year, <span class="kw">aes</span>(<span class="dt">x =</span> Polity2_cat, <span class="dt">y =</span> richness)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_beeswarm</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Dietary richness</span><span class="ch">\n</span><span class="st">[number of food items]&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Type of political system&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>()</code></pre>
<div class="figure" style="text-align: center"><span id="fig:fao-pol9"></span>
<img src="insights_website_files/figure-html/fao-pol9-1.svg" alt="Frequency distribution of diversity of food items across all countries and years." width="75%" />
<p class="caption">
FIGURE 8.11: Frequency distribution of diversity of food items across all countries and years.
</p>
</div>
<p>This tells more or less the same story, though the figure might be considered a bit nicer as it shows the meaning of the Polity score. There is an interest pattern we didn’t note before, however: that the very autocratic countries seems to have somewhat higher food diversity than we might expect—quite similar to the countries with Neutral polities. There are relatively few of these very autocratic countries, however, and one of them (China) has the highest food richness of any country!</p>
</div>
<div id="wrapping-up" class="section level2">
<h2><span class="header-section-number">8.11</span> Wrapping up</h2>
<p>Did you notice that we spent about 20 pages preparing the data, and then only ten or so (mostly graphs) looking at shapes and relationships? We spent much more time and effort making sure we knew the data inside out, that we had prepared it appropriately, and it was a solid foundation for the question we wanted to answer. And that most of the new practices and R code you experience were in that data preparation phase, and not in the analysis part.</p>
<p>That said, we were rather shallow in the analysis part. There is much much more we could have looked at. For example, we could look at relationships within countries across time, especially if there is a big shift in polity. Does the shift in polity precede a shift in diversity of food availability?</p>
<p>There are also lots of other explanatory variables we could have included in our analysis, for example national GDP, geographical location, and so on. Lots of this data is freely available on the internet. A simply fantastic place to get lost in such data and visualisation is the <a href="https://ourworldindata.org/">Our World in Data</a> website.</p>
<p>Other things you could think about analysing, for which data are available (though we couldn’t say exactly where):</p>
<ul>
<li>Biodiversity</li>
<li>Latitudinal gradient</li>
<li>Species (country) area relationship</li>
<li>GDP diversity relationship.</li>
<li>Causality by time lag relationships.</li>
<li>FAO Macroeconomic statistics (e.g. GDP by country by year) (<a href="http://www.fao.org/faostat/en/#data" class="uri">http://www.fao.org/faostat/en/#data</a>)</li>
<li>FAO Population data (e.g. population size by country by year) (<a href="http://www.fao.org/faostat/en/#data" class="uri">http://www.fao.org/faostat/en/#data</a>)</li>
<li>World Bank, e.g. country land area <a href="https://data.worldbank.org/indicator/AG.LND.TOTL.K2" class="uri">https://data.worldbank.org/indicator/AG.LND.TOTL.K2</a></li>
<li>Maybe: SDG indicators: <a href="http://data.un.org/Explorer.aspx?d=SDGs" class="uri">http://data.un.org/Explorer.aspx?d=SDGs</a></li>
</ul>
</div>
<div id="some-questions" class="section level2">
<h2><span class="header-section-number">8.12</span> Some questions</h2>
<p>Go to the Insights companion website <a href="http://insightsfromdata.io" class="uri">http://insightsfromdata.io</a> and have a go at the questions and exercises for this chapter.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="additional-concepts.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="WFD-3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown/edit/master/inst/examples/04-wfdemo-polity-fooddiv.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["insights_website.pdf", "insights_website.epub", "insights_website.mobi"],
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
