<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 What are the effects of dietary restriction? | Insights from Data with R — Online Companion</title>
  <meta name="description" content="To be completed" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 What are the effects of dietary restriction? | Insights from Data with R — Online Companion" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="To be completed" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 What are the effects of dietary restriction? | Insights from Data with R — Online Companion" />
  
  <meta name="twitter:description" content="To be completed" />
  

<meta name="author" content="Owen Petchey, Andrew Beckerman, Natalie Cooper, Dylan Childs" />


<meta name="date" content="2020-03-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="WFD-dietdiv-effect.html"/>
<link rel="next" href="modelwf-scripts.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Insights from Data Website</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#for-instructors"><i class="fa fa-check"></i><b>1.1</b> For instructors</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#workflow-demonstration"><i class="fa fa-check"></i><b>1.2</b> Workflow demonstration</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="insights-workflow.html"><a href="insights-workflow.html"><i class="fa fa-check"></i><b>2</b> Insights Workflow</a><ul>
<li class="chapter" data-level="2.1" data-path="insights-workflow.html"><a href="insights-workflow.html#preparing-the-data"><i class="fa fa-check"></i><b>2.1</b> Preparing the data</a></li>
<li class="chapter" data-level="2.2" data-path="insights-workflow.html"><a href="insights-workflow.html#prepare-computer-r-and-rstudio"><i class="fa fa-check"></i><b>2.2</b> Prepare computer, R, and RStudio</a></li>
<li class="chapter" data-level="2.3" data-path="insights-workflow.html"><a href="insights-workflow.html#read-the-data-into-r"><i class="fa fa-check"></i><b>2.3</b> Read the data into R</a></li>
<li class="chapter" data-level="2.4" data-path="insights-workflow.html"><a href="insights-workflow.html#tidy-the-data"><i class="fa fa-check"></i><b>2.4</b> Tidy the data</a></li>
<li class="chapter" data-level="2.5" data-path="insights-workflow.html"><a href="insights-workflow.html#clean-the-data."><i class="fa fa-check"></i><b>2.5</b> Clean the data.</a></li>
<li class="chapter" data-level="2.6" data-path="insights-workflow.html"><a href="insights-workflow.html#initial-insights"><i class="fa fa-check"></i><b>2.6</b> Initial insights</a></li>
<li class="chapter" data-level="2.7" data-path="insights-workflow.html"><a href="insights-workflow.html#insights-about-question-posed"><i class="fa fa-check"></i><b>2.7</b> Insights about question posed</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="more-R.html"><a href="more-R.html"><i class="fa fa-check"></i><b>3</b> More R</a><ul>
<li class="chapter" data-level="3.1" data-path="more-R.html"><a href="more-R.html#rstudio-project-setup"><i class="fa fa-check"></i><b>3.1</b> RStudio Project setup</a></li>
<li class="chapter" data-level="3.2" data-path="more-R.html"><a href="more-R.html#base-and-tidyverse-comparison"><i class="fa fa-check"></i><b>3.2</b> Base and tidyverse comparison</a></li>
<li class="chapter" data-level="3.3" data-path="more-R.html"><a href="more-R.html#multiple-graphs-in-one-figure"><i class="fa fa-check"></i><b>3.3</b> Multiple graphs in one figure</a></li>
<li class="chapter" data-level="3.4" data-path="more-R.html"><a href="more-R.html#other-pipes"><i class="fa fa-check"></i><b>3.4</b> Other pipes</a></li>
<li class="chapter" data-level="3.5" data-path="more-R.html"><a href="more-R.html#simulating-data"><i class="fa fa-check"></i><b>3.5</b> Simulating data</a></li>
<li class="chapter" data-level="3.6" data-path="more-R.html"><a href="more-R.html#avoiding-loops"><i class="fa fa-check"></i><b>3.6</b> Avoiding “loops”</a></li>
<li class="chapter" data-level="3.7" data-path="more-R.html"><a href="more-R.html#syntax-highlighting"><i class="fa fa-check"></i><b>3.7</b> Syntax highlighting</a></li>
<li class="chapter" data-level="3.8" data-path="more-R.html"><a href="more-R.html#ordination-and-clustering"><i class="fa fa-check"></i><b>3.8</b> Ordination and clustering</a></li>
<li class="chapter" data-level="3.9" data-path="more-R.html"><a href="more-R.html#summarise"><i class="fa fa-check"></i><b>3.9</b> summarise</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="additional-concepts.html"><a href="additional-concepts.html"><i class="fa fa-check"></i><b>4</b> Additional concepts</a><ul>
<li class="chapter" data-level="4.1" data-path="additional-concepts.html"><a href="additional-concepts.html#modes-of-data-analysis"><i class="fa fa-check"></i><b>4.1</b> Modes of data analysis</a></li>
<li class="chapter" data-level="4.2" data-path="additional-concepts.html"><a href="additional-concepts.html#interoperability"><i class="fa fa-check"></i><b>4.2</b> Interoperability</a><ul>
<li class="chapter" data-level="4.2.1" data-path="additional-concepts.html"><a href="additional-concepts.html#standardising-terms"><i class="fa fa-check"></i><b>4.2.1</b> Standardising terms</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="additional-concepts.html"><a href="additional-concepts.html#lurking-variables"><i class="fa fa-check"></i><b>4.3</b> Lurking variables</a></li>
<li class="chapter" data-level="4.4" data-path="additional-concepts.html"><a href="additional-concepts.html#influence-and-outliers"><i class="fa fa-check"></i><b>4.4</b> Influence and outliers</a></li>
<li class="chapter" data-level="4.5" data-path="additional-concepts.html"><a href="additional-concepts.html#transformations"><i class="fa fa-check"></i><b>4.5</b> Transformations</a></li>
<li class="chapter" data-level="4.6" data-path="additional-concepts.html"><a href="additional-concepts.html#interactions"><i class="fa fa-check"></i><b>4.6</b> Interactions</a></li>
<li class="chapter" data-level="4.7" data-path="additional-concepts.html"><a href="additional-concepts.html#distributions"><i class="fa fa-check"></i><b>4.7</b> Distributions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html"><i class="fa fa-check"></i><b>5</b> Are diets more diverse in more democratic countries?</a><ul>
<li class="chapter" data-level="5.1" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#about-this-workflow-demonstration"><i class="fa fa-check"></i><b>5.1</b> About this Workflow Demonstration</a></li>
<li class="chapter" data-level="5.2" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#introduction-to-the-study-and-data"><i class="fa fa-check"></i><b>5.2</b> Introduction to the study and data</a></li>
<li class="chapter" data-level="5.3" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#understanding-the-data"><i class="fa fa-check"></i><b>5.3</b> Understanding the data</a></li>
<li class="chapter" data-level="5.4" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#a-little-preparation"><i class="fa fa-check"></i><b>5.4</b> A little preparation</a></li>
<li class="chapter" data-level="5.5" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#polity-data-origins-acquire-import-clean-tidy-nas-duplicates"><i class="fa fa-check"></i><b>5.5</b> Polity data: origins, acquire, import, clean, tidy, NAs, duplicates</a><ul>
<li class="chapter" data-level="5.5.1" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#data-origins-and-acquisition"><i class="fa fa-check"></i><b>5.5.1</b> Data origins and acquisition</a></li>
<li class="chapter" data-level="5.5.2" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#data-import"><i class="fa fa-check"></i><b>5.5.2</b> Data import</a></li>
<li class="chapter" data-level="5.5.3" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#tidy-and-clean"><i class="fa fa-check"></i><b>5.5.3</b> Tidy and clean</a></li>
<li class="chapter" data-level="5.5.4" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#deal-with-nas"><i class="fa fa-check"></i><b>5.5.4</b> Deal with NAs</a></li>
<li class="chapter" data-level="5.5.5" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#check-for-innapropriate-duplicate-observations"><i class="fa fa-check"></i><b>5.5.5</b> Check for innapropriate duplicate observations</a></li>
<li class="chapter" data-level="5.5.6" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#check-ranges-of-numeric-variables"><i class="fa fa-check"></i><b>5.5.6</b> Check ranges of numeric variables</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#first-insights-from-the-polity-data"><i class="fa fa-check"></i><b>5.6</b> First insights from the polity data</a></li>
<li class="chapter" data-level="5.7" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#acquire-import-check-the-fao-food-balance-sheet-data"><i class="fa fa-check"></i><b>5.7</b> Acquire, import, check the FAO Food balance sheet data</a><ul>
<li class="chapter" data-level="5.7.1" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#tidying-FAO"><i class="fa fa-check"></i><b>5.7.1</b> Tidy the FAO data</a></li>
<li class="chapter" data-level="5.7.2" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#clean-the-fao-data"><i class="fa fa-check"></i><b>5.7.2</b> Clean the FAO data</a></li>
<li class="chapter" data-level="5.7.3" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#check-for-innapropriate-duplicate-observations-1"><i class="fa fa-check"></i><b>5.7.3</b> Check for innapropriate duplicate observations</a></li>
<li class="chapter" data-level="5.7.4" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#checking-something-else"><i class="fa fa-check"></i><b>5.7.4</b> Checking something else…</a></li>
<li class="chapter" data-level="5.7.5" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#missing-values"><i class="fa fa-check"></i><b>5.7.5</b> Missing values</a></li>
<li class="chapter" data-level="5.7.6" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#more-cleaning"><i class="fa fa-check"></i><b>5.7.6</b> More cleaning</a></li>
<li class="chapter" data-level="5.7.7" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#calculating-our-response-variables"><i class="fa fa-check"></i><b>5.7.7</b> Calculating our response variables</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#merge-the-two-datasets"><i class="fa fa-check"></i><b>5.8</b> Merge the two datasets</a><ul>
<li class="chapter" data-level="5.8.1" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#polity-standardisation"><i class="fa fa-check"></i><b>5.8.1</b> Polity standardisation</a></li>
<li class="chapter" data-level="5.8.2" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#the-final-merge"><i class="fa fa-check"></i><b>5.8.2</b> The final merge</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#tidying-up"><i class="fa fa-check"></i><b>5.9</b> Tidying up</a></li>
<li class="chapter" data-level="5.10" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#shapes"><i class="fa fa-check"></i><b>5.10</b> Shapes</a></li>
<li class="chapter" data-level="5.11" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#relationships"><i class="fa fa-check"></i><b>5.11</b> Relationships</a></li>
<li class="chapter" data-level="5.12" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#wrapping-up"><i class="fa fa-check"></i><b>5.12</b> Wrapping up</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html"><i class="fa fa-check"></i><b>6</b> How does dietary diversity affect populations?</a><ul>
<li class="chapter" data-level="6.1" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#going-to-the-next-level"><i class="fa fa-check"></i><b>6.1</b> Going to the next level</a></li>
<li class="chapter" data-level="6.2" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#introduction-to-the-study-and-data-1"><i class="fa fa-check"></i><b>6.2</b> Introduction to the study and data</a></li>
<li class="chapter" data-level="6.3" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#what-type-of-response-variable"><i class="fa fa-check"></i><b>6.3</b> What type of response variable?</a></li>
<li class="chapter" data-level="6.4" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#a-little-preparation-1"><i class="fa fa-check"></i><b>6.4</b> A little preparation</a></li>
<li class="chapter" data-level="6.5" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#acquire-the-dataset"><i class="fa fa-check"></i><b>6.5</b> Acquire the dataset</a></li>
<li class="chapter" data-level="6.6" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#import-the-dataset"><i class="fa fa-check"></i><b>6.6</b> Import the dataset</a></li>
<li class="chapter" data-level="6.7" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#checking-the-import-worked-correctly"><i class="fa fa-check"></i><b>6.7</b> Checking the import worked correctly</a></li>
<li class="chapter" data-level="6.8" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#cleaning-and-tidying"><i class="fa fa-check"></i><b>6.8</b> Cleaning and tidying</a><ul>
<li class="chapter" data-level="6.8.1" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#recode-some-names"><i class="fa fa-check"></i><b>6.8.1</b> Recode some names</a></li>
<li class="chapter" data-level="6.8.2" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#make-the-prey_composition-variable-a-factor-with-specific-order"><i class="fa fa-check"></i><b>6.8.2</b> Make the <code>prey_composition</code> variable a factor with specific order</a></li>
<li class="chapter" data-level="6.8.3" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#fix-those-variable-names"><i class="fa fa-check"></i><b>6.8.3</b> Fix those variable names</a></li>
<li class="chapter" data-level="6.8.4" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#calculate-an-important-variable"><i class="fa fa-check"></i><b>6.8.4</b> Calculate an important variable</a></li>
<li class="chapter" data-level="6.8.5" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#remove-nas"><i class="fa fa-check"></i><b>6.8.5</b> Remove NAs</a></li>
<li class="chapter" data-level="6.8.6" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#checking-some-specifics"><i class="fa fa-check"></i><b>6.8.6</b> Checking some specifics</a></li>
<li class="chapter" data-level="6.8.7" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#a-closer-look-at-the-data"><i class="fa fa-check"></i><b>6.8.7</b> A closer look at the data</a></li>
<li class="chapter" data-level="6.8.8" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#calculate-the-three-response-variables"><i class="fa fa-check"></i><b>6.8.8</b> Calculate the three response variables</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#shapes-1"><i class="fa fa-check"></i><b>6.9</b> Shapes</a></li>
<li class="chapter" data-level="6.10" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#relationships-1"><i class="fa fa-check"></i><b>6.10</b> Relationships</a><ul>
<li class="chapter" data-level="6.10.1" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#maximum-predator-density"><i class="fa fa-check"></i><b>6.10.1</b> Maximum predator density</a></li>
<li class="chapter" data-level="6.10.2" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#predator-population-variability-cv"><i class="fa fa-check"></i><b>6.10.2</b> Predator population variability (CV)</a></li>
<li class="chapter" data-level="6.10.3" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#predator-persistence-time"><i class="fa fa-check"></i><b>6.10.3</b> Predator persistence time</a></li>
<li class="chapter" data-level="6.10.4" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#all-three-at-once"><i class="fa fa-check"></i><b>6.10.4</b> All three at once</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#wrapping-up-1"><i class="fa fa-check"></i><b>6.11</b> Wrapping up</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html"><i class="fa fa-check"></i><b>7</b> What are the effects of dietary restriction?</a><ul>
<li class="chapter" data-level="7.1" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#before-working-in-r"><i class="fa fa-check"></i><b>7.1</b> Before working in R</a></li>
<li class="chapter" data-level="7.2" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#after-importing-the-data-into-r"><i class="fa fa-check"></i><b>7.2</b> After importing the data into R</a><ul>
<li class="chapter" data-level="7.2.1" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#checking-for-duplicates"><i class="fa fa-check"></i><b>7.2.1</b> Checking for duplicates</a></li>
<li class="chapter" data-level="7.2.2" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#nas-variable-entries-e.g.levels-of-characters-ranges-of-numerics-numbers-of-things"><i class="fa fa-check"></i><b>7.2.2</b> NAs, variable entries, e.g. levels of characters, ranges of numerics, numbers of “things”*</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#independence"><i class="fa fa-check"></i><b>7.3</b> Independence</a></li>
<li class="chapter" data-level="7.4" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#balance-in-experimental-design"><i class="fa fa-check"></i><b>7.4</b> Balance in experimental design</a></li>
<li class="chapter" data-level="7.5" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#calculate-response-variables-if-required"><i class="fa fa-check"></i><b>7.5</b> Calculate response variable(s) (if required)</a><ul>
<li class="chapter" data-level="7.5.1" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#time-of-death"><i class="fa fa-check"></i><b>7.5.1</b> Time of death</a></li>
<li class="chapter" data-level="7.5.2" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#change-in-length"><i class="fa fa-check"></i><b>7.5.2</b> Change in length</a></li>
<li class="chapter" data-level="7.5.3" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#change-in-condition"><i class="fa fa-check"></i><b>7.5.3</b> Change in condition</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#merge-all-datasets-together-and-check-for-correct-number-of-rows"><i class="fa fa-check"></i><b>7.6</b> Merge all datasets together and check for correct number of rows</a></li>
<li class="chapter" data-level="7.7" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#super-sleuth-questions"><i class="fa fa-check"></i><b>7.7</b> Super sleuth questions</a></li>
<li class="chapter" data-level="7.8" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#inspect-shapes-distributions"><i class="fa fa-check"></i><b>7.8</b> Inspect shapes (distributions)</a></li>
<li class="chapter" data-level="7.9" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#inspect-relationships"><i class="fa fa-check"></i><b>7.9</b> Inspect relationships</a></li>
<li class="chapter" data-level="7.10" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#moatt-et-al-data-s1-mortality-data"><i class="fa fa-check"></i><b>7.10</b> Moatt et al Data S1 – Mortality Data</a></li>
<li class="chapter" data-level="7.11" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#moatt-et-al-data-s5-courtship-data"><i class="fa fa-check"></i><b>7.11</b> Moatt et al Data S5 – Courtship Data</a></li>
<li class="chapter" data-level="7.12" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#moatt-et-al-data-s6-eggs-data"><i class="fa fa-check"></i><b>7.12</b> Moatt et al Data S6 – Eggs Data</a></li>
<li class="chapter" data-level="7.13" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#moatt-et-al-data-s15-length-weight-and-condition-index-data"><i class="fa fa-check"></i><b>7.13</b> Moatt et al Data S15 – Length, Weight and Condition Index Data</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modelwf-scripts.html"><a href="modelwf-scripts.html"><i class="fa fa-check"></i><b>8</b> </a></li>
<li class="chapter" data-level="9" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html"><i class="fa fa-check"></i><b>9</b> Live data analysis demonstration {#live-data-demo)}</a><ul>
<li class="chapter" data-level="9.1" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#introduction-for-intructors"><i class="fa fa-check"></i><b>9.1</b> Introduction for intructors</a></li>
<li class="chapter" data-level="" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#introduction-1"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#meta-task"><i class="fa fa-check"></i><b>9.2</b> Meta-task</a></li>
<li class="chapter" data-level="9.3" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#the-question"><i class="fa fa-check"></i><b>9.3</b> The question</a></li>
<li class="chapter" data-level="9.4" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#expectation"><i class="fa fa-check"></i><b>9.4</b> Expectation</a></li>
<li class="chapter" data-level="9.5" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#how-are-we-going-to-present-the-results"><i class="fa fa-check"></i><b>9.5</b> How are we going to present the results?</a></li>
<li class="chapter" data-level="9.6" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#what-statistical-test-will-we-use"><i class="fa fa-check"></i><b>9.6</b> What statistical test will we use?</a></li>
<li class="chapter" data-level="9.7" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#selection-of-subjects"><i class="fa fa-check"></i><b>9.7</b> Selection of subjects</a></li>
<li class="chapter" data-level="9.8" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#ethical-clearance-and-considerations"><i class="fa fa-check"></i><b>9.8</b> Ethical clearance and considerations</a></li>
<li class="chapter" data-level="9.9" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#data-collection"><i class="fa fa-check"></i><b>9.9</b> Data collection</a></li>
<li class="chapter" data-level="9.10" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#look-at-the-data"><i class="fa fa-check"></i><b>9.10</b> Look at the data!</a></li>
<li class="chapter" data-level="9.11" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#lets-get-the-data-into-our-data-analysis-software-of-choice-r-via-rstudio"><i class="fa fa-check"></i><b>9.11</b> Lets get the data into our data analysis software of choice (R, via RStudio)</a></li>
<li class="chapter" data-level="9.12" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#now-we-need-to-do-some-data-wrangling-cleaning-and-tidying"><i class="fa fa-check"></i><b>9.12</b> Now we need to do some data wrangling (cleaning and tidying)</a><ul>
<li class="chapter" data-level="9.12.1" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#clean-up-the-column-variable-names"><i class="fa fa-check"></i><b>9.12.1</b> Clean up the column / variable names:</a></li>
<li class="chapter" data-level="9.12.2" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#check-the-variable-types-are-correct."><i class="fa fa-check"></i><b>9.12.2</b> Check the variable types are correct.</a></li>
<li class="chapter" data-level="9.12.3" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#correct-or-exclude-problematic-data"><i class="fa fa-check"></i><b>9.12.3</b> Correct or exclude problematic data</a></li>
<li class="chapter" data-level="9.12.4" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#check-numbers-of-data-points-in-each-gender"><i class="fa fa-check"></i><b>9.12.4</b> Check numbers of data points in each gender</a></li>
<li class="chapter" data-level="9.12.5" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#check-the-number-of-observations"><i class="fa fa-check"></i><b>9.12.5</b> Check the number of observations</a></li>
</ul></li>
<li class="chapter" data-level="9.13" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#visualise-the-data"><i class="fa fa-check"></i><b>9.13</b> Visualise the data</a></li>
<li class="chapter" data-level="9.14" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#get-the-means"><i class="fa fa-check"></i><b>9.14</b> Get the means</a></li>
<li class="chapter" data-level="9.15" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#effect-size-and-practical-importance"><i class="fa fa-check"></i><b>9.15</b> Effect size and practical importance?</a></li>
<li class="chapter" data-level="9.16" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#assess-assumptions"><i class="fa fa-check"></i><b>9.16</b> Assess assumptions</a><ul>
<li class="chapter" data-level="9.16.1" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#independence-1"><i class="fa fa-check"></i><b>9.16.1</b> Independence</a></li>
<li class="chapter" data-level="9.16.2" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#normally-distributed-residuals"><i class="fa fa-check"></i><b>9.16.2</b> Normally distributed residuals</a></li>
<li class="chapter" data-level="9.16.3" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#equal-variance"><i class="fa fa-check"></i><b>9.16.3</b> Equal variance</a></li>
</ul></li>
<li class="chapter" data-level="9.17" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#do-the-statistical-test"><i class="fa fa-check"></i><b>9.17</b> Do the statistical test</a></li>
<li class="chapter" data-level="9.18" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#critical-thinking"><i class="fa fa-check"></i><b>9.18</b> Critical thinking</a></li>
<li class="chapter" data-level="9.19" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#report-and-communicate-the-results"><i class="fa fa-check"></i><b>9.19</b> Report and communicate the results</a><ul>
<li class="chapter" data-level="9.19.1" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#the-results-as-a-sentence"><i class="fa fa-check"></i><b>9.19.1</b> The results as a sentence</a></li>
<li class="chapter" data-level="9.19.2" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#the-results-graphically"><i class="fa fa-check"></i><b>9.19.2</b> The results graphically</a></li>
<li class="chapter" data-level="9.19.3" data-path="live-data-analysis-demonstration-live-data-demo.html"><a href="live-data-analysis-demonstration-live-data-demo.html#do-not-use-a-table"><i class="fa fa-check"></i><b>9.19.3</b> Do not use a table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="more-questions-data.html"><a href="more-questions-data.html"><i class="fa fa-check"></i><b>10</b> More questions and datasets</a><ul>
<li class="chapter" data-level="10.1" data-path="more-questions-data.html"><a href="more-questions-data.html#hungry-ladybirds"><i class="fa fa-check"></i><b>10.1</b> Hungry ladybirds</a></li>
<li class="chapter" data-level="10.2" data-path="more-questions-data.html"><a href="more-questions-data.html#seal-suppers"><i class="fa fa-check"></i><b>10.2</b> Seal suppers</a></li>
<li class="chapter" data-level="10.3" data-path="more-questions-data.html"><a href="more-questions-data.html#more-bat-poop"><i class="fa fa-check"></i><b>10.3</b> More bat poop</a></li>
<li class="chapter" data-level="10.4" data-path="more-questions-data.html"><a href="more-questions-data.html#marten-isotopes"><i class="fa fa-check"></i><b>10.4</b> Marten isotopes</a></li>
<li class="chapter" data-level="10.5" data-path="more-questions-data.html"><a href="more-questions-data.html#snake-diets"><i class="fa fa-check"></i><b>10.5</b> Snake diets</a></li>
<li class="chapter" data-level="10.6" data-path="more-questions-data.html"><a href="more-questions-data.html#desert-bat-diets"><i class="fa fa-check"></i><b>10.6</b> Desert bat diets</a></li>
<li class="chapter" data-level="10.7" data-path="more-questions-data.html"><a href="more-questions-data.html#birds-eating-insects"><i class="fa fa-check"></i><b>10.7</b> Birds eating insects</a></li>
<li class="chapter" data-level="10.8" data-path="more-questions-data.html"><a href="more-questions-data.html#diets-of-predatory-fish"><i class="fa fa-check"></i><b>10.8</b> Diets of predatory fish</a></li>
<li class="chapter" data-level="10.9" data-path="more-questions-data.html"><a href="more-questions-data.html#cervical-spine-compression-and-mri-not-food-related"><i class="fa fa-check"></i><b>10.9</b> Cervical spine compression and MRI (not food related)</a></li>
<li class="chapter" data-level="10.10" data-path="more-questions-data.html"><a href="more-questions-data.html#lots-of-other-datasets-here"><i class="fa fa-check"></i><b>10.10</b> Lots of other datasets here:</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="related-reading.html"><a href="related-reading.html"><i class="fa fa-check"></i><b>11</b> Related reading</a><ul>
<li class="chapter" data-level="11.1" data-path="related-reading.html"><a href="related-reading.html#data-science-related-reading"><i class="fa fa-check"></i><b>11.1</b> Data science related reading</a></li>
<li class="chapter" data-level="11.2" data-path="related-reading.html"><a href="related-reading.html#study-design-related-reading"><i class="fa fa-check"></i><b>11.2</b> Study design related reading</a></li>
<li class="chapter" data-level="11.3" data-path="related-reading.html"><a href="related-reading.html#beautifying-graphs-ggplot2"><i class="fa fa-check"></i><b>11.3</b> Beautifying graphs (ggplot2)</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Insights from Data with R — Online Companion</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="WFD-diet-restrict" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> What are the effects of dietary restriction?</h1>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" data-line-number="1"><span class="co">## Load the libraries we use</span></a>
<a class="sourceLine" id="cb189-2" data-line-number="2"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb189-3" data-line-number="3"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb189-4" data-line-number="4"><span class="kw">library</span>(readr)</a>
<a class="sourceLine" id="cb189-5" data-line-number="5"><span class="kw">library</span>(stringr)</a>
<a class="sourceLine" id="cb189-6" data-line-number="6"><span class="kw">library</span>(lubridate)</a>
<a class="sourceLine" id="cb189-7" data-line-number="7"><span class="kw">library</span>(skimr)</a>
<a class="sourceLine" id="cb189-8" data-line-number="8"><span class="kw">library</span>(tidyr)</a>
<a class="sourceLine" id="cb189-9" data-line-number="9"><span class="kw">library</span>(ggbeeswarm)</a>
<a class="sourceLine" id="cb189-10" data-line-number="10"><span class="kw">library</span>(taxize)</a>
<a class="sourceLine" id="cb189-11" data-line-number="11"><span class="kw">library</span>(broom)</a>
<a class="sourceLine" id="cb189-12" data-line-number="12"><span class="kw">library</span>(forcats)</a></code></pre></div>
<p><img src="images/WF4_icon.jpg" width="60"/></p>
<p>A general article about dietary restriction (DR): <a href="https://www.nia.nih.gov/health/calorie-restriction-and-fasting-diets-what-do-we-know" class="uri">https://www.nia.nih.gov/health/calorie-restriction-and-fasting-diets-what-do-we-know</a></p>
<p>The case study article: <em>Reconciling nutritional geometry with classical dietary restriction: effects of nutrient intake, not calories, on survival and reproduction.</em> Moatt JP, Fyfe MA, Heap E, Mitchell LJM, Moon F, Walling CA (2018) Aging Cell, Volume 18, e12868.</p>
<p>Article: <a href="https://doi.org/10.1111/acel.12868" class="uri">https://doi.org/10.1111/acel.12868</a></p>
<p>Data: <a href="https://doi.org/10.5061/dryad.g12p0j2" class="uri">https://doi.org/10.5061/dryad.g12p0j2</a></p>
<p>Abstract: “Here, using a novel nonmodel vertebrate system (the stickleback fish, <em>Gasterosteus aculeatus</em>), we test the effect of macronutrient versus calorie intake on key fitness‐related traits, both using the GF and avoiding dietary dilution. We find that the intake of macronutrients rather than calories determines both mortality risk and reproduction. Male mortality risk was lowest on intermediate lipid intakes, and female risk was generally reduced by low protein intakes. The effect of macronutrient intake on reproduction was similar between the sexes, with high protein intakes maximizing reproduction.”</p>
<p>A discussion of these features of the case study data (put info in a box? A new type of box?):</p>
<p>The number of variables (columns) they contain.
The number of observations (rows).
If and how many of the variables describe experimental manipulations.
The amount of correlation among the variables.
How independent are the observations.</p>
<div id="before-working-in-r" class="section level2">
<h2><span class="header-section-number">7.1</span> Before working in R</h2>
<p><strong>Question</strong>: How does diet composition and amount of food individually and in combination affect individual characteristics related to health and fitness?</p>
<p><strong>Hypotheses/predictions</strong>:</p>
<ul>
<li>Fitness: “mortality”</li>
<li>Fitness: “reproductive behaviour (time spent courting)”</li>
<li>Fitness: “Female reproduction (total egg production)”</li>
<li>Health: “We use change in fish length as our measure of growth.”</li>
<li>Health: “As a proxy for overall health, we use body condition index, which is a measure of the weight of an individual relative to its length”</li>
</ul>
<p><strong>Study methods and design</strong> (<strong>numbers of “things”</strong>) “We fed 300 male and 300 female individually housed three‐spine sticklebacks one of five diets varying in protein and lipid content (Table 2) at one of three provisioning levels (100%, 75% or 50% of ad lib), therefore using a restriction of food availability rather than a dilution of the diets to achieve calorie restriction. This gave a total of 15 dietary treatments (see methods and supplementary materials for full details). Fish were maintained on diets for life and measured for numerous traits including survival, reproductive investment, growth and body condition. Given the broad range of traits examined, we present data for each trait separately, with an accompanying short interpretation section.”</p>
<p>“Mortality was checked twice daily and date of death was recorded. We quantified male lifetime reproductive investment as the total time spent courting (in seconds) across all courtship attempts. Males were also assayed for other common reproductive behaviours (e.g., territory defence, nesting and nuptial coloration—see supplementary methods and analysis). Female lifetime reproductive investment was taken as the total number of eggs produced). Fish were monitored for growth (length (mm) and weight (g)) approximately every 1–2 months (Supporting Information Table S26). From these measures, body condition (overall health) was also quantified (Moatt et al., 2017 and supplementary methods).”</p>
<p>Q: How many fish per treatment combination? A. 20</p>
<p><strong>Type of response variable:</strong></p>
<ul>
<li>Mortality—binary, dead or alive.</li>
<li>Time spent courting—cannot be negative, will likely be numeric, may be distrete (e.g. 10 mins or 20 minutes) or continuous, ratio type.</li>
<li>Female reproduction egg production—count type data, not negative, discrete (integers), ratio type.</li>
<li>Change in fish length—could be negative or positive, ratio type.</li>
<li>Body condition index (a measure of the weight of an individual relative to its length)-only positive, likely continuous, ratio type.</li>
</ul>
<p><strong>Explanatory variables:</strong></p>
<ul>
<li>A variable about the diet composition treatment.</li>
<li>A variable about the provisioning level treatment.</li>
<li>Perhaps some others.</li>
</ul>
<p><strong>Predictions</strong>:
What were the predictions?</p>
<p><strong>Data birth</strong>:</p>
<ul>
<li><strong>Number of variables</strong>: not too many as a designed experiment with clear question.</li>
<li><strong>Number of observations</strong>: number of fish (they were “individually housed”, and assigned treatment on an individual level).</li>
<li><strong>Variables describing manipulations</strong>: yes, two.</li>
<li><strong>Correlation among variables</strong>: low (factorial experiment, though some imbalance likely)</li>
<li><strong>Independence of observations</strong>: there may be multiple observations per fish (repeated measures). Fish may share mothers, fathers, and other pre-experiment conditions.</li>
</ul>
<p><strong>Secure resources and perform study</strong></p>
<p><strong>Which datafiles:</strong> Have a look at the data files on the dryad repository. Which data files are required for which response variable?</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" data-line-number="1">mortality &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/Moatt_et_al_Data_S1.csv&quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   FID = col_character(),
##   Sex = col_character(),
##   Size = col_character()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" data-line-number="1">courtship &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/Moatt_et_al_Data_S5.csv&quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   FID = col_character(),
##   Family = col_character(),
##   Shelf_stack = col_character(),
##   Diet = col_double(),
##   Level = col_double(),
##   Size = col_character(),
##   Trial = col_double(),
##   Days_breeding = col_double(),
##   P_day = col_double(),
##   P2_day = col_double(),
##   L_day = col_double(),
##   L2_day = col_double(),
##   Mean_react = col_double(),
##   Total_ZZ = col_double(),
##   Total_lead = col_double(),
##   Total_court = col_double()
## )</code></pre>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb195-1" data-line-number="1">eggs &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/Moatt_et_al_Data_S6.csv&quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   FID = col_character(),
##   Family = col_character(),
##   Stack_shelf = col_character(),
##   Diet = col_double(),
##   Level = col_double(),
##   Size = col_character(),
##   P_day = col_double(),
##   P2_day = col_double(),
##   L_day = col_double(),
##   L2_day = col_double(),
##   Days_breeding = col_double(),
##   Number_clutches = col_double(),
##   mean_number = col_double(),
##   Total_egg = col_double()
## )</code></pre>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb197-1" data-line-number="1">length_weight_condition &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/Moatt_et_al_Data_S15.csv&quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   FID = col_character(),
##   Shelf_stack = col_character(),
##   Sex = col_character(),
##   Diet = col_double(),
##   Level = col_double(),
##   Size = col_character(),
##   Batch = col_double(),
##   P_day = col_double(),
##   P2_day = col_double(),
##   L_day = col_double(),
##   L2_day = col_double(),
##   ZP = col_double(),
##   ZP2 = col_double(),
##   ZL = col_double(),
##   ZL2 = col_double(),
##   Ln = col_double(),
##   Wt = col_double(),
##   CI = col_double()
## )</code></pre>
<p><strong>Variables in the datafiles</strong>: Look at the <code>data file key</code> word document in the dryad repository.</p>
<p>Which variables tell us about the experimental design (including the explantory variables) and when observations were made?</p>
<ul>
<li><strong>FID</strong> – Unique ID for each individual.</li>
<li><strong>Diet</strong> – Diet Treatment (Diet P:L: 1 = 10.2:1, 2 = 4.6:1, 3 = 2.5:1, 4 = 8.5:1, 5 = 1.6:1).</li>
<li><strong>Sex</strong> – Sex of individual (M = male, F = female).</li>
<li><strong>Size</strong> – Size classification of individual (L = large, S = Small).</li>
<li><strong>Level</strong> – Provisioning level, values represent percentages of monthly ad libitum monitoring.</li>
<li><strong>Week_F</strong> – Experimental week.</li>
<li><strong>Batch</strong> – Weighing batch.</li>
</ul>
<p>There are numerous other variables in the datasets. We will look at them if and when we need to.</p>
<p>Which variables in which dataset can be used to calculate each of the five response variables?</p>
<ul>
<li>Mortality: <code>status</code>, 0 = alive, 1 = Dead, in <code>Moatt_et_al_Data_S1.csv</code></li>
<li>Time spent courting: <code>Total_court</code> – Total time courting across all trials, in <code>Moatt_et_al_Data_S5.csv</code>.</li>
<li>Female reproduction egg production: <code>Total_egg</code> – Total number of eggs produced, in <code>Moatt_et_al_Data_S6.csv</code>.</li>
<li>Change in fish length: Ln – Length of individual in mm, in <code>Moatt_et_al_Data_S15.csv</code>.</li>
<li>Body condition index: CI – Condition Index for each individual, <code>Moatt_et_al_Data_S15.csv</code>.</li>
</ul>
<p><strong>Number of rows and columns in the dataset</strong>:
(By looking at the datasets in a spreadsheet programme)</p>
<ul>
<li><code>Moatt_et_al_Data_S1.csv</code>: 33’049 rows, 24 variables</li>
<li><code>Moatt_et_al_Data_S5.csv</code>: 228, 16</li>
<li><code>Moatt_et_al_Data_S6.csv</code>: 269, 14</li>
<li><code>Moatt_et_al_Data_S15.csv</code>:6000, 18</li>
</ul>
</div>
<div id="after-importing-the-data-into-r" class="section level2">
<h2><span class="header-section-number">7.2</span> After importing the data into R</h2>
<ul>
<li>number of rows and columns: as expected</li>
<li>tidy: all four datasets appear tidy, at the moment.</li>
<li>variable types: all as expected</li>
<li>fix dates: none present</li>
</ul>
<p><strong>Make more informative variable names (and discard variables not obviously of use)</strong>:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" data-line-number="1">courtship &lt;-<span class="st"> </span>courtship <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb199-2" data-line-number="2"><span class="st">  </span><span class="kw">select</span>(<span class="dt">Fish_ID=</span>FID, Family, Shelf_stack, <span class="dt">Diet_comp=</span>Diet,</a>
<a class="sourceLine" id="cb199-3" data-line-number="3">         <span class="dt">Prov_level=</span>Level, <span class="dt">Fish_size=</span>Size, Trial, Total_court)</a>
<a class="sourceLine" id="cb199-4" data-line-number="4">eggs &lt;-<span class="st"> </span>eggs <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb199-5" data-line-number="5"><span class="st">  </span><span class="kw">select</span>(<span class="dt">Fish_ID=</span>FID, Family, <span class="dt">Shelf_stack=</span>Stack_shelf, <span class="dt">Diet_comp=</span>Diet,</a>
<a class="sourceLine" id="cb199-6" data-line-number="6">         <span class="dt">Prov_level=</span>Level, <span class="dt">Fish_size=</span>Size, Total_egg)</a>
<a class="sourceLine" id="cb199-7" data-line-number="7">length_weight_condition &lt;-<span class="st"> </span>length_weight_condition <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb199-8" data-line-number="8"><span class="st">  </span><span class="kw">select</span>(<span class="dt">Fish_ID=</span>FID, Shelf_stack, <span class="dt">Diet_comp=</span>Diet, <span class="dt">Sex=</span>Sex,</a>
<a class="sourceLine" id="cb199-9" data-line-number="9">         Batch,</a>
<a class="sourceLine" id="cb199-10" data-line-number="10">         <span class="dt">Prov_level=</span>Level, <span class="dt">Fish_size=</span>Size, <span class="dt">Length=</span>Ln, <span class="dt">Weigth=</span>Wt, <span class="dt">Cond_index=</span>CI)</a>
<a class="sourceLine" id="cb199-11" data-line-number="11">mortality &lt;-<span class="st"> </span>mortality <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb199-12" data-line-number="12"><span class="st">  </span><span class="kw">select</span>(<span class="dt">Fish_ID=</span>FID, <span class="dt">Diet_comp=</span>Diet, Sex,</a>
<a class="sourceLine" id="cb199-13" data-line-number="13">         <span class="dt">Prov_level=</span>Level, <span class="dt">Fish_size=</span>Size, <span class="dt">Week=</span>Week_F, Status)</a></code></pre></div>
<p><strong>Replace codes with informative words</strong>:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb200-1" data-line-number="1">courtship &lt;-<span class="st"> </span>courtship <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb200-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Diet_comp =</span> <span class="kw">case_when</span>(Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">~</span><span class="st"> &quot;10.2:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-3" data-line-number="3">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">2</span> <span class="op">~</span><span class="st"> &quot;4.6:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-4" data-line-number="4">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">3</span> <span class="op">~</span><span class="st"> &quot;2.5:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-5" data-line-number="5">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">4</span> <span class="op">~</span><span class="st"> &quot;8.5:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-6" data-line-number="6">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">5</span> <span class="op">~</span><span class="st"> &quot;1.6:1&quot;</span>),</a>
<a class="sourceLine" id="cb200-7" data-line-number="7">         <span class="dt">Fish_size =</span> <span class="kw">case_when</span>(Fish_size <span class="op">==</span><span class="st"> &quot;S&quot;</span> <span class="op">~</span><span class="st"> &quot;Small&quot;</span>,</a>
<a class="sourceLine" id="cb200-8" data-line-number="8">                               Fish_size <span class="op">==</span><span class="st"> &quot;L&quot;</span> <span class="op">~</span><span class="st"> &quot;Large&quot;</span>))</a>
<a class="sourceLine" id="cb200-9" data-line-number="9"></a>
<a class="sourceLine" id="cb200-10" data-line-number="10">eggs &lt;-<span class="st"> </span>eggs <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb200-11" data-line-number="11"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Diet_comp =</span> <span class="kw">case_when</span>(Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">~</span><span class="st"> &quot;10.2:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-12" data-line-number="12">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">2</span> <span class="op">~</span><span class="st"> &quot;4.6:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-13" data-line-number="13">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">3</span> <span class="op">~</span><span class="st"> &quot;2.5:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-14" data-line-number="14">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">4</span> <span class="op">~</span><span class="st"> &quot;8.5:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-15" data-line-number="15">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">5</span> <span class="op">~</span><span class="st"> &quot;1.6:1&quot;</span>),</a>
<a class="sourceLine" id="cb200-16" data-line-number="16">         <span class="dt">Fish_size =</span> <span class="kw">case_when</span>(Fish_size <span class="op">==</span><span class="st"> &quot;S&quot;</span> <span class="op">~</span><span class="st"> &quot;Small&quot;</span>,</a>
<a class="sourceLine" id="cb200-17" data-line-number="17">                               Fish_size <span class="op">==</span><span class="st"> &quot;L&quot;</span> <span class="op">~</span><span class="st"> &quot;Large&quot;</span>))</a>
<a class="sourceLine" id="cb200-18" data-line-number="18"></a>
<a class="sourceLine" id="cb200-19" data-line-number="19">length_weight_condition &lt;-<span class="st"> </span>length_weight_condition <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb200-20" data-line-number="20"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Diet_comp =</span> <span class="kw">case_when</span>(Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">~</span><span class="st"> &quot;10.2:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-21" data-line-number="21">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">2</span> <span class="op">~</span><span class="st"> &quot;4.6:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-22" data-line-number="22">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">3</span> <span class="op">~</span><span class="st"> &quot;2.5:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-23" data-line-number="23">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">4</span> <span class="op">~</span><span class="st"> &quot;8.5:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-24" data-line-number="24">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">5</span> <span class="op">~</span><span class="st"> &quot;1.6:1&quot;</span>),</a>
<a class="sourceLine" id="cb200-25" data-line-number="25">         <span class="dt">Fish_size =</span> <span class="kw">case_when</span>(Fish_size <span class="op">==</span><span class="st"> &quot;S&quot;</span> <span class="op">~</span><span class="st"> &quot;Small&quot;</span>,</a>
<a class="sourceLine" id="cb200-26" data-line-number="26">                               Fish_size <span class="op">==</span><span class="st"> &quot;L&quot;</span> <span class="op">~</span><span class="st"> &quot;Large&quot;</span>),</a>
<a class="sourceLine" id="cb200-27" data-line-number="27">         <span class="dt">Sex =</span> <span class="kw">case_when</span>(Sex <span class="op">==</span><span class="st"> &quot;M&quot;</span> <span class="op">~</span><span class="st"> &quot;Male&quot;</span>,</a>
<a class="sourceLine" id="cb200-28" data-line-number="28">                         Sex <span class="op">==</span><span class="st"> &quot;F&quot;</span> <span class="op">~</span><span class="st"> &quot;Female&quot;</span>))</a>
<a class="sourceLine" id="cb200-29" data-line-number="29"></a>
<a class="sourceLine" id="cb200-30" data-line-number="30">mortality &lt;-<span class="st"> </span>mortality <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb200-31" data-line-number="31"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Diet_comp =</span> <span class="kw">case_when</span>(Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">~</span><span class="st"> &quot;10.2:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-32" data-line-number="32">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">2</span> <span class="op">~</span><span class="st"> &quot;4.6:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-33" data-line-number="33">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">3</span> <span class="op">~</span><span class="st"> &quot;2.5:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-34" data-line-number="34">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">4</span> <span class="op">~</span><span class="st"> &quot;8.5:1&quot;</span>,</a>
<a class="sourceLine" id="cb200-35" data-line-number="35">                               Diet_comp <span class="op">==</span><span class="st"> </span><span class="dv">5</span> <span class="op">~</span><span class="st"> &quot;1.6:1&quot;</span>),</a>
<a class="sourceLine" id="cb200-36" data-line-number="36">         <span class="dt">Fish_size =</span> <span class="kw">case_when</span>(Fish_size <span class="op">==</span><span class="st"> &quot;S&quot;</span> <span class="op">~</span><span class="st"> &quot;Small&quot;</span>,</a>
<a class="sourceLine" id="cb200-37" data-line-number="37">                               Fish_size <span class="op">==</span><span class="st"> &quot;L&quot;</span> <span class="op">~</span><span class="st"> &quot;Large&quot;</span>),</a>
<a class="sourceLine" id="cb200-38" data-line-number="38">         <span class="dt">Sex =</span> <span class="kw">case_when</span>(Sex <span class="op">==</span><span class="st"> &quot;M&quot;</span> <span class="op">~</span><span class="st"> &quot;Male&quot;</span>,</a>
<a class="sourceLine" id="cb200-39" data-line-number="39">                         Sex <span class="op">==</span><span class="st"> &quot;F&quot;</span> <span class="op">~</span><span class="st"> &quot;Female&quot;</span>),</a>
<a class="sourceLine" id="cb200-40" data-line-number="40">         <span class="dt">Status =</span> <span class="kw">case_when</span>(Status <span class="op">==</span><span class="st"> </span><span class="dv">0</span> <span class="op">~</span><span class="st"> &quot;alive&quot;</span>,</a>
<a class="sourceLine" id="cb200-41" data-line-number="41">                            Status <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">~</span><span class="st"> &quot;dead&quot;</span>))</a></code></pre></div>
<div id="checking-for-duplicates" class="section level3">
<h3><span class="header-section-number">7.2.1</span> Checking for duplicates</h3>
<p>Question: which of the four datasets contains an odd duplicate entry? And which fish is involved? What should we do next?</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" data-line-number="1"><span class="kw">sum</span>(<span class="kw">duplicated</span>(<span class="kw">select</span>(courtship, Fish_ID)))</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb203-1" data-line-number="1"><span class="kw">sum</span>(<span class="kw">duplicated</span>(<span class="kw">select</span>(eggs, Fish_ID)))</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb205-1" data-line-number="1"><span class="kw">sum</span>(<span class="kw">duplicated</span>(<span class="kw">select</span>(length_weight_condition, Fish_ID, Batch)))</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" data-line-number="1"><span class="kw">sum</span>(<span class="kw">duplicated</span>(<span class="kw">select</span>(mortality, Fish_ID, Week)))</a></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb209-1" data-line-number="1">dupl &lt;-<span class="st"> </span><span class="kw">duplicated</span>(<span class="kw">select</span>(mortality, Fish_ID, Week))</a>
<a class="sourceLine" id="cb209-2" data-line-number="2"><span class="kw">filter</span>(mortality, dupl)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   Fish_ID Diet_comp Sex   Prov_level Fish_size  Week Status
##   &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; 
## 1 LR504   1.6:1     Male         100 Small         2 alive</code></pre>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb211-1" data-line-number="1"><span class="kw">filter</span>(mortality, Fish_ID<span class="op">==</span><span class="st">&quot;LR504&quot;</span>, Week<span class="op">==</span><span class="dv">2</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 7
##   Fish_ID Diet_comp Sex   Prov_level Fish_size  Week Status
##   &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; 
## 1 LR504   1.6:1     Male         100 Small         2 dead  
## 2 LR504   1.6:1     Male         100 Small         2 alive</code></pre>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb213-1" data-line-number="1"><span class="kw">filter</span>(mortality, Fish_ID<span class="op">==</span><span class="st">&quot;LR504&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 4 x 7
##   Fish_ID Diet_comp Sex   Prov_level Fish_size  Week Status
##   &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; 
## 1 LR504   1.6:1     Male         100 Small         1 alive 
## 2 LR504   1.6:1     Male         100 Small         2 dead  
## 3 LR504   1.6:1     Male         100 Small         2 alive 
## 4 LR504   1.6:1     Male         100 Small         4 dead</code></pre>
<p>In the mortality dataset fish LR504 has two record for week 2.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb215-1" data-line-number="1">check &lt;-<span class="st"> </span>mortality <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(Fish_ID) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb215-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">check =</span> <span class="kw">length</span>(<span class="kw">unique</span>(Week))<span class="op">==</span><span class="kw">max</span>(Week))</a></code></pre></div>
</div>
<div id="nas-variable-entries-e.g.levels-of-characters-ranges-of-numerics-numbers-of-things" class="section level3">
<h3><span class="header-section-number">7.2.2</span> NAs, variable entries, e.g. levels of characters, ranges of numerics, numbers of “things”*</h3>
<p>How many missing values in the courtship dataset (remember to reduce the variables to those mentioned above)?</p>
<p>Which variable(s) contain missing values?</p>
<p>Which fish have missing values?</p>
<p>How many different entries are there in the <code>Shelf_stack</code> variable?</p>
<p>What are the mean and median of the <code>Total_court</code> variable?</p>
<p>What are the units of the <code>Total_court</code> variable? (From paper only, seconds)</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" data-line-number="1"><span class="kw">skim</span>(courtship)</a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-146">TABLE 7.1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">courtship</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">228</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">8</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">5</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Fish_ID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">228</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Family</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">22</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Shelf_stack</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">36</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Diet_comp</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Fish_size</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Prov_level</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">74.45</td>
<td align="right">20.38</td>
<td align="right">50</td>
<td align="right">50</td>
<td align="right">75</td>
<td align="right">100</td>
<td align="right">100</td>
<td align="left">▇▁▇▁▇</td>
</tr>
<tr class="even">
<td align="left">Trial</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4.57</td>
<td align="right">2.24</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">11</td>
<td align="left">▇▆▆▂▁</td>
</tr>
<tr class="odd">
<td align="left">Total_court</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">453.23</td>
<td align="right">456.20</td>
<td align="right">0</td>
<td align="right">64</td>
<td align="right">337</td>
<td align="right">713</td>
<td align="right">2666</td>
<td align="left">▇▃▁▁▁</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb217-1" data-line-number="1"><span class="kw">filter</span>(courtship, <span class="kw">is.na</span>(Total_court))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 8
##   Fish_ID Family Shelf_stack Diet_comp Prov_level Fish_size Trial Total_court
##   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1 LR021   F117   A3          8.5:1             50 Large         1          NA</code></pre>
<p>228 fish IDs</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb219-1" data-line-number="1"><span class="kw">skim</span>(eggs)</a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-147">TABLE 7.2: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">eggs</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">269</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">7</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">5</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Fish_ID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">269</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Family</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">20</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Shelf_stack</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">36</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Diet_comp</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Fish_size</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Prov_level</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">75.09</td>
<td align="right">20.32</td>
<td align="right">50</td>
<td align="right">50</td>
<td align="right">75</td>
<td align="right">100</td>
<td align="right">100</td>
<td align="left">▇▁▇▁▇</td>
</tr>
<tr class="even">
<td align="left">Total_egg</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1069.56</td>
<td align="right">631.56</td>
<td align="right">66</td>
<td align="right">609</td>
<td align="right">1001</td>
<td align="right">1402</td>
<td align="right">3608</td>
<td align="left">▇▇▃▁▁</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb220-1" data-line-number="1"><span class="kw">filter</span>(eggs, <span class="kw">is.na</span>(Total_egg))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   Fish_ID Family Shelf_stack Diet_comp Prov_level Fish_size Total_egg
##   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt;
## 1 LR212   F121   D3          2.5:1             75 Small            NA</code></pre>
<p>269 fish IDs</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb222-1" data-line-number="1"><span class="kw">skim</span>(length_weight_condition)</a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-148">TABLE 7.3: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">length_weight_condition</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">6000</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">10</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">5</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Fish_ID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">600</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Shelf_stack</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">36</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Diet_comp</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Sex</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Fish_size</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Batch</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">5.50</td>
<td align="right">2.87</td>
<td align="right">1.00</td>
<td align="right">3.00</td>
<td align="right">5.50</td>
<td align="right">8.00</td>
<td align="right">10.00</td>
<td align="left">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td align="left">Prov_level</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">75.00</td>
<td align="right">20.41</td>
<td align="right">50.00</td>
<td align="right">50.00</td>
<td align="right">75.00</td>
<td align="right">100.00</td>
<td align="right">100.00</td>
<td align="left">▇▁▇▁▇</td>
</tr>
<tr class="odd">
<td align="left">Length</td>
<td align="right">2088</td>
<td align="right">0.65</td>
<td align="right">47.58</td>
<td align="right">9.60</td>
<td align="right">3.75</td>
<td align="right">40.00</td>
<td align="right">48.00</td>
<td align="right">54.50</td>
<td align="right">78.00</td>
<td align="left">▁▁▇▇▁</td>
</tr>
<tr class="even">
<td align="left">Weigth</td>
<td align="right">2088</td>
<td align="right">0.65</td>
<td align="right">1.61</td>
<td align="right">1.01</td>
<td align="right">0.12</td>
<td align="right">0.74</td>
<td align="right">1.47</td>
<td align="right">2.27</td>
<td align="right">6.19</td>
<td align="left">▇▆▂▁▁</td>
</tr>
<tr class="odd">
<td align="left">Cond_index</td>
<td align="right">2088</td>
<td align="right">0.65</td>
<td align="right">0.00</td>
<td align="right">0.15</td>
<td align="right">-0.84</td>
<td align="right">-0.09</td>
<td align="right">0.00</td>
<td align="right">0.09</td>
<td align="right">1.54</td>
<td align="left">▁▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">600 fish IDs</td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb223-1" data-line-number="1"><span class="kw">skim</span>(mortality)</a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-149">TABLE 7.4: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">mortality</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">33049</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">7</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">5</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Fish_ID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">594</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Diet_comp</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Sex</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Fish_size</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Status</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Prov_level</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">74.49</td>
<td align="right">20.43</td>
<td align="right">50</td>
<td align="right">50</td>
<td align="right">75</td>
<td align="right">100</td>
<td align="right">100</td>
<td align="left">▇▁▇▁▇</td>
</tr>
<tr class="even">
<td align="left">Week</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">37.84</td>
<td align="right">26.49</td>
<td align="right">1</td>
<td align="right">16</td>
<td align="right">33</td>
<td align="right">57</td>
<td align="right">107</td>
<td align="left">▇▆▅▃▁</td>
</tr>
<tr class="odd">
<td align="left">594 fish IDs</td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="left"></td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="independence" class="section level2">
<h2><span class="header-section-number">7.3</span> Independence</h2>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" data-line-number="1"><span class="kw">table</span>(<span class="kw">pull</span>(courtship, Fish_ID))</a></code></pre></div>
<pre><code>## 
## LR001 LR004 LR005 LR010 LR019 LR021 LR022 LR023 LR024 LR033 LR034 LR042 LR046 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR048 LR049 LR052 LR056 LR057 LR060 LR062 LR064 LR069 LR070 LR071 LR072 LR077 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR087 LR093 LR095 LR099 LR102 LR106 LR109 LR111 LR113 LR117 LR118 LR124 LR126 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR129 LR130 LR132 LR136 LR137 LR139 LR140 LR141 LR143 LR148 LR150 LR154 LR157 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR158 LR161 LR165 LR167 LR174 LR175 LR176 LR178 LR182 LR184 LR185 LR186 LR187 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR189 LR190 LR192 LR200 LR201 LR205 LR206 LR208 LR209 LR210 LR211 LR214 LR218 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR221 LR224 LR226 LR227 LR230 LR235 LR238 LR244 LR246 LR247 LR248 LR249 LR257 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR258 LR259 LR264 LR265 LR268 LR269 LR273 LR276 LR277 LR279 LR283 LR284 LR285 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR294 LR299 LR300 LR302 LR303 LR304 LR305 LR311 LR312 LR314 LR315 LR322 LR327 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR328 LR329 LR331 LR332 LR333 LR334 LR340 LR347 LR348 LR352 LR353 LR358 LR360 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR361 LR363 LR364 LR366 LR367 LR368 LR372 LR373 LR374 LR379 LR380 LR381 LR383 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR384 LR385 LR386 LR390 LR391 LR392 LR394 LR395 LR402 LR404 LR405 LR406 LR412 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR413 LR415 LR416 LR420 LR421 LR422 LR423 LR427 LR429 LR430 LR438 LR440 LR442 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR445 LR452 LR453 LR454 LR456 LR459 LR460 LR462 LR463 LR464 LR465 LR471 LR472 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR473 LR475 LR477 LR478 LR480 LR481 LR485 LR489 LR493 LR500 LR502 LR503 LR505 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR516 LR518 LR524 LR532 LR537 LR539 LR541 LR542 LR544 LR546 LR549 LR551 LR552 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR555 LR557 LR558 LR559 LR560 LR570 LR572 LR573 LR574 LR577 LR578 LR581 LR584 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR585 LR591 LR594 LR596 LR597 LR598 LR600 
##     1     1     1     1     1     1     1</code></pre>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" data-line-number="1"><span class="kw">table</span>(<span class="kw">pull</span>(eggs, Fish_ID))</a></code></pre></div>
<pre><code>## 
## LR002 LR003 LR006 LR007 LR008 LR009 LR012 LR013 LR014 LR016 LR025 LR027 LR029 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR030 LR031 LR032 LR035 LR037 LR039 LR042 LR043 LR045 LR053 LR055 LR058 LR059 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR065 LR066 LR067 LR075 LR076 LR079 LR080 LR081 LR082 LR083 LR084 LR085 LR086 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR088 LR089 LR090 LR091 LR094 LR096 LR097 LR100 LR101 LR104 LR105 LR107 LR108 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR110 LR112 LR114 LR115 LR116 LR119 LR120 LR121 LR122 LR125 LR127 LR128 LR131 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR134 LR138 LR142 LR144 LR145 LR146 LR149 LR151 LR152 LR153 LR155 LR159 LR160 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR162 LR163 LR164 LR169 LR170 LR172 LR173 LR177 LR181 LR183 LR191 LR193 LR194 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR195 LR196 LR197 LR207 LR212 LR213 LR215 LR216 LR217 LR219 LR220 LR223 LR225 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR228 LR229 LR231 LR232 LR233 LR234 LR236 LR237 LR240 LR241 LR242 LR245 LR250 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR252 LR253 LR254 LR256 LR260 LR261 LR262 LR266 LR267 LR270 LR271 LR272 LR275 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR278 LR282 LR286 LR288 LR289 LR290 LR291 LR292 LR293 LR294 LR295 LR296 LR297 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR298 LR306 LR307 LR309 LR313 LR316 LR317 LR320 LR321 LR323 LR324 LR325 LR326 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR338 LR342 LR343 LR346 LR349 LR354 LR355 LR356 LR357 LR362 LR364 LR365 LR369 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR370 LR371 LR382 LR388 LR389 LR393 LR396 LR398 LR400 LR407 LR409 LR410 LR411 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR414 LR417 LR418 LR419 LR428 LR431 LR433 LR434 LR435 LR436 LR437 LR443 LR444 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR446 LR447 LR448 LR449 LR450 LR451 LR457 LR458 LR461 LR466 LR467 LR469 LR470 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR474 LR476 LR482 LR484 LR488 LR490 LR491 LR492 LR494 LR495 LR497 LR498 LR501 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR506 LR507 LR509 LR510 LR512 LR513 LR514 LR517 LR519 LR520 LR522 LR523 LR525 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR526 LR527 LR528 LR530 LR531 LR534 LR535 LR536 LR538 LR540 LR543 LR545 LR553 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR554 LR556 LR561 LR562 LR563 LR565 LR566 LR568 LR569 LR571 LR575 LR576 LR579 
##     1     1     1     1     1     1     1     1     1     1     1     1     1 
## LR580 LR581 LR582 LR583 LR587 LR588 LR592 LR595 LR599 
##     1     1     1     1     1     1     1     1     1</code></pre>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" data-line-number="1"><span class="kw">table</span>(<span class="kw">pull</span>(length_weight_condition, Fish_ID))</a></code></pre></div>
<pre><code>## 
## LR001 LR002 LR003 LR004 LR005 LR006 LR007 LR008 LR009 LR010 LR011 LR012 LR013 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR014 LR015 LR016 LR017 LR018 LR019 LR020 LR021 LR022 LR023 LR024 LR025 LR026 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR027 LR028 LR029 LR030 LR031 LR032 LR033 LR034 LR035 LR036 LR037 LR038 LR039 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR040 LR041 LR042 LR043 LR044 LR045 LR046 LR047 LR048 LR049 LR050 LR051 LR052 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR053 LR054 LR055 LR056 LR057 LR058 LR059 LR060 LR061 LR062 LR063 LR064 LR065 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR066 LR067 LR068 LR069 LR070 LR071 LR072 LR073 LR074 LR075 LR076 LR077 LR078 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR079 LR080 LR081 LR082 LR083 LR084 LR085 LR086 LR087 LR088 LR089 LR090 LR091 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR092 LR093 LR094 LR095 LR096 LR097 LR098 LR099 LR100 LR101 LR102 LR103 LR104 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR105 LR106 LR107 LR108 LR109 LR110 LR111 LR112 LR113 LR114 LR115 LR116 LR117 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR118 LR119 LR120 LR121 LR122 LR123 LR124 LR125 LR126 LR127 LR128 LR129 LR130 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR131 LR132 LR133 LR134 LR135 LR136 LR137 LR138 LR139 LR140 LR141 LR142 LR143 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR144 LR145 LR146 LR147 LR148 LR149 LR150 LR151 LR152 LR153 LR154 LR155 LR156 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR157 LR158 LR159 LR160 LR161 LR162 LR163 LR164 LR165 LR166 LR167 LR168 LR169 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR170 LR171 LR172 LR173 LR174 LR175 LR176 LR177 LR178 LR179 LR180 LR181 LR182 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR183 LR184 LR185 LR186 LR187 LR188 LR189 LR190 LR191 LR192 LR193 LR194 LR195 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR196 LR197 LR198 LR199 LR200 LR201 LR202 LR203 LR204 LR205 LR206 LR207 LR208 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR209 LR210 LR211 LR212 LR213 LR214 LR215 LR216 LR217 LR218 LR219 LR220 LR221 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR222 LR223 LR224 LR225 LR226 LR227 LR228 LR229 LR230 LR231 LR232 LR233 LR234 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR235 LR236 LR237 LR238 LR239 LR240 LR241 LR242 LR243 LR244 LR245 LR246 LR247 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR248 LR249 LR250 LR251 LR252 LR253 LR254 LR255 LR256 LR257 LR258 LR259 LR260 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR261 LR262 LR263 LR264 LR265 LR266 LR267 LR268 LR269 LR270 LR271 LR272 LR273 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR274 LR275 LR276 LR277 LR278 LR279 LR280 LR281 LR282 LR283 LR284 LR285 LR286 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR287 LR288 LR289 LR290 LR291 LR292 LR293 LR294 LR295 LR296 LR297 LR298 LR299 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR300 LR301 LR302 LR303 LR304 LR305 LR306 LR307 LR308 LR309 LR310 LR311 LR312 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR313 LR314 LR315 LR316 LR317 LR318 LR319 LR320 LR321 LR322 LR323 LR324 LR325 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR326 LR327 LR328 LR329 LR330 LR331 LR332 LR333 LR334 LR335 LR336 LR337 LR338 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR339 LR340 LR341 LR342 LR343 LR344 LR345 LR346 LR347 LR348 LR349 LR350 LR351 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR352 LR353 LR354 LR355 LR356 LR357 LR358 LR359 LR360 LR361 LR362 LR363 LR364 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR365 LR366 LR367 LR368 LR369 LR370 LR371 LR372 LR373 LR374 LR375 LR376 LR377 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR378 LR379 LR380 LR381 LR382 LR383 LR384 LR385 LR386 LR387 LR388 LR389 LR390 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR391 LR392 LR393 LR394 LR395 LR396 LR397 LR398 LR399 LR400 LR401 LR402 LR403 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR404 LR405 LR406 LR407 LR408 LR409 LR410 LR411 LR412 LR413 LR414 LR415 LR416 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR417 LR418 LR419 LR420 LR421 LR422 LR423 LR424 LR425 LR426 LR427 LR428 LR429 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR430 LR431 LR432 LR433 LR434 LR435 LR436 LR437 LR438 LR439 LR440 LR441 LR442 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR443 LR444 LR445 LR446 LR447 LR448 LR449 LR450 LR451 LR452 LR453 LR454 LR455 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR456 LR457 LR458 LR459 LR460 LR461 LR462 LR463 LR464 LR465 LR466 LR467 LR468 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR469 LR470 LR471 LR472 LR473 LR474 LR475 LR476 LR477 LR478 LR479 LR480 LR481 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR482 LR483 LR484 LR485 LR486 LR487 LR488 LR489 LR490 LR491 LR492 LR493 LR494 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR495 LR496 LR497 LR498 LR499 LR500 LR501 LR502 LR503 LR504 LR505 LR506 LR507 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR508 LR509 LR510 LR511 LR512 LR513 LR514 LR515 LR516 LR517 LR518 LR519 LR520 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR521 LR522 LR523 LR524 LR525 LR526 LR527 LR528 LR529 LR530 LR531 LR532 LR533 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR534 LR535 LR536 LR537 LR538 LR539 LR540 LR541 LR542 LR543 LR544 LR545 LR546 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR547 LR548 LR549 LR550 LR551 LR552 LR553 LR554 LR555 LR556 LR557 LR558 LR559 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR560 LR561 LR562 LR563 LR564 LR565 LR566 LR567 LR568 LR569 LR570 LR571 LR572 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR573 LR574 LR575 LR576 LR577 LR578 LR579 LR580 LR581 LR582 LR583 LR584 LR585 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR586 LR587 LR588 LR589 LR590 LR591 LR592 LR593 LR594 LR595 LR596 LR597 LR598 
##    10    10    10    10    10    10    10    10    10    10    10    10    10 
## LR599 LR600 
##    10    10</code></pre>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" data-line-number="1"><span class="kw">table</span>(<span class="kw">pull</span>(mortality, Fish_ID))</a></code></pre></div>
<pre><code>## 
## LR001 LR002 LR003 LR004 LR005 LR006 LR007 LR008 LR009 LR010 LR011 LR012 LR013 
##   107    84    91    34   107    53    81    39    80    69     5    72    97 
## LR014 LR015 LR016 LR017 LR018 LR019 LR020 LR021 LR022 LR023 LR024 LR025 LR026 
##    62     3    73     2     3    47     2    39    44   107    91    29    10 
## LR027 LR028 LR029 LR030 LR031 LR032 LR033 LR034 LR035 LR036 LR037 LR038 LR039 
##    31     2    80    24    42    40   107    85    32     3    57    33    77 
## LR040 LR041 LR042 LR043 LR044 LR045 LR046 LR047 LR048 LR049 LR050 LR051 LR052 
##    90     2    95    40    18    77    42    17   107   107     6     2    98 
## LR053 LR054 LR055 LR056 LR057 LR058 LR059 LR060 LR061 LR062 LR063 LR064 LR065 
##    41     2    53    85    91    58    18    39     1    72     4    86    38 
## LR066 LR067 LR068 LR069 LR070 LR071 LR072 LR073 LR074 LR075 LR076 LR077 LR078 
##    58    39    25    36    86    82    62    16     2    87    73    51     6 
## LR079 LR080 LR081 LR082 LR083 LR084 LR085 LR086 LR087 LR088 LR089 LR090 LR091 
##    53    74    67    83    67    37    42    73    82    37    37    39    40 
## LR092 LR093 LR094 LR095 LR096 LR097 LR098 LR099 LR100 LR101 LR102 LR104 LR105 
##     6    40    85    32    88    30    10    87    88    95    97    82    66 
## LR106 LR107 LR108 LR109 LR110 LR111 LR112 LR113 LR114 LR115 LR116 LR117 LR118 
##    39    97   107   107    88    79    30    84    74    98    39    31    30 
## LR119 LR120 LR121 LR122 LR123 LR124 LR125 LR126 LR127 LR128 LR129 LR130 LR131 
##    79    81    77   107     7   107    38   107    94    39    33   107    90 
## LR132 LR133 LR134 LR135 LR136 LR137 LR138 LR139 LR140 LR141 LR142 LR143 LR144 
##    82     9    32    87    91    86    29    55    78    81    39    37    62 
## LR145 LR146 LR147 LR148 LR149 LR150 LR151 LR152 LR153 LR154 LR155 LR157 LR158 
##    41    32     6   107    69    33    96    85    76    37    32    88    93 
## LR159 LR160 LR161 LR162 LR163 LR164 LR165 LR167 LR168 LR169 LR170 LR171 LR172 
##    81    80    38    48    41    83   107    22     3    38    34     2    78 
## LR173 LR174 LR175 LR176 LR177 LR178 LR179 LR180 LR181 LR182 LR183 LR184 LR185 
##    33    85    33    29    33    77     5    10    42    33    38    30   107 
## LR186 LR187 LR189 LR190 LR191 LR192 LR193 LR194 LR195 LR196 LR197 LR198 LR199 
##    32   102    97    41    39    57    46    54    54    40    39     4    17 
## LR200 LR201 LR202 LR203 LR204 LR205 LR206 LR207 LR208 LR209 LR210 LR211 LR212 
##    44    88     9    38     7    27    94    38    47    91    81   107    25 
## LR213 LR214 LR215 LR216 LR217 LR218 LR219 LR220 LR221 LR222 LR223 LR224 LR225 
##    48    41    32    48    82    64    47    25   107    14    38    39    43 
## LR226 LR227 LR228 LR229 LR230 LR231 LR232 LR233 LR234 LR235 LR236 LR237 LR238 
##    87    91    28    39    70    66    84    83    90   107    58    40    80 
## LR239 LR240 LR241 LR242 LR243 LR244 LR245 LR246 LR247 LR248 LR249 LR250 LR251 
##     7    38    54    42    13    43    32    91   107   107   107    26    31 
## LR252 LR253 LR254 LR255 LR256 LR257 LR258 LR259 LR260 LR261 LR262 LR263 LR264 
##    31    53    40     4    86   107    84    44    36    32    32     1    82 
## LR265 LR266 LR267 LR268 LR269 LR270 LR271 LR272 LR273 LR274 LR275 LR276 LR277 
##    85    83    77    80   107    22    38    85    79     3    87    60    92 
## LR278 LR279 LR281 LR282 LR283 LR284 LR285 LR286 LR287 LR288 LR289 LR290 LR291 
##    37    84     4    53    35    45    41    17     2    87    34    96    84 
## LR292 LR293 LR294 LR295 LR296 LR297 LR298 LR299 LR300 LR301 LR302 LR303 LR304 
##    39    36   107    81    37   107    88    43    31     1    50   107    55 
## LR305 LR306 LR307 LR308 LR309 LR310 LR311 LR312 LR313 LR314 LR315 LR316 LR317 
##    60    32    44     2    35     1    32    45    36    99   107    82    33 
## LR318 LR320 LR321 LR322 LR323 LR324 LR325 LR326 LR327 LR328 LR329 LR330 LR331 
##     8    26    37    43    48    37    43    44    33   100    42     7    62 
## LR332 LR333 LR334 LR335 LR336 LR337 LR338 LR339 LR340 LR341 LR342 LR343 LR344 
##    84    81   107     9     2     1    39     3    31     2    41    80     9 
## LR345 LR346 LR347 LR348 LR349 LR350 LR351 LR352 LR353 LR354 LR355 LR356 LR357 
##    12    26    63    91    36     3     4    87    37    46    37    38    30 
## LR358 LR359 LR360 LR361 LR362 LR363 LR364 LR365 LR366 LR367 LR368 LR369 LR370 
##    40    40    91   107    95    82    26    32    83   107    91    87    33 
## LR371 LR372 LR373 LR374 LR375 LR376 LR377 LR378 LR379 LR380 LR381 LR382 LR383 
##    30    50    36   104    13     1    27     4    85    92    38    40   107 
## LR384 LR385 LR386 LR387 LR388 LR389 LR390 LR391 LR392 LR393 LR394 LR395 LR396 
##    83    89    75    16    78    85    92    90    48    41   107   107    28 
## LR397 LR398 LR399 LR400 LR401 LR402 LR403 LR404 LR405 LR406 LR407 LR408 LR409 
##    17    43     7    96     2   107     2    51    86    46    69     5    23 
## LR410 LR411 LR412 LR413 LR414 LR415 LR416 LR417 LR418 LR419 LR420 LR421 LR422 
##    46    33    41    73    34    97    44    33    38    31   107   107    33 
## LR423 LR424 LR425 LR426 LR427 LR428 LR429 LR430 LR431 LR432 LR433 LR434 LR435 
##    82    13     2    39   107    46    86    83    36     8   102    64    73 
## LR436 LR437 LR438 LR439 LR440 LR441 LR442 LR443 LR444 LR445 LR446 LR447 LR448 
##    29    41    69    35    34     6   107    37    79    70    22    55    55 
## LR449 LR450 LR451 LR452 LR453 LR454 LR455 LR456 LR457 LR458 LR459 LR460 LR461 
##    43    89    58    90    91    80     4   107    70    53   101    82    79 
## LR462 LR463 LR464 LR465 LR466 LR467 LR468 LR469 LR470 LR471 LR472 LR473 LR474 
##    35    52   107   107    55    22    19    49    59   107   106    35    55 
## LR475 LR476 LR477 LR478 LR479 LR480 LR481 LR482 LR483 LR484 LR485 LR486 LR487 
##    99    84    34    35     2    40    91    85    17    80    73     3    93 
## LR488 LR489 LR490 LR491 LR492 LR493 LR494 LR495 LR496 LR497 LR498 LR499 LR500 
##    55    83    73    91    97    96    73    44     1    46    41     8    90 
## LR501 LR502 LR503 LR504 LR505 LR506 LR507 LR508 LR509 LR510 LR511 LR512 LR513 
##    31    95    96     4    96    40    22     4    95    30    10    36   107 
## LR514 LR515 LR516 LR517 LR518 LR519 LR520 LR521 LR522 LR523 LR524 LR525 LR526 
##   107    11   107    79    94    36   107    17    41    82    87    51    98 
## LR527 LR528 LR529 LR530 LR531 LR532 LR533 LR534 LR535 LR536 LR537 LR538 LR539 
##    76    58     3    58    85    85    11    88    91    31   107    24    94 
## LR540 LR541 LR542 LR543 LR544 LR545 LR546 LR547 LR548 LR549 LR550 LR551 LR552 
##    30   107    83    61    51    46    41    35     5    32     3    94   107 
## LR553 LR554 LR555 LR556 LR557 LR558 LR559 LR560 LR561 LR562 LR563 LR564 LR565 
##    37    82    27    87    47   102    88    82    90    29    74    16    81 
## LR566 LR567 LR568 LR569 LR570 LR571 LR572 LR573 LR574 LR575 LR576 LR577 LR578 
##    70    11    36    69   107    33    75    75    76    39    23    39    32 
## LR579 LR580 LR581 LR582 LR583 LR584 LR585 LR586 LR587 LR588 LR589 LR590 LR591 
##    40    87    70    28    29    86   107    15    56    41     1     7    87 
## LR592 LR593 LR594 LR595 LR596 LR597 LR598 LR599 LR600 
##    89    16   107    34   107    92    31    22    91</code></pre>
</div>
<div id="balance-in-experimental-design" class="section level2">
<h2><span class="header-section-number">7.4</span> Balance in experimental design</h2>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" data-line-number="1">temp &lt;-<span class="st"> </span>courtship <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb232-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(Diet_comp, Prov_level) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb232-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count=</span><span class="kw">n</span>(),</a>
<a class="sourceLine" id="cb232-4" data-line-number="4">            <span class="dt">n_unique=</span><span class="kw">length</span>(<span class="kw">unique</span>(Fish_ID)))</a>
<a class="sourceLine" id="cb232-5" data-line-number="5"><span class="kw">sum</span>(<span class="kw">pull</span>(temp, n_unique))</a></code></pre></div>
<pre><code>## [1] 228</code></pre>
<p>228 Fish_IDs is what we found already for this dataset.</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" data-line-number="1">temp &lt;-<span class="st"> </span>eggs <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb234-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(Diet_comp, Prov_level) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb234-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="kw">n</span>(),</a>
<a class="sourceLine" id="cb234-4" data-line-number="4">            <span class="dt">n_unique=</span><span class="kw">length</span>(<span class="kw">unique</span>(Fish_ID)))</a>
<a class="sourceLine" id="cb234-5" data-line-number="5"><span class="kw">sum</span>(<span class="kw">pull</span>(temp, n_unique))</a></code></pre></div>
<pre><code>## [1] 269</code></pre>
<p>269 Fish_IDs is what we found already for this dataset.
WHY??? 21 for 2.5:1 100 21 21
Check below.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" data-line-number="1">egg_ids &lt;-<span class="st"> </span><span class="kw">unique</span>(<span class="kw">pull</span>(eggs, Fish_ID))</a>
<a class="sourceLine" id="cb236-2" data-line-number="2">courtship_ids &lt;-<span class="st"> </span><span class="kw">unique</span>(<span class="kw">pull</span>(courtship, Fish_ID))</a>
<a class="sourceLine" id="cb236-3" data-line-number="3"><span class="kw">length</span>(<span class="kw">unique</span>(<span class="kw">c</span>(egg_ids, courtship_ids)))</a></code></pre></div>
<pre><code>## [1] 493</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" data-line-number="1">length_weight_condition <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb238-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(Diet_comp, Prov_level) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb238-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="kw">n</span>(),</a>
<a class="sourceLine" id="cb238-4" data-line-number="4">            <span class="dt">n_unique=</span><span class="kw">length</span>(<span class="kw">unique</span>(Fish_ID)))</a></code></pre></div>
<pre><code>## # A tibble: 15 x 4
##   Diet_comp Prov_level `n()` n_unique
##   &lt;chr&gt;          &lt;dbl&gt; &lt;int&gt;    &lt;int&gt;
## 1 1.6:1             50   400       40
## 2 1.6:1             75   400       40
## 3 1.6:1            100   400       40
## 4 10.2:1            50   400       40
## 5 10.2:1            75   400       40
## # … with 10 more rows</code></pre>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" data-line-number="1"><span class="kw">length</span>(<span class="kw">unique</span>(<span class="kw">pull</span>(length_weight_condition, Fish_ID)))</a></code></pre></div>
<pre><code>## [1] 600</code></pre>
<p>40 of each, hence 600 fish IDs</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" data-line-number="1">mortality <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb242-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(Diet_comp, Prov_level) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb242-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="kw">n</span>(),</a>
<a class="sourceLine" id="cb242-4" data-line-number="4">            <span class="dt">n_unique=</span><span class="kw">length</span>(<span class="kw">unique</span>(Fish_ID)))</a></code></pre></div>
<pre><code>## # A tibble: 15 x 4
##   Diet_comp Prov_level `n()` n_unique
##   &lt;chr&gt;          &lt;dbl&gt; &lt;int&gt;    &lt;int&gt;
## 1 1.6:1             50  2239       39
## 2 1.6:1             75  2519       40
## 3 1.6:1            100  2258       40
## 4 10.2:1            50  1951       40
## 5 10.2:1            75  1668       39
## # … with 10 more rows</code></pre>
<p>39 or 40 of each (six of 39, hence 594 fish IDs)</p>
</div>
<div id="calculate-response-variables-if-required" class="section level2">
<h2><span class="header-section-number">7.5</span> Calculate response variable(s) (if required)</h2>
<p>The courtship and eggs datasets already contain the response variable.
We need to calculate the response variable for the change in fish length and change in body condition from the <code>length_weight_condition</code> dataset, and the time of death (or no death [censored]) from the <code>mortality</code> dataset.</p>
<div id="time-of-death" class="section level3">
<h3><span class="header-section-number">7.5.1</span> Time of death</h3>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb244-1" data-line-number="1">temp_mortality2 &lt;-<span class="st"> </span>mortality <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb244-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(Status<span class="op">==</span><span class="st">&quot;alive&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb244-3" data-line-number="3"><span class="st">  </span><span class="kw">group_by</span>(Fish_ID, Diet_comp, Prov_level, Sex) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb244-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Lifespan=</span><span class="kw">max</span>(Week))</a>
<a class="sourceLine" id="cb244-5" data-line-number="5">last_obs &lt;-<span class="st"> </span>mortality  <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb244-6" data-line-number="6"><span class="st">  </span><span class="kw">group_by</span>(Fish_ID, Diet_comp, Prov_level) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb244-7" data-line-number="7"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Last_sample=</span><span class="kw">max</span>(Week))</a>
<a class="sourceLine" id="cb244-8" data-line-number="8">mortality2 &lt;-<span class="st"> </span><span class="kw">full_join</span>(temp_mortality2, last_obs) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb244-9" data-line-number="9"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Censored=</span><span class="kw">ifelse</span>(Lifespan<span class="op">==</span>Last_sample, T, F),</a>
<a class="sourceLine" id="cb244-10" data-line-number="10">         <span class="dt">Lifespan=</span><span class="kw">ifelse</span>(<span class="kw">is.na</span>(Lifespan), <span class="dv">0</span>, Lifespan),</a>
<a class="sourceLine" id="cb244-11" data-line-number="11">         <span class="dt">Censored=</span><span class="kw">ifelse</span>(Lifespan<span class="op">==</span><span class="dv">0</span>, <span class="ot">FALSE</span>, Censored)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb244-12" data-line-number="12"><span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb244-13" data-line-number="13"><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>Last_sample)</a></code></pre></div>
<pre><code>## Joining, by = c(&quot;Fish_ID&quot;, &quot;Diet_comp&quot;, &quot;Prov_level&quot;)</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb246-1" data-line-number="1"><span class="kw">skim</span>(mortality2)</a></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-156">TABLE 7.5: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">mortality2</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">594</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">6</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">3</td>
</tr>
<tr class="odd">
<td align="left">logical</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Fish_ID</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">594</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Diet_comp</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">5</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Sex</td>
<td align="right">8</td>
<td align="right">0.99</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="left">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Censored</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.09</td>
<td align="left">FAL: 541, TRU: 53</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Prov_level</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">75.04</td>
<td align="right">20.46</td>
<td align="right">50</td>
<td align="right">50</td>
<td align="right">75</td>
<td align="right">100</td>
<td align="right">100</td>
<td align="left">▇▁▇▁▇</td>
</tr>
<tr class="even">
<td align="left">Lifespan</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">54.73</td>
<td align="right">32.73</td>
<td align="right">0</td>
<td align="right">31</td>
<td align="right">47</td>
<td align="right">84</td>
<td align="right">107</td>
<td align="left">▅▇▃▅▆</td>
</tr>
</tbody>
</table>
<p>Above, we set the eight fish that were already dead at week 1 as having a lifespan of zero.</p>
</div>
<div id="change-in-length" class="section level3">
<h3><span class="header-section-number">7.5.2</span> Change in length</h3>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb247-1" data-line-number="1">change1 &lt;-<span class="st"> </span>length_weight_condition <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb247-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(Fish_ID, Diet_comp, Prov_level) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb247-3" data-line-number="3"><span class="st">  </span><span class="kw">do</span>(<span class="dt">m1 =</span> <span class="kw">lm</span>(Length <span class="op">~</span><span class="st"> </span>Batch, <span class="dt">data=</span>.)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb247-4" data-line-number="4"><span class="st">  </span><span class="kw">tidy</span>(m1) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb247-5" data-line-number="5"><span class="st">  </span><span class="kw">filter</span>(term<span class="op">==</span><span class="st">&quot;Batch&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb247-6" data-line-number="6"><span class="st">  </span><span class="kw">select</span>(Fish_ID, Diet_comp, Prov_level, <span class="dt">Length_change=</span>estimate)</a></code></pre></div>
<p>Note that <code>tidy</code> silently drops NA coefficients.</p>
</div>
<div id="change-in-condition" class="section level3">
<h3><span class="header-section-number">7.5.3</span> Change in condition</h3>
<p>Not quite what they did in the paper. But…</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" data-line-number="1">change2 &lt;-<span class="st"> </span>length_weight_condition <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb248-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(Fish_ID, Diet_comp, Prov_level) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb248-3" data-line-number="3"><span class="st">  </span><span class="kw">do</span>(<span class="dt">m1 =</span> <span class="kw">lm</span>(Cond_index <span class="op">~</span><span class="st"> </span>Batch, <span class="dt">data=</span>.)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb248-4" data-line-number="4"><span class="st">  </span><span class="kw">tidy</span>(m1) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb248-5" data-line-number="5"><span class="st">  </span><span class="kw">filter</span>(term<span class="op">==</span><span class="st">&quot;Batch&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb248-6" data-line-number="6"><span class="st">  </span><span class="kw">select</span>(Fish_ID, Diet_comp, Prov_level, <span class="dt">CI_change=</span>estimate)</a></code></pre></div>
<p>Note that <code>tidy</code> silently drops NA coefficients.</p>
</div>
</div>
<div id="merge-all-datasets-together-and-check-for-correct-number-of-rows" class="section level2">
<h2><span class="header-section-number">7.6</span> Merge all datasets together and check for correct number of rows</h2>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb249-1" data-line-number="1">dd &lt;-<span class="st"> </span><span class="kw">full_join</span>(courtship, eggs) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb249-2" data-line-number="2"><span class="st">  </span><span class="kw">full_join</span>(mortality2) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb249-3" data-line-number="3"><span class="st">  </span><span class="kw">full_join</span>(change1) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb249-4" data-line-number="4"><span class="st">  </span><span class="kw">full_join</span>(change2)</a></code></pre></div>
<pre><code>## Joining, by = c(&quot;Fish_ID&quot;, &quot;Family&quot;, &quot;Shelf_stack&quot;, &quot;Diet_comp&quot;, &quot;Prov_level&quot;,
## &quot;Fish_size&quot;)Joining, by = c(&quot;Fish_ID&quot;, &quot;Diet_comp&quot;, &quot;Prov_level&quot;)Joining, by =
## c(&quot;Fish_ID&quot;, &quot;Diet_comp&quot;, &quot;Prov_level&quot;)Joining, by = c(&quot;Fish_ID&quot;, &quot;Diet_comp&quot;,
## &quot;Prov_level&quot;)</code></pre>
<p>Bring in and merge the diet comp data</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb251-1" data-line-number="1">diet_comp &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/diet_comp_treatments.csv&quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Protein = col_double(),
##   Lipid = col_double(),
##   Diet_comp = col_character()
## )</code></pre>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb253-1" data-line-number="1">dd &lt;-<span class="st"> </span><span class="kw">full_join</span>(dd, diet_comp)</a></code></pre></div>
<pre><code>## Joining, by = &quot;Diet_comp&quot;</code></pre>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb255-1" data-line-number="1">dd &lt;-<span class="st"> </span><span class="kw">mutate</span>(dd,</a>
<a class="sourceLine" id="cb255-2" data-line-number="2">             <span class="dt">Diet_comp =</span> <span class="kw">fct_relevel</span>(Diet_comp,</a>
<a class="sourceLine" id="cb255-3" data-line-number="3">                                            <span class="st">&quot;1.6:1&quot;</span>,</a>
<a class="sourceLine" id="cb255-4" data-line-number="4">                                            <span class="st">&quot;2.5:1&quot;</span>,</a>
<a class="sourceLine" id="cb255-5" data-line-number="5">                                            <span class="st">&quot;4.6:1&quot;</span>,</a>
<a class="sourceLine" id="cb255-6" data-line-number="6">                                            <span class="st">&quot;8.5:1&quot;</span>,</a>
<a class="sourceLine" id="cb255-7" data-line-number="7">                                            <span class="st">&quot;10.2:1&quot;</span>),</a>
<a class="sourceLine" id="cb255-8" data-line-number="8">             <span class="dt">Prov_level =</span> <span class="kw">fct_relevel</span>(<span class="kw">as.character</span>(Prov_level),</a>
<a class="sourceLine" id="cb255-9" data-line-number="9">                                            <span class="st">&quot;50&quot;</span>,</a>
<a class="sourceLine" id="cb255-10" data-line-number="10">                                            <span class="st">&quot;75&quot;</span>,</a>
<a class="sourceLine" id="cb255-11" data-line-number="11">                                            <span class="st">&quot;100&quot;</span>))</a></code></pre></div>
</div>
<div id="super-sleuth-questions" class="section level2">
<h2><span class="header-section-number">7.7</span> Super sleuth questions</h2>
<p>About:</p>
<ul>
<li>Two females doing courtship, perhaps odd?</li>
<li>Some males laying eggs… a bit strange.</li>
</ul>
</div>
<div id="inspect-shapes-distributions" class="section level2">
<h2><span class="header-section-number">7.8</span> Inspect shapes (distributions)</h2>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb256-1" data-line-number="1"><span class="kw">ggplot</span>(dd, <span class="kw">aes</span>(<span class="dt">x=</span>Total_court)) <span class="op">+</span></a>
<a class="sourceLine" id="cb256-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 367 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="insights_website_files/figure-html/unnamed-chunk-162-1.svg" width="336" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb259-1" data-line-number="1"><span class="kw">ggplot</span>(dd, <span class="kw">aes</span>(<span class="dt">x=</span>Total_egg)) <span class="op">+</span></a>
<a class="sourceLine" id="cb259-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 326 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="insights_website_files/figure-html/unnamed-chunk-162-2.svg" width="336" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb262-1" data-line-number="1"><span class="kw">ggplot</span>(dd, <span class="kw">aes</span>(<span class="dt">x=</span>Lifespan)) <span class="op">+</span></a>
<a class="sourceLine" id="cb262-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="insights_website_files/figure-html/unnamed-chunk-162-3.svg" width="336" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb264-1" data-line-number="1"><span class="kw">ggplot</span>(dd, <span class="kw">aes</span>(<span class="dt">x=</span>Length_change)) <span class="op">+</span></a>
<a class="sourceLine" id="cb264-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 26 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="insights_website_files/figure-html/unnamed-chunk-162-4.svg" width="336" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb267-1" data-line-number="1"><span class="kw">ggplot</span>(dd, <span class="kw">aes</span>(<span class="dt">x=</span>CI_change)) <span class="op">+</span></a>
<a class="sourceLine" id="cb267-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 26 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="insights_website_files/figure-html/unnamed-chunk-162-5.svg" width="336" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" data-line-number="1">dd &lt;-<span class="st"> </span>dd <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb270-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">period=</span><span class="kw">cut</span>(Lifespan, <span class="dt">breaks=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">20</span>, <span class="dv">60</span>, <span class="dv">106</span>, <span class="dv">120</span>)))</a></code></pre></div>
</div>
<div id="inspect-relationships" class="section level2">
<h2><span class="header-section-number">7.9</span> Inspect relationships</h2>
<p>“Male mortality risk was lowest on intermediate lipid intakes”.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb271-1" data-line-number="1">dd <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex<span class="op">==</span><span class="st">&quot;Male&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb271-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Lipid, <span class="dt">y=</span>Lifespan, <span class="dt">col=</span>Prov_level)) <span class="op">+</span></a>
<a class="sourceLine" id="cb271-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">position =</span> <span class="kw">position_jitterdodge</span>(<span class="dt">jitter.width=</span><span class="fl">0.05</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb271-4" data-line-number="4"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>period, <span class="dt">nrow=</span><span class="dv">3</span>)</a></code></pre></div>
<p><img src="insights_website_files/figure-html/unnamed-chunk-163-1.svg" width="336" style="display: block; margin: auto;" /></p>
<p>“Female risk was generally reduced by low protein intakes.”</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb272-1" data-line-number="1">dd <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex<span class="op">==</span><span class="st">&quot;Female&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb272-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Protein, <span class="dt">y=</span>Lifespan, <span class="dt">col=</span>Prov_level)) <span class="op">+</span></a>
<a class="sourceLine" id="cb272-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">position =</span> <span class="kw">position_jitterdodge</span>(<span class="dt">jitter.width=</span><span class="fl">0.05</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb272-4" data-line-number="4"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>period, <span class="dt">nrow=</span><span class="dv">3</span>)</a></code></pre></div>
<p><img src="insights_website_files/figure-html/unnamed-chunk-164-1.svg" width="336" style="display: block; margin: auto;" /></p>
<p>“The effect of macronutrient intake on reproduction was similar between the sexes, with high protein intakes maximizing reproduction.”</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb273-1" data-line-number="1">dd <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex<span class="op">==</span><span class="st">&quot;Male&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb273-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Protein, <span class="dt">y=</span>Total_court, <span class="dt">col=</span>Prov_level)) <span class="op">+</span></a>
<a class="sourceLine" id="cb273-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">position =</span> <span class="kw">position_jitterdodge</span>(<span class="dt">jitter.width=</span><span class="fl">0.05</span>))</a></code></pre></div>
<pre><code>## Warning: Removed 67 rows containing missing values (geom_point).</code></pre>
<p><img src="insights_website_files/figure-html/unnamed-chunk-165-1.svg" width="336" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb275-1" data-line-number="1">dd <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex<span class="op">==</span><span class="st">&quot;Female&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb275-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Protein, <span class="dt">y=</span>Total_court, <span class="dt">col=</span>Prov_level)) <span class="op">+</span></a>
<a class="sourceLine" id="cb275-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">position =</span> <span class="kw">position_jitterdodge</span>(<span class="dt">jitter.width=</span><span class="fl">0.05</span>))</a></code></pre></div>
<pre><code>## Warning: Removed 292 rows containing missing values (geom_point).</code></pre>
<p><img src="insights_website_files/figure-html/unnamed-chunk-165-2.svg" width="336" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb277-1" data-line-number="1">dd <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex<span class="op">==</span><span class="st">&quot;Male&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb277-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Protein, <span class="dt">y=</span>Total_egg, <span class="dt">col=</span>Prov_level)) <span class="op">+</span></a>
<a class="sourceLine" id="cb277-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">position =</span> <span class="kw">position_jitterdodge</span>(<span class="dt">jitter.width=</span><span class="fl">0.05</span>))</a></code></pre></div>
<pre><code>## Warning: Removed 288 rows containing missing values (geom_point).</code></pre>
<p><img src="insights_website_files/figure-html/unnamed-chunk-166-1.svg" width="336" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb279-1" data-line-number="1">dd <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex<span class="op">==</span><span class="st">&quot;Female&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb279-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Protein, <span class="dt">y=</span>Total_egg, <span class="dt">col=</span>Prov_level)) <span class="op">+</span></a>
<a class="sourceLine" id="cb279-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">position =</span> <span class="kw">position_jitterdodge</span>(<span class="dt">jitter.width=</span><span class="fl">0.2</span>, <span class="dt">dodge.width =</span> <span class="dv">5</span>))</a></code></pre></div>
<pre><code>## Warning: position_jitterdodge requires non-overlapping x intervals</code></pre>
<pre><code>## Warning: Removed 30 rows containing missing values (geom_point).</code></pre>
<p><img src="insights_website_files/figure-html/unnamed-chunk-166-2.svg" width="336" style="display: block; margin: auto;" /></p>
</div>
<div id="moatt-et-al-data-s1-mortality-data" class="section level2">
<h2><span class="header-section-number">7.10</span> Moatt et al Data S1 – Mortality Data</h2>
<ul>
<li>FID – Unique ID for each individual.</li>
<li>Diet – Diet Treatment (Diet P:L: 1 = 10.2:1, 2 = 4.6:1, 3 = 2.5:1, 4 = 8.5:1, 5 = 1.6:1).</li>
<li>Sex – Sex of individual (M = male, F = female).</li>
<li>Size – Size classification of individual (L = large, S = Small).</li>
<li>Level – Provisioning level, values represent percentages of monthly ad libitum monitoring.</li>
<li>Total_eaten – Total pellet eaten in g from the start of the experiment.</li>
<li>Eaten_wk – Amount of pellet consumed that week (gweek-1).</li>
<li>P_tot - Total protein eaten in g from the start of the experiment.</li>
<li>P2_total – P_tot2 squared (i.e. the total protein eaten squared).</li>
<li>P_wk – Amount of protein consumed that week (gweek-1).</li>
<li>P2_wk – P_wk2 squared (i.e. the weekly protein intake squared).</li>
<li>L_tot - Total lipid eaten in g from the start of the experiment.</li>
<li>L2_total – L_tot2 squared (i.e. the total lipid eaten squared).</li>
<li>L_wk – Amount of lipid consumed that week (gweek-1).</li>
<li>L2_wk – L_wk2 squared (i.e. the weekly lipid intake squared).</li>
<li>Weight – Weight of fish from last weighing (g).</li>
<li>Week_F – Experimental week.</li>
<li>Status – Survival status (0= alive, 1 = Dead).</li>
<li>T_group – Time period of the experiment (see Fig. S1).</li>
<li>Initial_weight – Initial weight of individual at the start of the experiment.</li>
<li>ZP – P_wk z transformed (mean of 0 and standard deviation of 1).</li>
<li>ZP2 – P2_wk z transformed (mean of 0 and standard deviation of 1).</li>
<li>ZL – L_wk z transformed (mean of 0 and standard deviation of 1).</li>
<li>ZL2 – L2_wk z transformed (mean of 0 and standard deviation of 1).</li>
</ul>
</div>
<div id="moatt-et-al-data-s5-courtship-data" class="section level2">
<h2><span class="header-section-number">7.11</span> Moatt et al Data S5 – Courtship Data</h2>
<ul>
<li>FID – Unique ID for each individual.</li>
<li>Family – Unique code for family group (i.e. clutch of origin). Each clutch produced from a unique sire and dam.</li>
<li>Shelf_stack – Unique code for the stack and shelf of fish home tank.</li>
<li>Diet – Diet Treatment (Diet P:L: 1 = 10.2:1, 2 = 4.6:1, 3 = 2.5:1, 4 = 8.5:1, 5 = 1.6:1).</li>
<li>Level – Provisioning level, values represent percentages of monthly ad libitum monitoring.</li>
<li>Size – Size classification of individual (L = large, S = Small).</li>
<li>Trial – Number of trials that individual experienced.</li>
<li>Days_breeding – Length of breeding season for that individual.</li>
<li>P_day – Average protein intake per day during the breeding season (gday-1).</li>
<li>P2_day – P_day2 squared (i.e. daily protein intake squared).</li>
<li>L_day - Average lipid intake per day during the breeding season (gday-1).</li>
<li>L2_day – L_day2 squared (i.e. daily lipid intake squared).</li>
<li>Mean_react – Mean reaction time across all trials for that individual.</li>
<li>Total_ZZ – Total number of zigzags across all trials.</li>
<li>Total_leads – Total number of leads across all trials.</li>
<li>Total_court – Total time courting across all trials.</li>
</ul>
</div>
<div id="moatt-et-al-data-s6-eggs-data" class="section level2">
<h2><span class="header-section-number">7.12</span> Moatt et al Data S6 – Eggs Data</h2>
<ul>
<li>FID – Unique ID for each individual.</li>
<li>Family – Unique code for family group (i.e. clutch of origin). Each clutch produced from a unique sire and dam.</li>
<li>Shelf_stack – Unique code for the stack and shelf of fish home tank.</li>
<li>Diet – Diet Treatment (Diet P:L: 1 = 10.2:1, 2 = 4.6:1, 3 = 2.5:1, 4 = 8.5:1, 5 = 1.6:1).</li>
<li>Level – Provisioning level, values represent percentages of monthly ad libitum monitoring.</li>
<li>Size – Size classification of individual (L = large, S = Small).</li>
<li>P_day – Average protein intake per day during the breeding season (gday-1).</li>
<li>P2_day – P_day2 squared (i.e. daily protein intake squared).</li>
<li>L_day - Average lipid intake per day during the breeding season (gday-1).</li>
<li>L2_day – L_day2 squared (i.e. daily lipid intake squared).</li>
<li>Days_breeding – Length of breeding season for that individual.</li>
<li>Number_clutches – Number of clutches produced by that individual.</li>
<li>Mean_number – Mean number of eggs per clutch.</li>
<li>Total_egg – Total number of eggs produced.</li>
</ul>
</div>
<div id="moatt-et-al-data-s15-length-weight-and-condition-index-data" class="section level2">
<h2><span class="header-section-number">7.13</span> Moatt et al Data S15 – Length, Weight and Condition Index Data</h2>
<ul>
<li>FID – Unique ID for each individual.</li>
<li>StackShelf – Unique code for the stack and shelf of fish home tank.</li>
<li>Sex – Sex of individual (M = male, F = female).</li>
<li>Diet – Diet Treatment (Diet P:L: 1 = 10.2:1, 2 = 4.6:1, 3 = 2.5:1, 4 = 8.5:1, 5 = 1.6:1).</li>
<li>Level – Provisioning level, values represent percentages of monthly ad libitum monitoring.</li>
<li>Size – Size classification of individual (L = large, S = Small).</li>
<li>Batch – Weighing batch. NB Batch 1 is prior to diet treatments therefore has no corresponding values for protein and lipid intake.</li>
<li>P_day – Average protein intake per day during the breeding season (gday-1).</li>
<li>P2_day – P_day2 squared (i.e. daily protein intake squared).</li>
<li>L_day - Average lipid intake per day during the breeding season (gday-1).</li>
<li>L2_day – L_day2 squared (i.e. daily lipid intake squared).</li>
<li>ZP – Daily protein intake z transformed (mean of 0 and standard deviation of 1), calculated for each sex independently.</li>
<li>ZP2 – Daily protein intake squared, z transformed (mean of 0 and standard deviation of 1), calculated for each sex independently.</li>
<li>ZL – Daily lipid intake z transformed (mean of 0 and standard deviation of 1), calculated for each sex independently.</li>
<li>ZL2 – Daily lipid intake squared, z transformed (mean of 0 and standard deviation of 1), calculated for each sex independently.</li>
<li>Ln – Length of individual in mm.</li>
<li>Wt – Weight of individual in g.</li>
<li>CI – Condition Index for each individual.</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="WFD-dietdiv-effect.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelwf-scripts.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown/edit/master/inst/examples/06-wfdemo-fishdiet-restr.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["insights_website.pdf", "insights_website.epub", "insights_website.mobi"],
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
