<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Are diets more diverse in more democratic countries? | Companion Website — Insights from Data with R</title>
  <meta name="description" content="Welcome!" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Are diets more diverse in more democratic countries? | Companion Website — Insights from Data with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Welcome!" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Are diets more diverse in more democratic countries? | Companion Website — Insights from Data with R" />
  
  <meta name="twitter:description" content="Welcome!" />
  

<meta name="author" content="Petchey, Beckerman, Cooper, Childs" />


<meta name="date" content="2021-04-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="WFD-dietdiv-effect.html"/>
<link rel="next" href="WFD-diet-restrict.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Insights from Data Website</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="insights-workflow.html"><a href="insights-workflow.html"><i class="fa fa-check"></i><b>2</b> Insights Workflow</a>
<ul>
<li class="chapter" data-level="2.1" data-path="insights-workflow.html"><a href="insights-workflow.html#preparing-the-data"><i class="fa fa-check"></i><b>2.1</b> Preparing the data</a></li>
<li class="chapter" data-level="2.2" data-path="insights-workflow.html"><a href="insights-workflow.html#prepare-your-computer-r-and-rstudio"><i class="fa fa-check"></i><b>2.2</b> Prepare your computer, R, and RStudio</a></li>
<li class="chapter" data-level="2.3" data-path="insights-workflow.html"><a href="insights-workflow.html#read-the-data-into-r"><i class="fa fa-check"></i><b>2.3</b> Read the data into R</a></li>
<li class="chapter" data-level="2.4" data-path="insights-workflow.html"><a href="insights-workflow.html#tidy-the-data"><i class="fa fa-check"></i><b>2.4</b> Tidy the data</a></li>
<li class="chapter" data-level="2.5" data-path="insights-workflow.html"><a href="insights-workflow.html#clean-the-data."><i class="fa fa-check"></i><b>2.5</b> Clean the data.</a></li>
<li class="chapter" data-level="2.6" data-path="insights-workflow.html"><a href="insights-workflow.html#initial-insights"><i class="fa fa-check"></i><b>2.6</b> Initial insights</a></li>
<li class="chapter" data-level="2.7" data-path="insights-workflow.html"><a href="insights-workflow.html#insights-about-question-posed"><i class="fa fa-check"></i><b>2.7</b> Insights about question posed</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="questions-exercises.html"><a href="questions-exercises.html"><i class="fa fa-check"></i><b>3</b> Questions and exercises</a>
<ul>
<li class="chapter" data-level="3.1" data-path="questions-exercises.html"><a href="questions-exercises.html#preface"><i class="fa fa-check"></i><b>3.1</b> Preface</a></li>
<li class="chapter" data-level="3.2" data-path="questions-exercises.html"><a href="questions-exercises.html#chapter-1-introduction"><i class="fa fa-check"></i><b>3.2</b> Chapter 1 (Introduction)</a></li>
<li class="chapter" data-level="3.3" data-path="questions-exercises.html"><a href="questions-exercises.html#chapter-2-getting-acquainted"><i class="fa fa-check"></i><b>3.3</b> Chapter 2 (Getting Acquainted)</a></li>
<li class="chapter" data-level="3.4" data-path="questions-exercises.html"><a href="questions-exercises.html#chapter-3-workflow-demonstrationpart-1"><i class="fa fa-check"></i><b>3.4</b> Chapter 3 (Workflow Demonstration–Part 1)</a></li>
<li class="chapter" data-level="3.5" data-path="questions-exercises.html"><a href="questions-exercises.html#chapter-4-workflow-demonstrationpart-2"><i class="fa fa-check"></i><b>3.5</b> Chapter 4 (Workflow Demonstration–Part 2)</a></li>
<li class="chapter" data-level="3.6" data-path="questions-exercises.html"><a href="questions-exercises.html#chapter-5-dealing-with-data-1digging-into-dplyr"><i class="fa fa-check"></i><b>3.6</b> Chapter 5 (Dealing with data 1—Digging into dplyr)</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="questions-exercises.html"><a href="questions-exercises.html#general-questions-and-exercises"><i class="fa fa-check"></i><b>3.6.1</b> General questions and exercises</a></li>
<li class="chapter" data-level="3.6.2" data-path="questions-exercises.html"><a href="questions-exercises.html#bat-diet-workflow-questions-and-exercises"><i class="fa fa-check"></i><b>3.6.2</b> Bat diet workflow questions and exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="questions-exercises.html"><a href="questions-exercises.html#chapter-6-dealing-with-data-2expanding-your-toolkit"><i class="fa fa-check"></i><b>3.7</b> Chapter 6 (Dealing with data 2—Expanding your toolkit)</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="questions-exercises.html"><a href="questions-exercises.html#general-questions-and-exercises-1"><i class="fa fa-check"></i><b>3.7.1</b> General questions and exercises</a></li>
<li class="chapter" data-level="3.7.2" data-path="questions-exercises.html"><a href="questions-exercises.html#bat-diet-workflow-questions-and-exercises-1"><i class="fa fa-check"></i><b>3.7.2</b> Bat diet workflow questions and exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="questions-exercises.html"><a href="questions-exercises.html#chapter-7-getting-to-grips-with-ggplot2"><i class="fa fa-check"></i><b>3.8</b> Chapter 7 (Getting to grips with ggplot2)</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="questions-exercises.html"><a href="questions-exercises.html#general-questions-and-exercises-2"><i class="fa fa-check"></i><b>3.8.1</b> General questions and exercises</a></li>
<li class="chapter" data-level="3.8.2" data-path="questions-exercises.html"><a href="questions-exercises.html#bat-diet-workflow-questions-and-exercises-2"><i class="fa fa-check"></i><b>3.8.2</b> Bat diet workflow questions and exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="questions-exercises.html"><a href="questions-exercises.html#chapter-8-making-deeper-insights-part-1---working-with-single-variables"><i class="fa fa-check"></i><b>3.9</b> Chapter 8 (Making Deeper Insights: Part 1 - working with single variables)</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="questions-exercises.html"><a href="questions-exercises.html#general-questions-and-exercises-3"><i class="fa fa-check"></i><b>3.9.1</b> General questions and exercises</a></li>
<li class="chapter" data-level="3.9.2" data-path="questions-exercises.html"><a href="questions-exercises.html#workflow-demonstration-questions-and-exercises"><i class="fa fa-check"></i><b>3.9.2</b> Workflow demonstration questions and exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="questions-exercises.html"><a href="questions-exercises.html#chapter-9-making-deeper-insights-part-2-relationships-among-many-variables"><i class="fa fa-check"></i><b>3.10</b> Chapter 9 (Making Deeper Insights Part 2: Relationships among (many) variables)</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="questions-exercises.html"><a href="questions-exercises.html#workflow-questions-and-exercises"><i class="fa fa-check"></i><b>3.10.1</b> Workflow questions and exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="questions-exercises.html"><a href="questions-exercises.html#chapter-10-looking-back-and-looking-forward"><i class="fa fa-check"></i><b>3.11</b> Chapter 10 (Looking back and looking forward)</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="more-R.html"><a href="more-R.html"><i class="fa fa-check"></i><b>4</b> More R</a>
<ul>
<li class="chapter" data-level="4.1" data-path="more-R.html"><a href="more-R.html#rstudio-project-setup"><i class="fa fa-check"></i><b>4.1</b> RStudio Project setup</a></li>
<li class="chapter" data-level="4.2" data-path="more-R.html"><a href="more-R.html#baseclassic-and-tidyverse-comparison"><i class="fa fa-check"></i><b>4.2</b> Base/classic and tidyverse comparison</a></li>
<li class="chapter" data-level="4.3" data-path="more-R.html"><a href="more-R.html#multiple-graphs-in-one-figure"><i class="fa fa-check"></i><b>4.3</b> Multiple graphs in one figure</a></li>
<li class="chapter" data-level="4.4" data-path="more-R.html"><a href="more-R.html#factors"><i class="fa fa-check"></i><b>4.4</b> Factors</a></li>
<li class="chapter" data-level="4.5" data-path="more-R.html"><a href="more-R.html#other-pipes"><i class="fa fa-check"></i><b>4.5</b> Other pipes</a></li>
<li class="chapter" data-level="4.6" data-path="more-R.html"><a href="more-R.html#simulating-data"><i class="fa fa-check"></i><b>4.6</b> Simulating data</a></li>
<li class="chapter" data-level="4.7" data-path="more-R.html"><a href="more-R.html#avoiding-loops"><i class="fa fa-check"></i><b>4.7</b> Avoiding “loops”</a></li>
<li class="chapter" data-level="4.8" data-path="more-R.html"><a href="more-R.html#syntax-highlighting"><i class="fa fa-check"></i><b>4.8</b> Syntax highlighting</a></li>
<li class="chapter" data-level="4.9" data-path="more-R.html"><a href="more-R.html#summarise-more-than-one-variable"><i class="fa fa-check"></i><b>4.9</b> Summarise more than one variable</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html"><i class="fa fa-check"></i><b>5</b> Data analysis concepts</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#distributions"><i class="fa fa-check"></i><b>5.1</b> Distributions</a></li>
<li class="chapter" data-level="5.2" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#interactions-and-complexity"><i class="fa fa-check"></i><b>5.2</b> Interactions and complexity</a></li>
<li class="chapter" data-level="5.3" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#lurking-variables"><i class="fa fa-check"></i><b>5.3</b> Lurking variables</a></li>
<li class="chapter" data-level="5.4" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#power-of-data-to-give-insights"><i class="fa fa-check"></i><b>5.4</b> Power of data to give insights</a></li>
<li class="chapter" data-level="5.5" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#effect-sizes"><i class="fa fa-check"></i><b>5.5</b> Effect sizes</a></li>
<li class="chapter" data-level="5.6" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#ordination"><i class="fa fa-check"></i><b>5.6</b> Ordination</a></li>
<li class="chapter" data-level="5.7" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#influence-outliers"><i class="fa fa-check"></i><b>5.7</b> Influence and outliers</a></li>
<li class="chapter" data-level="5.8" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#transformations"><i class="fa fa-check"></i><b>5.8</b> Transformations</a></li>
<li class="chapter" data-level="5.9" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#non-independence"><i class="fa fa-check"></i><b>5.9</b> Non-independence</a></li>
<li class="chapter" data-level="5.10" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#missing-values-nas"><i class="fa fa-check"></i><b>5.10</b> Missing values (NAs)</a></li>
<li class="chapter" data-level="5.11" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#skewness"><i class="fa fa-check"></i><b>5.11</b> Skewness</a></li>
<li class="chapter" data-level="5.12" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#interoperability"><i class="fa fa-check"></i><b>5.12</b> Interoperability / standardising terms</a></li>
<li class="chapter" data-level="5.13" data-path="data-analysis-concepts.html"><a href="data-analysis-concepts.html#comparing-descriptive-statistics"><i class="fa fa-check"></i><b>5.13</b> Comparing descriptive statistics</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html"><i class="fa fa-check"></i><b>6</b> How does dietary diversity affect populations?</a>
<ul>
<li class="chapter" data-level="6.1" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#about-this-workflow-demonstration"><i class="fa fa-check"></i><b>6.1</b> About this Workflow Demonstration</a></li>
<li class="chapter" data-level="6.2" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#going-to-the-next-level"><i class="fa fa-check"></i><b>6.2</b> Going to the next level</a></li>
<li class="chapter" data-level="6.3" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#introduction-to-the-study-and-data"><i class="fa fa-check"></i><b>6.3</b> Introduction to the study and data</a></li>
<li class="chapter" data-level="6.4" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#what-type-of-response-variable"><i class="fa fa-check"></i><b>6.4</b> What type of response variable?</a></li>
<li class="chapter" data-level="6.5" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#a-little-preparation"><i class="fa fa-check"></i><b>6.5</b> A little preparation</a></li>
<li class="chapter" data-level="6.6" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#acquire-the-dataset"><i class="fa fa-check"></i><b>6.6</b> Acquire the dataset</a></li>
<li class="chapter" data-level="6.7" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#import-the-dataset"><i class="fa fa-check"></i><b>6.7</b> Import the dataset</a></li>
<li class="chapter" data-level="6.8" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#checking-the-import-worked-correctly"><i class="fa fa-check"></i><b>6.8</b> Checking the import worked correctly</a></li>
<li class="chapter" data-level="6.9" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#cleaning-and-tidying"><i class="fa fa-check"></i><b>6.9</b> Cleaning and tidying</a>
<ul>
<li class="chapter" data-level="6.9.1" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#recode-some-names"><i class="fa fa-check"></i><b>6.9.1</b> Recode some names</a></li>
<li class="chapter" data-level="6.9.2" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#factors-predstab"><i class="fa fa-check"></i><b>6.9.2</b> Make the <code>prey_composition</code> variable a factor with specific order</a></li>
<li class="chapter" data-level="6.9.3" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#fix-those-variable-names"><i class="fa fa-check"></i><b>6.9.3</b> Fix those variable names</a></li>
<li class="chapter" data-level="6.9.4" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#calculate-an-important-variable"><i class="fa fa-check"></i><b>6.9.4</b> Calculate an important variable</a></li>
<li class="chapter" data-level="6.9.5" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#remove-nas"><i class="fa fa-check"></i><b>6.9.5</b> Remove NAs</a></li>
<li class="chapter" data-level="6.9.6" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#checking-some-specifics"><i class="fa fa-check"></i><b>6.9.6</b> Checking some specifics</a></li>
<li class="chapter" data-level="6.9.7" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#a-closer-look-at-the-data"><i class="fa fa-check"></i><b>6.9.7</b> A closer look at the data</a></li>
<li class="chapter" data-level="6.9.8" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#calculate-the-three-response-variables"><i class="fa fa-check"></i><b>6.9.8</b> Calculate the three response variables</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#shapes"><i class="fa fa-check"></i><b>6.10</b> Shapes</a></li>
<li class="chapter" data-level="6.11" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#relationships"><i class="fa fa-check"></i><b>6.11</b> Relationships</a>
<ul>
<li class="chapter" data-level="6.11.1" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#maximum-predator-density"><i class="fa fa-check"></i><b>6.11.1</b> Maximum predator density</a></li>
<li class="chapter" data-level="6.11.2" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#predator-population-variability-cv"><i class="fa fa-check"></i><b>6.11.2</b> Predator population variability (CV)</a></li>
<li class="chapter" data-level="6.11.3" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#predator-persistence-time"><i class="fa fa-check"></i><b>6.11.3</b> Predator persistence time</a></li>
<li class="chapter" data-level="6.11.4" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#all-three-at-once"><i class="fa fa-check"></i><b>6.11.4</b> All three at once</a></li>
</ul></li>
<li class="chapter" data-level="6.12" data-path="WFD-dietdiv-effect.html"><a href="WFD-dietdiv-effect.html#wrapping-up"><i class="fa fa-check"></i><b>6.12</b> Wrapping up</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html"><i class="fa fa-check"></i><b>7</b> Are diets more diverse in more democratic countries?</a>
<ul>
<li class="chapter" data-level="7.1" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#about-this-workflow-demonstration-1"><i class="fa fa-check"></i><b>7.1</b> About this Workflow Demonstration</a></li>
<li class="chapter" data-level="7.2" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#introduction-to-the-study-and-data-1"><i class="fa fa-check"></i><b>7.2</b> Introduction to the study and data</a></li>
<li class="chapter" data-level="7.3" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#understanding-the-data"><i class="fa fa-check"></i><b>7.3</b> Understanding the data</a></li>
<li class="chapter" data-level="7.4" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#a-little-preparation-1"><i class="fa fa-check"></i><b>7.4</b> A little preparation</a></li>
<li class="chapter" data-level="7.5" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#polity-data-origins-acquire-import-clean-tidy-nas-duplicates"><i class="fa fa-check"></i><b>7.5</b> Polity data: origins, acquire, import, clean, tidy, NAs, duplicates</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#data-origins-and-acquisition"><i class="fa fa-check"></i><b>7.5.1</b> Data origins and acquisition</a></li>
<li class="chapter" data-level="7.5.2" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#data-import"><i class="fa fa-check"></i><b>7.5.2</b> Data import</a></li>
<li class="chapter" data-level="7.5.3" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#tidy-and-clean"><i class="fa fa-check"></i><b>7.5.3</b> Tidy and clean</a></li>
<li class="chapter" data-level="7.5.4" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#deal-with-nas"><i class="fa fa-check"></i><b>7.5.4</b> Deal with NAs</a></li>
<li class="chapter" data-level="7.5.5" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#check-for-innapropriate-duplicate-observations"><i class="fa fa-check"></i><b>7.5.5</b> Check for innapropriate duplicate observations</a></li>
<li class="chapter" data-level="7.5.6" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#check-ranges-of-numeric-variables"><i class="fa fa-check"></i><b>7.5.6</b> Check ranges of numeric variables</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#first-insights-from-the-polity-data"><i class="fa fa-check"></i><b>7.6</b> First insights from the polity data</a></li>
<li class="chapter" data-level="7.7" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#acquire-import-check-the-fao-food-balance-sheet-data"><i class="fa fa-check"></i><b>7.7</b> Acquire, import, check the FAO Food balance sheet data</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#tidying-FAO"><i class="fa fa-check"></i><b>7.7.1</b> Tidy the FAO data</a></li>
<li class="chapter" data-level="7.7.2" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#clean-the-fao-data"><i class="fa fa-check"></i><b>7.7.2</b> Clean the FAO data</a></li>
<li class="chapter" data-level="7.7.3" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#check-for-innapropriate-duplicate-observations-1"><i class="fa fa-check"></i><b>7.7.3</b> Check for innapropriate duplicate observations</a></li>
<li class="chapter" data-level="7.7.4" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#checking-something-else"><i class="fa fa-check"></i><b>7.7.4</b> Checking something else…</a></li>
<li class="chapter" data-level="7.7.5" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#missing-values"><i class="fa fa-check"></i><b>7.7.5</b> Missing values</a></li>
<li class="chapter" data-level="7.7.6" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#more-cleaning"><i class="fa fa-check"></i><b>7.7.6</b> More cleaning</a></li>
<li class="chapter" data-level="7.7.7" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#calculating-our-response-variables"><i class="fa fa-check"></i><b>7.7.7</b> Calculating our response variables</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#merge-the-two-datasets-aaaaaargh"><i class="fa fa-check"></i><b>7.8</b> Merge the two datasets (aaaaaargh!!)</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#polity-standardisation"><i class="fa fa-check"></i><b>7.8.1</b> Polity standardisation</a></li>
<li class="chapter" data-level="7.8.2" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#the-final-merge"><i class="fa fa-check"></i><b>7.8.2</b> The final merge</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#tidying-up"><i class="fa fa-check"></i><b>7.9</b> Tidying up</a></li>
<li class="chapter" data-level="7.10" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#shapes-1"><i class="fa fa-check"></i><b>7.10</b> Shapes</a></li>
<li class="chapter" data-level="7.11" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#relationships-1"><i class="fa fa-check"></i><b>7.11</b> Relationships</a></li>
<li class="chapter" data-level="7.12" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#wrapping-up-1"><i class="fa fa-check"></i><b>7.12</b> Wrapping up</a></li>
<li class="chapter" data-level="7.13" data-path="WFD-food-pol.html"><a href="WFD-food-pol.html#and-a-challenge-for-you"><i class="fa fa-check"></i><b>7.13</b> And a challenge for you…</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html"><i class="fa fa-check"></i><b>8</b> What are the effects of dietary restriction?</a>
<ul>
<li class="chapter" data-level="8.1" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#about-this-workflow-demonstration-2"><i class="fa fa-check"></i><b>8.1</b> About this Workflow Demonstration</a></li>
<li class="chapter" data-level="8.2" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#introduction-1"><i class="fa fa-check"></i><b>8.2</b> Introduction</a></li>
<li class="chapter" data-level="8.3" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#the-question"><i class="fa fa-check"></i><b>8.3</b> The question</a></li>
<li class="chapter" data-level="8.4" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#before-working-in-r"><i class="fa fa-check"></i><b>8.4</b> Before working in R</a></li>
<li class="chapter" data-level="8.5" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#what-was-the-experimental-design"><i class="fa fa-check"></i><b>8.5</b> What was the experimental design?</a></li>
<li class="chapter" data-level="8.6" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#what-are-the-features-of-the-data"><i class="fa fa-check"></i><b>8.6</b> What are the features of the data?</a></li>
<li class="chapter" data-level="8.7" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#acquire-and-import-the-necessary-datafiles."><i class="fa fa-check"></i><b>8.7</b> Acquire and import the necessary datafiles.</a></li>
<li class="chapter" data-level="8.8" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#explore-and-understand-the-datafiles"><i class="fa fa-check"></i><b>8.8</b> Explore and understand the datafiles</a></li>
<li class="chapter" data-level="8.9" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#check-the-data-import"><i class="fa fa-check"></i><b>8.9</b> Check the data import</a></li>
<li class="chapter" data-level="8.10" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#make-more-informative-variable-names-and-discard-variables-not-obviously-of-use"><i class="fa fa-check"></i><b>8.10</b> Make more informative variable names (and discard variables not obviously of use):</a></li>
<li class="chapter" data-level="8.11" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#replace-codes-with-informative-words"><i class="fa fa-check"></i><b>8.11</b> Replace codes with informative words</a></li>
<li class="chapter" data-level="8.12" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#checking-for-duplicates"><i class="fa fa-check"></i><b>8.12</b> Checking for duplicates</a></li>
<li class="chapter" data-level="8.13" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#nas-variable-entries-e.g.-levels-of-characters-ranges-of-numerics-numbers-of-things"><i class="fa fa-check"></i><b>8.13</b> NAs, variable entries, e.g. levels of characters, ranges of numerics, numbers of “things”</a></li>
<li class="chapter" data-level="8.14" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#independence"><i class="fa fa-check"></i><b>8.14</b> Independence</a></li>
<li class="chapter" data-level="8.15" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#balance-in-experimental-design"><i class="fa fa-check"></i><b>8.15</b> Balance in experimental design</a></li>
<li class="chapter" data-level="8.16" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#calculate-response-variables-if-required"><i class="fa fa-check"></i><b>8.16</b> Calculate response variable(s) (if required)</a></li>
<li class="chapter" data-level="8.17" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#merge-all-datasets-together-and-check-for-correct-number-of-rows"><i class="fa fa-check"></i><b>8.17</b> Merge all datasets together and check for correct number of rows</a></li>
<li class="chapter" data-level="8.18" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#something-a-bit-weird"><i class="fa fa-check"></i><b>8.18</b> Something a bit weird…</a></li>
<li class="chapter" data-level="8.19" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#import-the-updated-versions-of-the-datasets."><i class="fa fa-check"></i><b>8.19</b> Import the updated versions of the datasets.</a></li>
<li class="chapter" data-level="8.20" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#inspect-shapes-distributions"><i class="fa fa-check"></i><b>8.20</b> Inspect shapes (distributions)</a></li>
<li class="chapter" data-level="8.21" data-path="WFD-diet-restrict.html"><a href="WFD-diet-restrict.html#inspect-relationships"><i class="fa fa-check"></i><b>8.21</b> Inspect relationships</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html"><i class="fa fa-check"></i><b>9</b> Solutions: What are the effects of dietary restriction?</a>
<ul>
<li class="chapter" data-level="9.1" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html#about-these-solutions"><i class="fa fa-check"></i><b>9.1</b> About these solutions</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html#nas-variable-entries-e.g.-levels-of-characters-ranges-of-numerics-numbers-of-things-1"><i class="fa fa-check"></i><b>9.1.1</b> NAs, variable entries, e.g. levels of characters, ranges of numerics, numbers of “things”*</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html#independence-1"><i class="fa fa-check"></i><b>9.2</b> Independence</a></li>
<li class="chapter" data-level="9.3" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html#balance-in-experimental-design-1"><i class="fa fa-check"></i><b>9.3</b> Balance in experimental design</a></li>
<li class="chapter" data-level="9.4" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html#do-regression"><i class="fa fa-check"></i><b>9.4</b> Calculate response variable(s) (if required)</a></li>
<li class="chapter" data-level="9.5" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html#inspect-relationships-1"><i class="fa fa-check"></i><b>9.5</b> Inspect relationships</a></li>
<li class="chapter" data-level="9.6" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html#below-are-lists-of-variables-in-each-of-the-four-used-datasets."><i class="fa fa-check"></i><b>9.6</b> Below are lists of variables in each of the four used datasets.</a></li>
<li class="chapter" data-level="9.7" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html#moatt-et-al-data-s1-mortality-data"><i class="fa fa-check"></i><b>9.7</b> Moatt et al Data S1 – Mortality Data</a></li>
<li class="chapter" data-level="9.8" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html#moatt-et-al-data-s5-courtship-data"><i class="fa fa-check"></i><b>9.8</b> Moatt et al Data S5 – Courtship Data</a></li>
<li class="chapter" data-level="9.9" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html#moatt-et-al-data-s6-eggs-data"><i class="fa fa-check"></i><b>9.9</b> Moatt et al Data S6 – Eggs Data</a></li>
<li class="chapter" data-level="9.10" data-path="WFD-diet-restrict-solutions.html"><a href="WFD-diet-restrict-solutions.html#moatt-et-al-data-s15-length-weight-and-condition-index-data"><i class="fa fa-check"></i><b>9.10</b> Moatt et al Data S15 – Length, Weight and Condition Index Data</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="modelwf-scripts.html"><a href="modelwf-scripts.html"><i class="fa fa-check"></i><b>10</b> Workflow demonstration R scripts</a></li>
<li class="chapter" data-level="11" data-path="live-data-demo.html"><a href="live-data-demo.html"><i class="fa fa-check"></i><b>11</b> Live data analysis demonstration</a>
<ul>
<li class="chapter" data-level="11.1" data-path="live-data-demo.html"><a href="live-data-demo.html#introduction-for-intructors"><i class="fa fa-check"></i><b>11.1</b> Introduction for intructors</a></li>
<li class="chapter" data-level="" data-path="live-data-demo.html"><a href="live-data-demo.html#introduction-2"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="live-data-demo.html"><a href="live-data-demo.html#meta-task"><i class="fa fa-check"></i><b>11.2</b> Meta-task</a></li>
<li class="chapter" data-level="11.3" data-path="live-data-demo.html"><a href="live-data-demo.html#the-question-1"><i class="fa fa-check"></i><b>11.3</b> The question</a></li>
<li class="chapter" data-level="11.4" data-path="live-data-demo.html"><a href="live-data-demo.html#expectation"><i class="fa fa-check"></i><b>11.4</b> Expectation</a></li>
<li class="chapter" data-level="11.5" data-path="live-data-demo.html"><a href="live-data-demo.html#how-are-we-going-to-present-the-results"><i class="fa fa-check"></i><b>11.5</b> How are we going to present the results?</a></li>
<li class="chapter" data-level="11.6" data-path="live-data-demo.html"><a href="live-data-demo.html#what-statistical-test-will-we-use"><i class="fa fa-check"></i><b>11.6</b> What statistical test will we use?</a></li>
<li class="chapter" data-level="11.7" data-path="live-data-demo.html"><a href="live-data-demo.html#selection-of-subjects"><i class="fa fa-check"></i><b>11.7</b> Selection of subjects</a></li>
<li class="chapter" data-level="11.8" data-path="live-data-demo.html"><a href="live-data-demo.html#ethical-clearance-and-considerations"><i class="fa fa-check"></i><b>11.8</b> Ethical clearance and considerations</a></li>
<li class="chapter" data-level="11.9" data-path="live-data-demo.html"><a href="live-data-demo.html#data-collection"><i class="fa fa-check"></i><b>11.9</b> Data collection</a></li>
<li class="chapter" data-level="11.10" data-path="live-data-demo.html"><a href="live-data-demo.html#look-at-the-data"><i class="fa fa-check"></i><b>11.10</b> Look at the data!</a></li>
<li class="chapter" data-level="11.11" data-path="live-data-demo.html"><a href="live-data-demo.html#lets-get-the-data-into-our-data-analysis-software-of-choice-r-via-rstudio"><i class="fa fa-check"></i><b>11.11</b> Lets get the data into our data analysis software of choice (R, via RStudio)</a></li>
<li class="chapter" data-level="11.12" data-path="live-data-demo.html"><a href="live-data-demo.html#now-we-need-to-do-some-data-wrangling-cleaning-and-tidying"><i class="fa fa-check"></i><b>11.12</b> Now we need to do some data wrangling (cleaning and tidying)</a>
<ul>
<li class="chapter" data-level="11.12.1" data-path="live-data-demo.html"><a href="live-data-demo.html#clean-up-the-column-variable-names"><i class="fa fa-check"></i><b>11.12.1</b> Clean up the column / variable names:</a></li>
<li class="chapter" data-level="11.12.2" data-path="live-data-demo.html"><a href="live-data-demo.html#check-the-variable-types-are-correct."><i class="fa fa-check"></i><b>11.12.2</b> Check the variable types are correct.</a></li>
<li class="chapter" data-level="11.12.3" data-path="live-data-demo.html"><a href="live-data-demo.html#correct-or-exclude-problematic-data"><i class="fa fa-check"></i><b>11.12.3</b> Correct or exclude problematic data</a></li>
<li class="chapter" data-level="11.12.4" data-path="live-data-demo.html"><a href="live-data-demo.html#check-numbers-of-data-points-in-each-sex"><i class="fa fa-check"></i><b>11.12.4</b> Check numbers of data points in each sex</a></li>
<li class="chapter" data-level="11.12.5" data-path="live-data-demo.html"><a href="live-data-demo.html#check-the-number-of-observations"><i class="fa fa-check"></i><b>11.12.5</b> Check the number of observations</a></li>
</ul></li>
<li class="chapter" data-level="11.13" data-path="live-data-demo.html"><a href="live-data-demo.html#visualise-the-data"><i class="fa fa-check"></i><b>11.13</b> Visualise the data</a></li>
<li class="chapter" data-level="11.14" data-path="live-data-demo.html"><a href="live-data-demo.html#get-the-means"><i class="fa fa-check"></i><b>11.14</b> Get the means</a></li>
<li class="chapter" data-level="11.15" data-path="live-data-demo.html"><a href="live-data-demo.html#effect-size-and-practical-importance"><i class="fa fa-check"></i><b>11.15</b> Effect size and practical importance?</a></li>
<li class="chapter" data-level="11.16" data-path="live-data-demo.html"><a href="live-data-demo.html#assess-assumptions"><i class="fa fa-check"></i><b>11.16</b> Assess assumptions</a>
<ul>
<li class="chapter" data-level="11.16.1" data-path="live-data-demo.html"><a href="live-data-demo.html#independence-2"><i class="fa fa-check"></i><b>11.16.1</b> Independence</a></li>
<li class="chapter" data-level="11.16.2" data-path="live-data-demo.html"><a href="live-data-demo.html#normally-distributed-residuals"><i class="fa fa-check"></i><b>11.16.2</b> Normally distributed residuals</a></li>
<li class="chapter" data-level="11.16.3" data-path="live-data-demo.html"><a href="live-data-demo.html#equal-variance"><i class="fa fa-check"></i><b>11.16.3</b> Equal variance</a></li>
</ul></li>
<li class="chapter" data-level="11.17" data-path="live-data-demo.html"><a href="live-data-demo.html#do-the-statistical-test"><i class="fa fa-check"></i><b>11.17</b> Do the statistical test</a></li>
<li class="chapter" data-level="11.18" data-path="live-data-demo.html"><a href="live-data-demo.html#critical-thinking"><i class="fa fa-check"></i><b>11.18</b> Critical thinking</a></li>
<li class="chapter" data-level="11.19" data-path="live-data-demo.html"><a href="live-data-demo.html#report-and-communicate-the-results"><i class="fa fa-check"></i><b>11.19</b> Report and communicate the results</a>
<ul>
<li class="chapter" data-level="11.19.1" data-path="live-data-demo.html"><a href="live-data-demo.html#the-results-as-a-sentence"><i class="fa fa-check"></i><b>11.19.1</b> The results as a sentence</a></li>
<li class="chapter" data-level="11.19.2" data-path="live-data-demo.html"><a href="live-data-demo.html#the-results-graphically"><i class="fa fa-check"></i><b>11.19.2</b> The results graphically</a></li>
<li class="chapter" data-level="11.19.3" data-path="live-data-demo.html"><a href="live-data-demo.html#do-not-use-a-table"><i class="fa fa-check"></i><b>11.19.3</b> Do not use a table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="more-questions-data.html"><a href="more-questions-data.html"><i class="fa fa-check"></i><b>12</b> More datasets</a>
<ul>
<li class="chapter" data-level="12.1" data-path="more-questions-data.html"><a href="more-questions-data.html#hungry-ladybirds"><i class="fa fa-check"></i><b>12.1</b> Hungry ladybirds</a></li>
<li class="chapter" data-level="12.2" data-path="more-questions-data.html"><a href="more-questions-data.html#seal-suppers"><i class="fa fa-check"></i><b>12.2</b> Seal suppers</a></li>
<li class="chapter" data-level="12.3" data-path="more-questions-data.html"><a href="more-questions-data.html#more-bat-poop"><i class="fa fa-check"></i><b>12.3</b> More bat poop</a></li>
<li class="chapter" data-level="12.4" data-path="more-questions-data.html"><a href="more-questions-data.html#marten-isotopes"><i class="fa fa-check"></i><b>12.4</b> Marten isotopes</a></li>
<li class="chapter" data-level="12.5" data-path="more-questions-data.html"><a href="more-questions-data.html#snake-diets"><i class="fa fa-check"></i><b>12.5</b> Snake diets</a></li>
<li class="chapter" data-level="12.6" data-path="more-questions-data.html"><a href="more-questions-data.html#desert-bat-diets"><i class="fa fa-check"></i><b>12.6</b> Desert bat diets</a></li>
<li class="chapter" data-level="12.7" data-path="more-questions-data.html"><a href="more-questions-data.html#birds-eating-insects"><i class="fa fa-check"></i><b>12.7</b> Birds eating insects</a></li>
<li class="chapter" data-level="12.8" data-path="more-questions-data.html"><a href="more-questions-data.html#diets-of-predatory-fish"><i class="fa fa-check"></i><b>12.8</b> Diets of predatory fish</a></li>
<li class="chapter" data-level="12.9" data-path="more-questions-data.html"><a href="more-questions-data.html#cervical-spine-compression-and-mri-not-food-related"><i class="fa fa-check"></i><b>12.9</b> Cervical spine compression and MRI (not food related)</a></li>
<li class="chapter" data-level="12.10" data-path="more-questions-data.html"><a href="more-questions-data.html#lots-of-other-datasets-here"><i class="fa fa-check"></i><b>12.10</b> Lots of other datasets here:</a></li>
<li class="chapter" data-level="12.11" data-path="more-questions-data.html"><a href="more-questions-data.html#fish-eye-lens-diets"><i class="fa fa-check"></i><b>12.11</b> Fish eye lens diets</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="related-reading.html"><a href="related-reading.html"><i class="fa fa-check"></i><b>13</b> Related reading</a>
<ul>
<li class="chapter" data-level="13.1" data-path="related-reading.html"><a href="related-reading.html#data-science-related-reading"><i class="fa fa-check"></i><b>13.1</b> Data science related reading</a></li>
<li class="chapter" data-level="13.2" data-path="related-reading.html"><a href="related-reading.html#study-design-related-reading"><i class="fa fa-check"></i><b>13.2</b> Study design related reading</a></li>
<li class="chapter" data-level="13.3" data-path="related-reading.html"><a href="related-reading.html#web-sites-pages"><i class="fa fa-check"></i><b>13.3</b> Web sites / pages</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="answers.html"><a href="answers.html"><i class="fa fa-check"></i><b>14</b> Answers and solutions</a>
<ul>
<li class="chapter" data-level="14.1" data-path="answers.html"><a href="answers.html#preface-1"><i class="fa fa-check"></i><b>14.1</b> Preface</a></li>
<li class="chapter" data-level="14.2" data-path="answers.html"><a href="answers.html#chapter-1-introduction-1"><i class="fa fa-check"></i><b>14.2</b> Chapter 1 (Introduction)</a></li>
<li class="chapter" data-level="14.3" data-path="answers.html"><a href="answers.html#chapter-2-getting-acquainted-1"><i class="fa fa-check"></i><b>14.3</b> Chapter 2 (Getting Acquainted)</a></li>
<li class="chapter" data-level="14.4" data-path="answers.html"><a href="answers.html#chapter-3-workflow-demonstrationpart-1-1"><i class="fa fa-check"></i><b>14.4</b> Chapter 3 (Workflow Demonstration–Part 1)</a></li>
<li class="chapter" data-level="14.5" data-path="answers.html"><a href="answers.html#chapter-4-workflow-demonstrationpart-2-1"><i class="fa fa-check"></i><b>14.5</b> Chapter 4 (Workflow Demonstration–Part 2)</a></li>
<li class="chapter" data-level="14.6" data-path="answers.html"><a href="answers.html#chapter-5-dealing-with-data-1digging-into-dplyr-1"><i class="fa fa-check"></i><b>14.6</b> Chapter 5 (Dealing with data 1—Digging into dplyr)</a>
<ul>
<li class="chapter" data-level="14.6.1" data-path="answers.html"><a href="answers.html#general-questions-and-exercises-4"><i class="fa fa-check"></i><b>14.6.1</b> General questions and exercises</a></li>
<li class="chapter" data-level="14.6.2" data-path="answers.html"><a href="answers.html#bat-diet-workflow-questions-and-exercises-3"><i class="fa fa-check"></i><b>14.6.2</b> Bat diet workflow questions and exercises</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="answers.html"><a href="answers.html#chapter-6-dealing-with-data-2expanding-your-toolkit-1"><i class="fa fa-check"></i><b>14.7</b> Chapter 6 (Dealing with data 2—Expanding your toolkit)</a>
<ul>
<li class="chapter" data-level="14.7.1" data-path="answers.html"><a href="answers.html#general-questions-and-exercises-5"><i class="fa fa-check"></i><b>14.7.1</b> General questions and exercises</a></li>
<li class="chapter" data-level="14.7.2" data-path="answers.html"><a href="answers.html#bat-diet-workflow-questions-and-exercises-4"><i class="fa fa-check"></i><b>14.7.2</b> Bat diet workflow questions and exercises</a></li>
</ul></li>
<li class="chapter" data-level="14.8" data-path="answers.html"><a href="answers.html#chapter-7-getting-to-grips-with-ggplot2-1"><i class="fa fa-check"></i><b>14.8</b> Chapter 7 (Getting to grips with ggplot2)</a>
<ul>
<li class="chapter" data-level="14.8.1" data-path="answers.html"><a href="answers.html#general-questions-and-exercises-6"><i class="fa fa-check"></i><b>14.8.1</b> General questions and exercises</a></li>
<li class="chapter" data-level="14.8.2" data-path="answers.html"><a href="answers.html#bat-diet-workflow-questions-and-exercises-5"><i class="fa fa-check"></i><b>14.8.2</b> Bat diet workflow questions and exercises</a></li>
</ul></li>
<li class="chapter" data-level="14.9" data-path="answers.html"><a href="answers.html#chapter-8-making-deeper-insights-part-1---working-with-single-variables-1"><i class="fa fa-check"></i><b>14.9</b> Chapter 8 (Making Deeper Insights: Part 1 - working with single variables)</a>
<ul>
<li class="chapter" data-level="14.9.1" data-path="answers.html"><a href="answers.html#general-questions-and-exercises-7"><i class="fa fa-check"></i><b>14.9.1</b> General questions and exercises</a></li>
<li class="chapter" data-level="14.9.2" data-path="answers.html"><a href="answers.html#workflow-demonstration-questions-and-exercises-1"><i class="fa fa-check"></i><b>14.9.2</b> Workflow demonstration questions and exercises</a></li>
</ul></li>
<li class="chapter" data-level="14.10" data-path="answers.html"><a href="answers.html#chapter-9-making-deeper-insights-part-2-relationships-among-many-variables-1"><i class="fa fa-check"></i><b>14.10</b> Chapter 9 (Making Deeper Insights Part 2: Relationships among (many) variables)</a>
<ul>
<li class="chapter" data-level="14.10.1" data-path="answers.html"><a href="answers.html#general-questions-and-exercises-8"><i class="fa fa-check"></i><b>14.10.1</b> General questions and exercises</a></li>
<li class="chapter" data-level="14.10.2" data-path="answers.html"><a href="answers.html#workflow-questions-and-exercises-1"><i class="fa fa-check"></i><b>14.10.2</b> Workflow questions and exercises</a></li>
</ul></li>
<li class="chapter" data-level="14.11" data-path="answers.html"><a href="answers.html#chapter-10-looking-back-and-looking-forward-1"><i class="fa fa-check"></i><b>14.11</b> Chapter 10 (Looking back and looking forward)</a></li>
<li class="chapter" data-level="14.12" data-path="answers.html"><a href="answers.html#foodpolgdp"><i class="fa fa-check"></i><b>14.12</b> Polity, food diversity, and GDP challenge</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="corrections.html"><a href="corrections.html"><i class="fa fa-check"></i><b>15</b> Corrections</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Companion Website — Insights from Data with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="WFD-food-pol" class="section level1" number="7">
<h1><span class="header-section-number">Chapter 7</span> Are diets more diverse in more democratic countries?</h1>
<p><img src="images/WF3_icon.jpg" width="60"/></p>
<div id="about-this-workflow-demonstration-1" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> About this Workflow Demonstration</h2>
<p>This Workflow Demonstation (WD) is primarily a supplement to the material in the book <em>Insights from Data with R</em> by Petchey, Beckerman, Childs, and Cooper. If you don’t understand something here, have a look at that book (perhaps again), or search for help, or get in touch with us.</p>
<p>At the time of publication (early 2021) there are likely some improvements that could be made to this demonstration, in terms of the description of what we do in it, why we do it, and how we do it. If anything seems odd, unclear, or sub-optimal, please don’t hesitate to get in touch, and we will quickly make improvements.</p>
</div>
<div id="introduction-to-the-study-and-data-1" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> Introduction to the study and data</h2>
<p>In this WD we will look at the diversity of food available to people living in different countries. And we will explore one potential influence of this diversity—the political system (e.g. democratic) of the country. Why this? Why not?</p>
<p>There are likely lots of factors governing the diversity of food available to the population of a country, and political system is just one. We could also look at gross domestic product, location, population size, and so on. But let’s keep things relatively simple and straightforward for the moment. You can make things more complex if you choose to look further into the question. Just wait until after you’ve mastered the simpler though perhaps still challenging enough material in this WD.</p>
<p>To be clear, we are asking the question of whether the diversity of food available to the population of a country is associated with the political system of that country. We hypothesise that more freedom will result in more diversity of food availability (figure <a href="WFD-food-pol.html#fig:insight-sketch-2">7.1</a>). We will restrict ourselves to two variables: diversity of food available and political system. Let’s explore two measures of diversity: the richness of food items, which is just the number of different food types, and a measure of diversity known as the Shannon index, which is greater if there are more food types and if the amount of each is more evenly distributed among them. As far as we know, the analyses are novel. Any insights will be new! Though, since the findings are not published / peer reviewed, they should be treated as preliminary and (as usual) be critically assessed.</p>
<div class="figure" style="text-align: center"><span id="fig:insight-sketch-2"></span>
<img src="images/insights_sketches_002.jpeg" alt="A hypothetical outcome of the demonstration study of relationship between the political system of a country and the diversity of food available." width="70%" />
<p class="caption">
FIGURE 7.1: A hypothetical outcome of the demonstration study of relationship between the political system of a country and the diversity of food available.
</p>
</div>
<p>The data about what food is available to the people of a country is from the <em>FAO Food balance data</em> and that about the political system is from the <em>Polity™ IV Project dataset</em>. Hence there will be something fundamentally new in this WD: importing two different datasets and then merging them together. This turns out to be quite a lot of work, a large part of which is making the two datasets <em>interoperable</em> <a href="data-analysis-concepts.html#interoperability">we mentioned interoperability here</a>.</p>
<p>As you work through this chapter, try following along with the <a href="insights-workflow.html#insights-workflow">workflow/checklist on this web page</a>.</p>
</div>
<div id="understanding-the-data" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Understanding the data</h2>
<p>As mentioned in the book, a number of features of data determine the types of insights we can get from it, and how much we might trust those insights. Though we start with two datasets, we will have only one after we merge them. Here are the features of that one dataset, and how these affect the insights we might reveal.</p>
<ul>
<li><p><strong>Number of variables:</strong> We will have only three variables, the food diversity, the political system, and the year. This is to keep the question and how to answer it simple. It is likely, however, that factors as well as, or other than, the political system of a country affect the food diversity available. Further analyses should explore these other factors (though we do not attempt them here).</p></li>
<li><p><strong>Number of observations:</strong> You will see that we have nearly 200 observations (the number of countries in the final dataset) for each year in the study. So in total we have multiple hundreds of observations (later we see exactly how many), which is quite a lot when one has only two variables. This means we have quite good potential to see patterns that could (if there were fewer observation) otherwise be unclear.</p></li>
<li><p><strong>Variables describing interventions/manipulations</strong>: This is not a randomised experiment; none of the variables describes a manipulation/intervention that is accompanied by a control. Hence we are exploring relationships and will not be able to make inferences about causation.</p></li>
<li><p><strong>Amount of correlation among explanatory variables:</strong> We will only have two explanatory variables (political system and year). Because we will remove the year variable (explore data independent of year), in a sense, we will have no correlation between explanatory variables. Recall that inference is harder if we have multiple explanatory variables and there was some correlation among them. So we are keeping things simple and easy, at least in terms of inference.</p></li>
<li><p><strong>How independent are observations:</strong> Each observation is of a country in a year. I.e. we have multiple observations for each country, and these make up a time series. Put another way, we have “repeated measures” of each country. Hence two observations close together in time are less independent than two far apart in time, and two from the same country are less independent than two from different countries. There are other sources of non-independence that we will pay less attention to, such as geographic closeness, political history, and climate. It would be interesting to investigate their importance, however.</p></li>
</ul>
</div>
<div id="a-little-preparation-1" class="section level2" number="7.4">
<h2><span class="header-section-number">7.4</span> A little preparation</h2>
<p>Make a new folder for this Workflow Demonstration (WD), and in it a folder called in <code>data</code> (this will contain any datasets for this WD/project). In <em>RStudio</em> create an <em>RStudio</em> project and save it in the project folder (not the <code>data</code> folder). Close <em>RStudio</em> and double click on the project file to re-open <em>RStudio</em>. Create a new R script file. In this new script file make a comment about what it will contains, and then load some libraries.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="WFD-food-pol.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the libraries we use</span></span>
<span id="cb105-2"><a href="WFD-food-pol.html#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb105-3"><a href="WFD-food-pol.html#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb105-4"><a href="WFD-food-pol.html#cb105-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb105-5"><a href="WFD-food-pol.html#cb105-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb105-6"><a href="WFD-food-pol.html#cb105-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb105-7"><a href="WFD-food-pol.html#cb105-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb105-8"><a href="WFD-food-pol.html#cb105-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vegan)</span>
<span id="cb105-9"><a href="WFD-food-pol.html#cb105-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggbeeswarm)</span></code></pre></div>
<div class="action">
<p>
Install the <code>vegan</code> and <code>ggbeeswarm</code> library if you have not already done so, otherwise <code>library(vegan)</code> and <code>library(ggbeeswarm)</code> will not work. Look at the <strong>Packages</strong> section of the <em>Getting Acquainted</em> chapter of the book if you need help with installation.
</p>
</div>
<p>Then save the file and give it a filename that is intuitive, unique, and memorable, so it is easy to search for and find.</p>
</div>
<div id="polity-data-origins-acquire-import-clean-tidy-nas-duplicates" class="section level2" number="7.5">
<h2><span class="header-section-number">7.5</span> Polity data: origins, acquire, import, clean, tidy, NAs, duplicates</h2>
<div id="data-origins-and-acquisition" class="section level3" number="7.5.1">
<h3><span class="header-section-number">7.5.1</span> Data origins and acquisition</h3>
<p>A <em>Polity</em> is a political entity. The Polity™ IV Project aimed to code the characteristics of states in the world for the purposes of comparative quantitative analysis (i.e. what we’re about to do!). The project and resulting datasets are used for monitoring regime change and for studying effects of regime authority. Nevertheless, the data “should be treated and interpreted with due caution. Its primary utility is in investigative research which should be augmented by more detailed analysis.”; quoted from page 16 of the <a href="https://www.systemicpeace.org/inscr/p4manualv2016.pdf">Dataset User’s Manual</a> by Monty G. Marshall, Ted Robert Gurr, and Keith Jaggers. Find out more about the project at the <a href="http://www.systemicpeace.org/polityproject.html">Center for Systemic Peace</a> website. By the way, there is another study of the concept and quantification of democracy called <a href="https://www.v-dem.net/">V-Dem</a>.</p>
<p>You can acquire the complete dataset from <a href="http://www.systemicpeace.org/inscrdata.html">this web page of the Center for Systemic Peace</a>. Scroll down to the section <em>Polity IV: Regime Authority Characteristics and Transitions Datasets</em> and click on the <em>Excel Series</em> link to the right of the <em>Polity IV Annual Time-Series, 1800-2017</em> box. The downloaded file is an Excel spreadsheet. We recommend you open this in Excel and save it as a <code>csv</code> file, but we’ll also show below how to read the Excel file into R.</p>
<p>Looking at the dataset in Excel or something similar, you will see that the dataset has 17’061 observations and 36 variables. We will work with only three of the variables:</p>
<ul>
<li><strong>country</strong> - a character variable containing the country name.</li>
<li><strong>year</strong> - a numeric variable containing the year.</li>
<li><strong>polity2</strong> - a numeric variable giving the <em>revised combined polity score</em> from +10 (strongly democratic) to -10 (strongly autocratic).</li>
</ul>
<p>The <em>revised combined polity score</em>, according to the <em>Dataset User’s Manual</em> is a score varying from -10 for the most autocratic of polities, up to +10 for the most democratic, that “provides a convenient avenue for examining general regime effects in analyses.” (The manual also states a number of reasons for treating the variable with caution.)</p>
</div>
<div id="data-import" class="section level3" number="7.5.2">
<h3><span class="header-section-number">7.5.2</span> Data import</h3>
<p>If you did the preparation mentioned above, made a project, made a <code>csv</code> file from the Excel file, and put the data file in the data folder of that project, and you started R by double clicking on the RProject file (or switching to this project), the following code should import the data:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="WFD-food-pol.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb106-2"><a href="WFD-food-pol.html#cb106-2" aria-hidden="true" tabindex="-1"></a>pol <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/p4v2015.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ───────────────────────────────
## cols(
##   .default = col_double(),
##   scode = col_character(),
##   country = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<p>If you want to read direct from the Excel file, use this (you will need to install the <strong>readxl</strong> package if you have not already done so):</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="WFD-food-pol.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb108-2"><a href="WFD-food-pol.html#cb108-2" aria-hidden="true" tabindex="-1"></a>pol <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;data/p4v2015.xls&quot;</span>)</span></code></pre></div>
<p>Is RStudio showing the correct number of rows and columns (you would have had to look at the file in Excel (or another spreadsheet program to know this)? Is it showing the appropriate variable types for each of the three variables? The <code>Country</code> variable should be a character variable, the other two should be numeric.</p>
</div>
<div id="tidy-and-clean" class="section level3" number="7.5.3">
<h3><span class="header-section-number">7.5.3</span> Tidy and clean</h3>
<p>We only want to work with three of the 36 variables, so we use the <code>select</code> function to keep only these, and at the same time rename them to standardise the variable names by making them all begin with an upper case letter and then have lower case:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="WFD-food-pol.html#cb109-1" aria-hidden="true" tabindex="-1"></a>pol <span class="ot">&lt;-</span> pol <span class="sc">%&gt;%</span></span>
<span id="cb109-2"><a href="WFD-food-pol.html#cb109-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">Country =</span> country,</span>
<span id="cb109-3"><a href="WFD-food-pol.html#cb109-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">Year =</span> year,</span>
<span id="cb109-4"><a href="WFD-food-pol.html#cb109-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Polity2 =</span> polity2)</span></code></pre></div>
<div class="info">
<p>
Please note that here and below we do not describe at all or in much detail the R code used. This is because it is described in detail in the book.
</p>
</div>
<p>Because we assign the result of this <code>select</code> operation to <code>pol</code> we are getting rid of the previous version of <code>pol</code> with this new one.</p>
<p>The data set has only one observation (of Polity) per row, so it is already tidy… we do not need to gather observations from multiple columns into one.</p>
</div>
<div id="deal-with-nas" class="section level3" number="7.5.4">
<h3><span class="header-section-number">7.5.4</span> Deal with NAs</h3>
<p>As usual, we should see if there are any NAs in the data, understand what they might result from, and decide what how to treat them. The next code makes a new dataset <code>pol_nas</code> that contains the rows that contain a missing value in any of the three variables.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="WFD-food-pol.html#cb110-1" aria-hidden="true" tabindex="-1"></a>pol_nas <span class="ot">&lt;-</span> pol <span class="sc">%&gt;%</span></span>
<span id="cb110-2"><a href="WFD-food-pol.html#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter_all</span>(<span class="fu">any_vars</span>(<span class="fu">is.na</span>(.))) </span>
<span id="cb110-3"><a href="WFD-food-pol.html#cb110-3" aria-hidden="true" tabindex="-1"></a>pol_nas</span></code></pre></div>
<pre><code>## # A tibble: 235 x 3
##   Country      Year Polity2
##   &lt;chr&gt;       &lt;dbl&gt;   &lt;dbl&gt;
## 1 Afghanistan  1979      NA
## 2 Afghanistan  1980      NA
## 3 Afghanistan  1981      NA
## 4 Afghanistan  1982      NA
## 5 Afghanistan  1983      NA
## # … with 230 more rows</code></pre>
<p>This dataset contains 235 rows, and viewing it we see that it is only the <code>polity2</code> variables that contains NAs. I.e. there are 235 missing <code>Polity2</code> values.</p>
<p>A brief perusal of the <em>Dataset User’s Manual</em> reveals a clue about why some of all of these NAs exist: “Cases of foreign”interruption" are treated as “system missing.”</p>
<p>Let us decide to treat these missing values as unimportant for further analyses, and to not include them in any further analyses, by removing them from the dataset. We know this should leave us with 17,061 - 235 = 16,826 rows of data:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="WFD-food-pol.html#cb112-1" aria-hidden="true" tabindex="-1"></a>pol <span class="ot">&lt;-</span> pol <span class="sc">%&gt;%</span></span>
<span id="cb112-2"><a href="WFD-food-pol.html#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code></pre></div>
<p>You should see that we do, indeed, now have 16,826 rows of data.</p>
<p>We might now like to clean up a little, by removing the <code>pol_nas</code> dataset from R (you will see it dissapear from the <em>Environment</em> pane):</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="WFD-food-pol.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(pol_nas)</span></code></pre></div>
</div>
<div id="check-for-innapropriate-duplicate-observations" class="section level3" number="7.5.5">
<h3><span class="header-section-number">7.5.5</span> Check for innapropriate duplicate observations</h3>
<p>We expect there to not exist any more than one Polity score per country per year. We check this by first selecting only the <code>Country</code> and <code>Year</code> variables, then getting any duplicate rows with the <code>duplicated</code> function. The <code>duplicated</code> function returns a vector of TRUE and FALSE, where TRUE means a row is a duplicate. We can then get the <code>sum</code> of this vector to count the number of TRUEs (i.e. number of duplicated rows).</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="WFD-food-pol.html#cb114-1" aria-hidden="true" tabindex="-1"></a>pol <span class="sc">%&gt;%</span></span>
<span id="cb114-2"><a href="WFD-food-pol.html#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Country, Year) <span class="sc">%&gt;%</span></span>
<span id="cb114-3"><a href="WFD-food-pol.html#cb114-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">duplicated</span>() <span class="sc">%&gt;%</span></span>
<span id="cb114-4"><a href="WFD-food-pol.html#cb114-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>()</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>Interesting. There are two cases that contain duplicates. Let’s see which Country-Year combinations these are:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="WFD-food-pol.html#cb116-1" aria-hidden="true" tabindex="-1"></a>pol <span class="sc">%&gt;%</span></span>
<span id="cb116-2"><a href="WFD-food-pol.html#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Country, Year) <span class="sc">%&gt;%</span></span>
<span id="cb116-3"><a href="WFD-food-pol.html#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">duplicated</span>(.))</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   Country     Year
##   &lt;chr&gt;      &lt;dbl&gt;
## 1 Ethiopia    1993
## 2 Yugoslavia  1991</code></pre>
<p>And look at the duplicated cases:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="WFD-food-pol.html#cb118-1" aria-hidden="true" tabindex="-1"></a>pol <span class="sc">%&gt;%</span></span>
<span id="cb118-2"><a href="WFD-food-pol.html#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Country <span class="sc">==</span> <span class="st">&quot;Yugoslavia&quot;</span>,</span>
<span id="cb118-3"><a href="WFD-food-pol.html#cb118-3" aria-hidden="true" tabindex="-1"></a>         Year <span class="sc">==</span> <span class="dv">1991</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   Country     Year Polity2
##   &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt;
## 1 Yugoslavia  1991      -5
## 2 Yugoslavia  1991      -5</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="WFD-food-pol.html#cb120-1" aria-hidden="true" tabindex="-1"></a>pol <span class="sc">%&gt;%</span></span>
<span id="cb120-2"><a href="WFD-food-pol.html#cb120-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Country <span class="sc">==</span> <span class="st">&quot;Ethiopia&quot;</span>,</span>
<span id="cb120-3"><a href="WFD-food-pol.html#cb120-3" aria-hidden="true" tabindex="-1"></a>         Year <span class="sc">==</span> <span class="dv">1993</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   Country   Year Polity2
##   &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 Ethiopia  1993       0
## 2 Ethiopia  1993       1</code></pre>
<p>Looking through the <em>Dataset User’s Manual</em> does not readily shed light on these duplicates. Let’s remove both cases of duplication by taking the average <code>Polity2</code> score. This should result in a dataset with 16,824 rows.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="WFD-food-pol.html#cb122-1" aria-hidden="true" tabindex="-1"></a>pol <span class="ot">&lt;-</span> pol <span class="sc">%&gt;%</span></span>
<span id="cb122-2"><a href="WFD-food-pol.html#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country, Year) <span class="sc">%&gt;%</span></span>
<span id="cb122-3"><a href="WFD-food-pol.html#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Polity2 =</span> <span class="fu">mean</span>(Polity2))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Country&#39;. You can override using the `.groups` argument.</code></pre>
<div class="warning">
<p>
We just made a decision about how to deal with the duplicated scores. We took the mean. There are other things we could have done (e.g. use a different measure of central tendency, such as the median). So we have made an arbitrary choice in our analysis pathway. We went down one path when we could have chosen another. We need to 1) recognise and record when we make decisions like this, and 2) check to see if our conclusions are robust to variation in what we choose to do. (Here, conclusions would not be affected by using the median, as there are only two values being averaged.)
</p>
</div>
<p>Let us again check for duplicate Country-Year combinations:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="WFD-food-pol.html#cb124-1" aria-hidden="true" tabindex="-1"></a>pol <span class="sc">%&gt;%</span></span>
<span id="cb124-2"><a href="WFD-food-pol.html#cb124-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Country, Year) <span class="sc">%&gt;%</span></span>
<span id="cb124-3"><a href="WFD-food-pol.html#cb124-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">duplicated</span>() <span class="sc">%&gt;%</span></span>
<span id="cb124-4"><a href="WFD-food-pol.html#cb124-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>()</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Good, there are now no duplicated cases.</p>
</div>
<div id="check-ranges-of-numeric-variables" class="section level3" number="7.5.6">
<h3><span class="header-section-number">7.5.6</span> Check ranges of numeric variables</h3>
<p>Its a good idea to check if numeric variables contain any unexpected values. From the <em>Dataset User’s Manual</em> we expect the <code>Year</code> variable to be values including the 19th, 20th, and 21st centuries, and the <code>Polity2</code> variable to have a minimum of -10 and maximum of 10. Write code to check these are true in the imported data. Make the summary dataset and have a look at it for yourself. You should see that the expected ranges of the year and polity variables are respected.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="WFD-food-pol.html#cb126-1" aria-hidden="true" tabindex="-1"></a>pol_summ <span class="ot">&lt;-</span> pol <span class="sc">%&gt;%</span></span>
<span id="cb126-2"><a href="WFD-food-pol.html#cb126-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">min_year =</span> <span class="fu">min</span>(Year),</span>
<span id="cb126-3"><a href="WFD-food-pol.html#cb126-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">max_year =</span> <span class="fu">max</span>(Year),</span>
<span id="cb126-4"><a href="WFD-food-pol.html#cb126-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">min_pol =</span> <span class="fu">min</span>(Polity2),</span>
<span id="cb126-5"><a href="WFD-food-pol.html#cb126-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">max_pol =</span> <span class="fu">max</span>(Polity2))</span></code></pre></div>
<p>We will now save this dataset so we don’t have to run all that code every time:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="WFD-food-pol.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(pol, <span class="st">&quot;data/pol.RDS&quot;</span>)</span></code></pre></div>
</div>
</div>
<div id="first-insights-from-the-polity-data" class="section level2" number="7.6">
<h2><span class="header-section-number">7.6</span> First insights from the polity data</h2>
<p>Before we move on to the FAO dataset, lets have quick look at some features of the Polity data.</p>
<p>Let’s look at the frequency distributions of the two numeric variables. We will do this efficiently by first gathering the information in the two variables into one, then plotting. This is the method used and described in detail in the <em>Insights</em> book. Here is the code that produces figure <a href="WFD-food-pol.html#fig:pol1">7.2</a>:</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="WFD-food-pol.html#cb128-1" aria-hidden="true" tabindex="-1"></a>pol <span class="sc">%&gt;%</span></span>
<span id="cb128-2"><a href="WFD-food-pol.html#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">&quot;Variable&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Value&quot;</span>, <span class="at">cols =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>) <span class="sc">%&gt;%</span></span>
<span id="cb128-3"><a href="WFD-food-pol.html#cb128-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb128-4"><a href="WFD-food-pol.html#cb128-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> Value), <span class="at">bins =</span> <span class="dv">21</span>) <span class="sc">+</span></span>
<span id="cb128-5"><a href="WFD-food-pol.html#cb128-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>( <span class="sc">~</span> Variable, <span class="at">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:pol1"></span>
<img src="insights_website_files/figure-html/pol1-1.svg" alt="Frequency distributions of the polity score and of the year in which observations were made." width="480" />
<p class="caption">
FIGURE 7.2: Frequency distributions of the polity score and of the year in which observations were made.
</p>
</div>
<p>The <code>Polity2</code> variable is numeric with a minimum values of -10 and a maximum of 10 (as we already knew). The most common polity score is very democratic (+10), there are relatively few moderately democratic polity score, and there are a number of several levels of autocratic polity scores. That is, the distribution appears somewhat bimodial. We must be aware, that these are distributions of each score, with many scores for each country.</p>
<p>The <code>Year</code> variable is distributed with more values in the later years than earlier years—it makes some sense that we have more information about the recent than about the distant past. None of the three variables have any missing values, so we expect to see no warnings about excluded data points, and to not have to deal with any other issues caused by missing values. Great!</p>
<p>Try to write code to find out each of these:</p>
<ul>
<li>Number of countries in the dataset.</li>
<li>Number of years in the dataset, and first year, and last year.</li>
<li>How many records (years of data) for each country.</li>
<li>First and last year of data for each country.</li>
<li>Whether there are gaps (years without data) in each country.</li>
<li>Number of countries with gaps (i.e. no data in some years).</li>
<li>Number of countries with records in each year.</li>
<li>Temporal change in polity in some countries that interest you.</li>
<li>Graphs to visualise these where appropriate.</li>
</ul>
<p>Answers for some of these are below.</p>
<p>Number of countries, years, first year and last year:</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="WFD-food-pol.html#cb129-1" aria-hidden="true" tabindex="-1"></a>pol <span class="sc">%&gt;%</span></span>
<span id="cb129-2"><a href="WFD-food-pol.html#cb129-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num_countries =</span> <span class="fu">length</span>(<span class="fu">unique</span>(Country)),</span>
<span id="cb129-3"><a href="WFD-food-pol.html#cb129-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">num_years =</span> <span class="fu">length</span>(<span class="fu">unique</span>(Year)),</span>
<span id="cb129-4"><a href="WFD-food-pol.html#cb129-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">first_year =</span> <span class="fu">min</span>(Year),</span>
<span id="cb129-5"><a href="WFD-food-pol.html#cb129-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">last_year =</span> <span class="fu">max</span>(Year))</span></code></pre></div>
<pre><code>## # A tibble: 193 x 5
##   Country  num_countries num_years first_year last_year
##   &lt;chr&gt;            &lt;int&gt;     &lt;int&gt;      &lt;dbl&gt;     &lt;dbl&gt;
## 1 Afghani…             1       193       1800      2015
## 2 Albania              1       102       1914      2015
## 3 Algeria              1        54       1962      2015
## 4 Angola               1        41       1975      2015
## 5 Argenti…             1       191       1825      2015
## # … with 188 more rows</code></pre>
<p>For each country, number of years of records, first year, last year, number of years between first and last, and if there are gaps of no data:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="WFD-food-pol.html#cb131-1" aria-hidden="true" tabindex="-1"></a>per_country_pol <span class="ot">&lt;-</span> pol <span class="sc">%&gt;%</span></span>
<span id="cb131-2"><a href="WFD-food-pol.html#cb131-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country) <span class="sc">%&gt;%</span></span>
<span id="cb131-3"><a href="WFD-food-pol.html#cb131-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num_years =</span> <span class="fu">length</span>(<span class="fu">unique</span>(Year)),</span>
<span id="cb131-4"><a href="WFD-food-pol.html#cb131-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">first_year =</span> <span class="fu">min</span>(Year),</span>
<span id="cb131-5"><a href="WFD-food-pol.html#cb131-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">last_year =</span> <span class="fu">max</span>(Year),</span>
<span id="cb131-6"><a href="WFD-food-pol.html#cb131-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">years_interval =</span> last_year <span class="sc">-</span> first_year <span class="sc">+</span><span class="dv">1</span>,</span>
<span id="cb131-7"><a href="WFD-food-pol.html#cb131-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">gaps =</span> num_years <span class="sc">!=</span> years_interval)</span></code></pre></div>
<p>Number of countries with gappy information:</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="WFD-food-pol.html#cb132-1" aria-hidden="true" tabindex="-1"></a>per_country_pol <span class="sc">%&gt;%</span></span>
<span id="cb132-2"><a href="WFD-food-pol.html#cb132-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">sum</span>(gaps))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   `sum(gaps)`
##         &lt;int&gt;
## 1          46</code></pre>
<p>Code for a graph of the number of countries with records in each year:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="WFD-food-pol.html#cb134-1" aria-hidden="true" tabindex="-1"></a>pol <span class="sc">%&gt;%</span></span>
<span id="cb134-2"><a href="WFD-food-pol.html#cb134-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb134-3"><a href="WFD-food-pol.html#cb134-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num_countries =</span> <span class="fu">length</span>(<span class="fu">unique</span>(Country))) <span class="sc">%&gt;%</span></span>
<span id="cb134-4"><a href="WFD-food-pol.html#cb134-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb134-5"><a href="WFD-food-pol.html#cb134-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span>Year, <span class="at">y=</span>num_countries))</span></code></pre></div>
<p>Change in polity in some countries of interest (to the authors at least) (the code below produces figure (fig:pol2):</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="WFD-food-pol.html#cb135-1" aria-hidden="true" tabindex="-1"></a>countries_of_interest <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Bhutan&quot;</span>, <span class="st">&quot;Brasil&quot;</span>, <span class="st">&quot;Cuba&quot;</span>, <span class="st">&quot;Cambodia&quot;</span>,</span>
<span id="cb135-2"><a href="WFD-food-pol.html#cb135-2" aria-hidden="true" tabindex="-1"></a>                           <span class="st">&quot;Estonia&quot;</span>, <span class="st">&quot;Yugoslavia&quot;</span>, <span class="st">&quot;Australia&quot;</span>)</span>
<span id="cb135-3"><a href="WFD-food-pol.html#cb135-3" aria-hidden="true" tabindex="-1"></a>pol <span class="sc">%&gt;%</span></span>
<span id="cb135-4"><a href="WFD-food-pol.html#cb135-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Country <span class="sc">%in%</span> countries_of_interest) <span class="sc">%&gt;%</span></span>
<span id="cb135-5"><a href="WFD-food-pol.html#cb135-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb135-6"><a href="WFD-food-pol.html#cb135-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Country) <span class="sc">+</span></span>
<span id="cb135-7"><a href="WFD-food-pol.html#cb135-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span>Year, <span class="at">y=</span>Polity2, <span class="at">col=</span>Country)) <span class="sc">+</span></span>
<span id="cb135-8"><a href="WFD-food-pol.html#cb135-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>Year, <span class="at">y=</span>Polity2, <span class="at">col=</span>Country))</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:pol2"></span>
<img src="insights_website_files/figure-html/pol2-1.svg" alt="Change in polity in some countries of interest (to the authors at least)" width="672" />
<p class="caption">
FIGURE 7.3: Change in polity in some countries of interest (to the authors at least)
</p>
</div>
<p><em>Insight</em>: That the polity score of a country can change so greatly has implications for our subsequent analyses. For example, calculating and using a mean polity score for each country (average across years) may be unwise as it would ignore such temporal change.</p>
</div>
<div id="acquire-import-check-the-fao-food-balance-sheet-data" class="section level2" number="7.7">
<h2><span class="header-section-number">7.7</span> Acquire, import, check the FAO Food balance sheet data</h2>
<p><strong>Important note: the food balance sheet data available on the FAO website was updated since the writing of this section. The currently (November 2020) available dataset is not the same as that used below. Please be sure to get and use the data here: <a href="data/FoodBalanceSheets_E_All_Data_reduced.Rdata">direct download small FAO balance sheet data</a>. Do not use the data from the FAO website.</strong></p>
<p>Let us now move on to the dataset we use to get the food diversity measure for each country. The dataset gives, for various <em>Areas</em> in the world, such as countries and continents, the annual supply and use of various food <em>Items</em> such as “Wheat and products,” “Honey,” and “Crustaceans.” Supply and use includes what are called <em>Elements</em> of the food supply equation; elements such as “Production,” Import Quantity“, and”Food supply quantity (kg/capita/yr)". The words <em>Area</em>, <em>Item</em>, and <em>Element</em> are emphasised because they are variables in the dataset, as described further below. There is a lot of important information about this data available on the <a href="http://www.fao.org/faostat/en/#data/FBS/metadata">FAO Food Balance Sheet Metadata</a> web page web page. And even more in the <a href="http://www.fao.org/economic/ess/fbs/ess-fbs02/en/">Food Balance Sheet Methodology Handbook</a>.</p>
<p>The full dataset is 206 MB and can be downloaded from the FAO web page (this is no longer true since the update mentioned above). Importing this takes about 4 seconds on a reasonably fast laptop. As you will see below, we will make a smaller dataset (about 15 MB) and save it, so we don’t have to work with the full dataset.</p>
<p>The full dataset has 238,560 rows and 113 variables. The first nine variables are:</p>
<ul>
<li><strong>Area.code</strong> - A numeric variable containing number codes for the <em>Area</em> variable.</li>
<li><strong>Area</strong> - A character variable containing the geographic area that a row is about, for example, a country name or a continent name.</li>
<li><strong>Item.code</strong> - A numeric variable containing number codes for the food items in the <em>Item</em> variable.</li>
<li><strong>Item</strong> - A character variable containing the food item a row is about.</li>
<li><strong>Element.code</strong> - A numeric variable contains number codes for the <em>Element</em> variable.</li>
<li><strong>Element</strong> - A character variable showing the particular supply or utlilisation element a row is about. These are the elements of the food balance equation.</li>
<li><strong>Unit</strong> - The units of measure of the quantity in the row.</li>
<li><strong>Y1961</strong> - A numeric variable giving the quantity in year 1961</li>
<li><strong>Y1961F</strong> - A character variable giving information about the data (F is for Flag), such as “Official data,” “FAO data,” etc.</li>
</ul>
<p>The <em>Definitions and standard button</em> on this web page <a href="http://www.fao.org/faostat/en/#data/FBS/metadata" class="uri">http://www.fao.org/faostat/en/#data/FBS/metadata</a> leads to much much more information about the variables and entries.</p>
<p>** Seems that the data have been updated online!!! and don’t include many years.**</p>
<p>DO NOT get the FAO food balance data from the <a href="http://www.fao.org/faostat/en/#data/FBS/metadata">FAO website</a>. At the time of writing, the datafile you would get is called <code>FoodBalanceSheets_E_All_Data.csv</code> and is 206 MB, i.e. it is quite big. (Now there is a different dataset available.) We need, however, only a small amount of the information in this dataset. So to make things easier for ourselves and for you, we created a smaller dataset containing only the data we need, and saved it as an <em>RDS</em> type of file. This file type fits more data into a smaller space—the resulting file <code>FoodBalanceSheets_E_All_Data_reduced.Rdata</code> is 1.9MB. You can download that data here: <a href="data/FoodBalanceSheets_E_All_Data_reduced.Rdata">direct download small FAO balance sheet data</a>.</p>
<p>In case you are interested, here is the code we used to reduce the 206 MB file down to something more manageable. It’s pretty straightforward, apart from two things.</p>
<p>First, we give the <code>read_csv</code> an argument you didn’t previously see: <code>encoding</code>. This helps <code>read_csv</code> properly recognise otherwise problematic symbols. In this case, it ensure that country names such as <em>Côte d’Ivoire</em> don’t cause problems (the “ô” can otherwise do so).</p>
<p>Second, the penultimate line saves the produced tibble <code>ff</code> to a <code>Rdata</code> type of data file; though even that new type of instruction should be quite transparent to you by now.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="WFD-food-pol.html#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the full food balance sheet dataset *All data* from the FAO website:</span></span>
<span id="cb136-2"><a href="WFD-food-pol.html#cb136-2" aria-hidden="true" tabindex="-1"></a><span class="co"># http://www.fao.org/faostat/en/#data/FBS/metadata.</span></span>
<span id="cb136-3"><a href="WFD-food-pol.html#cb136-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Reduce the size of the FAO data, so easier to deal with</span></span>
<span id="cb136-4"><a href="WFD-food-pol.html#cb136-4" aria-hidden="true" tabindex="-1"></a><span class="co"># import FAO data</span></span>
<span id="cb136-5"><a href="WFD-food-pol.html#cb136-5" aria-hidden="true" tabindex="-1"></a>fbs <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/FoodBalanceSheets_E_All_Data.csv&quot;</span>,</span>
<span id="cb136-6"><a href="WFD-food-pol.html#cb136-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">locale =</span> <span class="fu">locale</span>(<span class="at">encoding =</span> <span class="st">&#39;ISO-8859-1&#39;</span>))</span>
<span id="cb136-7"><a href="WFD-food-pol.html#cb136-7" aria-hidden="true" tabindex="-1"></a><span class="co"># First fix some variable names:</span></span>
<span id="cb136-8"><a href="WFD-food-pol.html#cb136-8" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(fbs) <span class="ot">&lt;-</span> <span class="fu">str_replace_all</span>(<span class="fu">names</span>(fbs), <span class="fu">c</span>(<span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="st">&quot;_&quot;</span>))</span>
<span id="cb136-9"><a href="WFD-food-pol.html#cb136-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove all non-countries</span></span>
<span id="cb136-10"><a href="WFD-food-pol.html#cb136-10" aria-hidden="true" tabindex="-1"></a>fbs <span class="ot">&lt;-</span> <span class="fu">filter</span>(fbs, Country_Code <span class="sc">&lt;</span> <span class="dv">5000</span>)</span>
<span id="cb136-11"><a href="WFD-food-pol.html#cb136-11" aria-hidden="true" tabindex="-1"></a><span class="co"># keep only some of the elements</span></span>
<span id="cb136-12"><a href="WFD-food-pol.html#cb136-12" aria-hidden="true" tabindex="-1"></a>fbs <span class="ot">&lt;-</span> <span class="fu">filter</span>(fbs, Element <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Food supply quantity (kg/capita/yr)&quot;</span>))</span>
<span id="cb136-13"><a href="WFD-food-pol.html#cb136-13" aria-hidden="true" tabindex="-1"></a><span class="co"># remove some other variables that won&#39;t be used</span></span>
<span id="cb136-14"><a href="WFD-food-pol.html#cb136-14" aria-hidden="true" tabindex="-1"></a>fbs <span class="ot">&lt;-</span> <span class="fu">select</span>(fbs, <span class="sc">-</span>Country_Code, <span class="sc">-</span>Item_Code,</span>
<span id="cb136-15"><a href="WFD-food-pol.html#cb136-15" aria-hidden="true" tabindex="-1"></a>             <span class="sc">-</span>Element_Code, <span class="sc">-</span>Element, <span class="sc">-</span>Unit,</span>
<span id="cb136-16"><a href="WFD-food-pol.html#cb136-16" aria-hidden="true" tabindex="-1"></a>             <span class="sc">-</span><span class="fu">ends_with</span>(<span class="st">&quot;F&quot;</span>))</span>
<span id="cb136-17"><a href="WFD-food-pol.html#cb136-17" aria-hidden="true" tabindex="-1"></a><span class="co"># save the reduced file</span></span>
<span id="cb136-18"><a href="WFD-food-pol.html#cb136-18" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(fbs, <span class="st">&quot;data/FoodBalanceSheets_E_All_Data_reduced.Rdata&quot;</span>)</span>
<span id="cb136-19"><a href="WFD-food-pol.html#cb136-19" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(fbs)</span></code></pre></div>
<p>The next line reads in that smaller dataset (this is the one you should start with; download it <a href="data/FoodBalanceSheets_E_All_Data_reduced.Rdata">here</a>:</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="WFD-food-pol.html#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="co">#rm(list = ls())</span></span>
<span id="cb137-2"><a href="WFD-food-pol.html#cb137-2" aria-hidden="true" tabindex="-1"></a>fbs <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;data/FoodBalanceSheets_E_All_Data_reduced.Rdata&quot;</span>)</span></code></pre></div>
<p>Feel free to have a look at the dataset with the <code>glimpse</code> function. We <code>select</code> a few columns first, as otherwise the output is rather long due to there being 112 variables in the dataset.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="WFD-food-pol.html#cb138-1" aria-hidden="true" tabindex="-1"></a>fbs <span class="sc">%&gt;%</span></span>
<span id="cb138-2"><a href="WFD-food-pol.html#cb138-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Country, Item, Y1961, Y1971, Y1981, Y1991, Y2001, Y2011) <span class="sc">%&gt;%</span></span>
<span id="cb138-3"><a href="WFD-food-pol.html#cb138-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 17,953
## Columns: 8
## $ Country &lt;chr&gt; &quot;China&quot;, &quot;China&quot;, &quot;China&quot;, &quot;China&quot;, …
## $ Item    &lt;chr&gt; &quot;Wheat and products&quot;, &quot;Rice (Milled …
## $ Y1961   &lt;dbl&gt; 20.88, 42.15, 5.78, 2.30, 1.32, 1.14…
## $ Y1971   &lt;dbl&gt; 33.02, 70.71, 2.70, 3.24, 1.16, 0.56…
## $ Y1981   &lt;dbl&gt; 62.57, 75.21, 2.38, 4.57, 1.11, 0.66…
## $ Y1991   &lt;dbl&gt; 77.59, 73.06, 1.10, 4.63, 0.57, 0.30…
## $ Y2001   &lt;dbl&gt; 71.94, 77.48, 0.43, 6.60, 0.16, 0.17…
## $ Y2011   &lt;dbl&gt; 63.03, 79.24, 0.17, 7.38, 0.10, 0.11…</code></pre>
<p>There are 17’953 observations/rows in the dataset. The country and food item variables are character variables, the year variables (which contain amounts of food for each year) contain numeric (double) variables.</p>
<p>Now find the number of countries and the number of food items:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="WFD-food-pol.html#cb140-1" aria-hidden="true" tabindex="-1"></a>fbs <span class="sc">%&gt;%</span></span>
<span id="cb140-2"><a href="WFD-food-pol.html#cb140-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num_countries =</span> <span class="fu">length</span>(<span class="fu">unique</span>(Country)),</span>
<span id="cb140-3"><a href="WFD-food-pol.html#cb140-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">num_food_items =</span> <span class="fu">length</span>(<span class="fu">unique</span>(Item)))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   num_countries num_food_items
##           &lt;int&gt;          &lt;int&gt;
## 1           182            114</code></pre>
<p>There are 182 countries, so 11 fewer than in the Polity data. We will later check which ones are not in the Polity data, and if any in the Polity data are not in the FAO data. There are 114 food <code>Items</code>… wow, that’s a lot of different types of food! Take a look at some of the values… it’s quite interesting to see what’s recorded.</p>
<p>If the data contained every possible combination of country and item we would expect 182 * 114 = 20’748 observations. That there are only 17’953 tells us that some combinations are missing. We will find out which these are and deal with them appropriately!</p>
<p>The six variables we <code>glimpse</code> above, with names like <code>Y1961</code> each contain amounts of food available (food supply quantities in kg per capita per year) in the year referred to in the variable name (i.e. 1961) and are, as expected, numeric.</p>
<p>We will examine for missing values and duplicates after tidying the data, as it is then more efficient to do so.</p>
<div id="tidying-FAO" class="section level3" number="7.7.1">
<h3><span class="header-section-number">7.7.1</span> Tidy the FAO data</h3>
<p>The FAO data is not tidy. You should be able to figure out in what respect it is “dirty.” Have a think about this before reading on.</p>
<p>Yes! … The same information is spread across multiple columns/variables, such that there are multiple observations in each row. More specifically, the data for each year is in a separate column—data for different years are spread across columns—each row contains lots of observations each from a different year.</p>
<p>It is not that this is a bad or unexpected arrangement for the data. It is, in fact, a quite compact arrangement. But it is not so easy for us to work with in R, so we will change it to be “tidy.”</p>
<p>Before we make the data tidy, let’s try to figure out how many rows it should have when tidy. We will gather food item quantity information that is currently spread across columns and put it in one column. A visualisation of a simplified version of the dataset is in Figure <a href="WFD-food-pol.html#fig:long-wide">7.4</a>.</p>
<p>Again, how many rows should there be: the answer is the amount of information that’s in the columns that we want to gather into a single column. In the untidy/wide data there are 55 variables containing the data we wish to gather (because we are not gathering the information from <code>Country</code> or <code>Item</code>). Each of those variables has 17,953 rows, so we expect the long/tidy data to have 55 * 17,953 = 987,415 rows.</p>
<div class="figure" style="text-align: center"><span id="fig:long-wide"></span>
<img src="images/long_wide.jpg" alt="The same data (a) in long/tidy format and (b) in wide format, with colours and arrows linking the same data in the two different formats." width="90%" />
<p class="caption">
FIGURE 7.4: The same data (a) in long/tidy format and (b) in wide format, with colours and arrows linking the same data in the two different formats.
</p>
</div>
<p>Let’s now make the data tidy, and clean up the year variable. We first gather all the same data from columns three through 57 (<code>3:57</code>) into a new variable called <code>Food_Supply_Quantity</code> and put the information about which year each observation belongs to in a new variable called <code>Year</code>. Because the column names begin with Y (e.g. <code>Y1961</code>) we then need to keep only the 2nd through to 5th character in the <code>Year</code> variable (using the <code>substr</code> function), and convert the result to a numeric type variable (with the <code>as.numeric</code> function), doing all this within a <code>mutate</code> in order to replace the old year variable with the converted one. Let’s then <code>glimpse</code> the data. Here’s the code for all that:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="WFD-food-pol.html#cb142-1" aria-hidden="true" tabindex="-1"></a>fbs_long <span class="ot">&lt;-</span> fbs <span class="sc">%&gt;%</span></span>
<span id="cb142-2"><a href="WFD-food-pol.html#cb142-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">&quot;Year&quot;</span>,</span>
<span id="cb142-3"><a href="WFD-food-pol.html#cb142-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">&quot;Food_Supply_Quantity&quot;</span>,</span>
<span id="cb142-4"><a href="WFD-food-pol.html#cb142-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">cols =</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">57</span>) <span class="sc">%&gt;%</span></span>
<span id="cb142-5"><a href="WFD-food-pol.html#cb142-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Year =</span> <span class="fu">as.numeric</span>(<span class="fu">substr</span>(Year, <span class="dv">2</span>, <span class="dv">5</span>)))</span>
<span id="cb142-6"><a href="WFD-food-pol.html#cb142-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(fbs_long)</span></code></pre></div>
<pre><code>## Rows: 987,415
## Columns: 4
## $ Country              &lt;chr&gt; &quot;China&quot;, &quot;China&quot;, &quot;Chin…
## $ Item                 &lt;chr&gt; &quot;Wheat and products&quot;, &quot;…
## $ Year                 &lt;dbl&gt; 1961, 1962, 1963, 1964,…
## $ Food_Supply_Quantity &lt;dbl&gt; 20.88, 23.29, 25.64, 27…</code></pre>
<p>We see that as expected the new tibble contains 987,415 observations. Excellent! This near-magical gather function has done a lot of very tedious work for us, very quickly.</p>
<p>Do a few things now for yourself:</p>
<ul>
<li>Check we still have 182 countries and 114 food items (114).</li>
<li>Confirm that the data covers the years 1961 through 2015.</li>
<li>Confirm the distribution of the food supply quantity variable has lots of small values, and a few large. Is this what you would expect? Perhaps supply is large for a few basic foods (e.g. grains) and then there are lots of relatively rare food items.</li>
<li>Confirm that only the food supply quantity variable contains missing values, and that there are 158,307 of them.</li>
</ul>
<p>Beware that at present we are looking at the distribution including data from across years and countries. We will soon look more closely at this distribution.</p>
</div>
<div id="clean-the-fao-data" class="section level3" number="7.7.2">
<h3><span class="header-section-number">7.7.2</span> Clean the FAO data</h3>
<p>Are all the years represented in the dataset? Let’s look at the unique values of the year variable:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="WFD-food-pol.html#cb144-1" aria-hidden="true" tabindex="-1"></a>fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb144-2"><a href="WFD-food-pol.html#cb144-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb144-3"><a href="WFD-food-pol.html#cb144-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>##  [1] 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970
## [11] 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980
## [21] 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990
## [31] 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000
## [41] 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010
## [51] 2011 2012 2013 2014 2015</code></pre>
<p>Yes, every year from 1961 to 2015 is represented (by at least one observation). There are 55 years in the dataset.</p>
</div>
<div id="check-for-innapropriate-duplicate-observations-1" class="section level3" number="7.7.3">
<h3><span class="header-section-number">7.7.3</span> Check for innapropriate duplicate observations</h3>
<p>As before, we should check for innapropriate duplicate observations. Do we think there can be/should be any duplicated rows in this dataset? That would be the exactly the same value of Country, Item, Year, and Food Supply Quantity. Lets check:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="WFD-food-pol.html#cb146-1" aria-hidden="true" tabindex="-1"></a>duplicated_records <span class="ot">&lt;-</span> fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb146-2"><a href="WFD-food-pol.html#cb146-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">duplicated</span>(.))</span></code></pre></div>
<p>Note that the resulting tibble contains only one example of each duplicate (look at the data with <code>View(duplicated_rows)</code>.</p>
<p>And have a look at one of these duplicates:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="WFD-food-pol.html#cb147-1" aria-hidden="true" tabindex="-1"></a>fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb147-2"><a href="WFD-food-pol.html#cb147-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Country <span class="sc">==</span> <span class="st">&quot;Afghanistan&quot;</span>,</span>
<span id="cb147-3"><a href="WFD-food-pol.html#cb147-3" aria-hidden="true" tabindex="-1"></a>         Item <span class="sc">==</span> <span class="st">&quot;Eggs&quot;</span>,</span>
<span id="cb147-4"><a href="WFD-food-pol.html#cb147-4" aria-hidden="true" tabindex="-1"></a>         Year <span class="sc">==</span> <span class="dv">1961</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   Country     Item   Year Food_Supply_Quantity
##   &lt;chr&gt;       &lt;chr&gt; &lt;dbl&gt;                &lt;dbl&gt;
## 1 Afghanistan Eggs   1961                 0.94
## 2 Afghanistan Eggs   1961                 0.94</code></pre>
<p>There are 9,287 rows that are duplicated (not unique). Let’s assume (somewhat dangerously perhaps) that these are mistaken duplicate entries, and so reduce to a dataset with only unique rows:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="WFD-food-pol.html#cb149-1" aria-hidden="true" tabindex="-1"></a>fbs_long <span class="ot">&lt;-</span> <span class="fu">unique</span>(fbs_long)</span></code></pre></div>
<p>Now, if we’re being really paranoid, we might wonder if there were ever two different values of food supply recorded for the same country in the same year. Put another way, if we look at only the Country, Year, and Item variables, do we see duplicated rows?</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="WFD-food-pol.html#cb150-1" aria-hidden="true" tabindex="-1"></a>part_duplicated_records <span class="ot">&lt;-</span> fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb150-2"><a href="WFD-food-pol.html#cb150-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Country, Item, Year) <span class="sc">%&gt;%</span></span>
<span id="cb150-3"><a href="WFD-food-pol.html#cb150-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">duplicated</span>() <span class="sc">%&gt;%</span></span>
<span id="cb150-4"><a href="WFD-food-pol.html#cb150-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(fbs_long, .)</span></code></pre></div>
<p>Looking at the result we see there are 10733 rows with duplicated <code>Country</code>, <code>Year</code>, and <code>Item</code>. This is weird. And these these duplicates are only for food items “Eggs” and “Milk - Excluding Butter.” We have no idea why there are multiple entries for these two items! Here’s an example of one of the duplicates:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="WFD-food-pol.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(fbs_long,</span>
<span id="cb151-2"><a href="WFD-food-pol.html#cb151-2" aria-hidden="true" tabindex="-1"></a>       Country <span class="sc">==</span> <span class="st">&quot;Albania&quot;</span>,</span>
<span id="cb151-3"><a href="WFD-food-pol.html#cb151-3" aria-hidden="true" tabindex="-1"></a>       Item <span class="sc">==</span> <span class="st">&quot;Eggs&quot;</span>,</span>
<span id="cb151-4"><a href="WFD-food-pol.html#cb151-4" aria-hidden="true" tabindex="-1"></a>       Year <span class="sc">==</span> <span class="dv">1961</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   Country Item   Year Food_Supply_Quantity
##   &lt;chr&gt;   &lt;chr&gt; &lt;dbl&gt;                &lt;dbl&gt;
## 1 Albania Eggs   1961                  1.5
## 2 Albania Eggs   1961                  1.8</code></pre>
<p>In the same year, for the same country, for the same item, there are two values of Food_Supply_Quantity: 1.5 and 1.8. But it’s quite reasonable to think there should be only one. Let’s solve this problem by rather arbitrarily calculating one value, the average, of these duplicated records:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="WFD-food-pol.html#cb153-1" aria-hidden="true" tabindex="-1"></a>fbs_long <span class="ot">&lt;-</span> fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb153-2"><a href="WFD-food-pol.html#cb153-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country, Year, Item) <span class="sc">%&gt;%</span></span>
<span id="cb153-3"><a href="WFD-food-pol.html#cb153-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Food_Supply_Quantity =</span> <span class="fu">mean</span>(Food_Supply_Quantity))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Country&#39;, &#39;Year&#39;. You can override using the `.groups` argument.</code></pre>
<div class="info">
<p>
Time to tell the truth. It took us a some considerable time to realise there were duplicated records in the FAO dataset. We only realised there must be duplicates when we tried to get the numbers to add up below. They did not before we removed the duplicates, and this led us to find the duplicates. Once we found them, we removed them above. In the text above, it may look like we were really smart to think they might occur, check for them, find them, and remove them. In reality we were not so smart. We were, however, absolutely determined to understand why the numbers did not add up. You must also be as strict in your work. After we found the duplicates in this dataset, we also looked in the Polity data, found some, and then decided to add a check for duplicates to all our Workflow Demostrations, and to advise you to make this a standard sanity check when you start looking at a dataset.
</p>
</div>
<p>That was a major step forward. Now we know our dataset has only unique observations.</p>
</div>
<div id="checking-something-else" class="section level3" number="7.7.4">
<h3><span class="header-section-number">7.7.4</span> Checking something else…</h3>
<p>Now let’s do another sanity check. Because there are 182 countries and 114 food items we know there could be 20,748 observations for each year. Let’s see how many there really are:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="WFD-food-pol.html#cb155-1" aria-hidden="true" tabindex="-1"></a>obs_per_year <span class="ot">&lt;-</span> fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb155-2"><a href="WFD-food-pol.html#cb155-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb155-3"><a href="WFD-food-pol.html#cb155-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num =</span> <span class="fu">n</span>())</span></code></pre></div>
<p>There are only 17,589 observation per year. Either not all countries reported in all years, not all items were reported by each country in each year, or both!</p>
<p>First let’s see how many countries there are per year:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="WFD-food-pol.html#cb156-1" aria-hidden="true" tabindex="-1"></a>countries_per_year <span class="ot">&lt;-</span> fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb156-2"><a href="WFD-food-pol.html#cb156-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb156-3"><a href="WFD-food-pol.html#cb156-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num =</span> <span class="fu">length</span>(<span class="fu">unique</span>(Country)))</span></code></pre></div>
<p>There are indeed 182 countries per year. All countries are included in all years.</p>
<p>Let’s see how many Items each country reported (across all years):</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="WFD-food-pol.html#cb157-1" aria-hidden="true" tabindex="-1"></a>items_per_country <span class="ot">&lt;-</span> fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb157-2"><a href="WFD-food-pol.html#cb157-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country) <span class="sc">%&gt;%</span></span>
<span id="cb157-3"><a href="WFD-food-pol.html#cb157-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num =</span> <span class="fu">length</span>(<span class="fu">unique</span>(Item)))</span></code></pre></div>
<p>Aha. Not all items were reported by all countries. Turkmenistan reported on the fewest (62), while China reported on the most (110). Let’s see if the sum of the number of items reported by each country is the number of observations per year.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="WFD-food-pol.html#cb158-1" aria-hidden="true" tabindex="-1"></a>items_per_country <span class="sc">%&gt;%</span></span>
<span id="cb158-2"><a href="WFD-food-pol.html#cb158-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">sum</span>(num))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   total
##   &lt;int&gt;
## 1 17589</code></pre>
<p>Yes! This is the same as the number of observations per year. All this pretty much guarantees that each country consistently (across all years) reported on a constant set of the items, or there is an observation for this set of items in each year.</p>
<div class="effrel">
<p>
We didn’t just now find out anything new about the data, but we did confirm that we understand it properly. Checks and balances increase confidence.
</p>
</div>
</div>
<div id="missing-values" class="section level3" number="7.7.5">
<h3><span class="header-section-number">7.7.5</span> Missing values</h3>
<p>Now let’s look at the missing values:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="WFD-food-pol.html#cb160-1" aria-hidden="true" tabindex="-1"></a>fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb160-2"><a href="WFD-food-pol.html#cb160-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="fu">list</span>( <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)))) <span class="sc">%&gt;%</span></span>
<span id="cb160-3"><a href="WFD-food-pol.html#cb160-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 10,010
## Columns: 4
## Groups: Country [182]
## $ Country              &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghani…
## $ Year                 &lt;dbl&gt; 1961, 1962, 1963, 1964,…
## $ Item                 &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0,…
## $ Food_Supply_Quantity &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
<p>We still have 158,307 missing values. Why? Where are they coming from?</p>
<p>Let’s dig a bit deeper by getting the number of observations per year, and the number and proportion of these that are missing values:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="WFD-food-pol.html#cb162-1" aria-hidden="true" tabindex="-1"></a>obs_per_year <span class="ot">&lt;-</span> fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb162-2"><a href="WFD-food-pol.html#cb162-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb162-3"><a href="WFD-food-pol.html#cb162-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num =</span> <span class="fu">n</span>(),</span>
<span id="cb162-4"><a href="WFD-food-pol.html#cb162-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">num_na =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(Food_Supply_Quantity)),</span>
<span id="cb162-5"><a href="WFD-food-pol.html#cb162-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">prop_na =</span> num_na <span class="sc">/</span> num)</span></code></pre></div>
<p>And take a look at the data using <code>View(obs_per_year)</code>. We can also see quite a bit if we plot the summary data (<a href="WFD-food-pol.html#fig:long-wide">7.4</a>) with the following code:</p>
<div class="figure" style="text-align: center"><span id="fig:fao-pol1"></span>
<img src="insights_website_files/figure-html/fao-pol1-1.svg" alt="The number of observations, the number of missing values and the proportion of missing values in each year of the data." width="576" />
<p class="caption">
FIGURE 7.5: The number of observations, the number of missing values and the proportion of missing values in each year of the data.
</p>
</div>
<p>We see that from 1961 to 1991 there are around 2,500 (15%) missing values per year. From 1992 to 2011 there are less than 5% of the values are missing, and from 2012 to 2015 (the last year in the dataset) most or all the values are missing. Can you think of why there might be fewer missing values after 1991?</p>
<p>Let’s look at one country (its identity might give you a clue)… Belarus. Let’s get the number of values, missing values, and proportion of missing values for Belarus in each year.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="WFD-food-pol.html#cb163-1" aria-hidden="true" tabindex="-1"></a>Belarus_obs_per_year <span class="ot">&lt;-</span> fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb163-2"><a href="WFD-food-pol.html#cb163-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Country <span class="sc">==</span> <span class="st">&quot;Belarus&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb163-3"><a href="WFD-food-pol.html#cb163-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb163-4"><a href="WFD-food-pol.html#cb163-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num =</span> <span class="fu">n</span>(),</span>
<span id="cb163-5"><a href="WFD-food-pol.html#cb163-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">num_na =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(Food_Supply_Quantity)),</span>
<span id="cb163-6"><a href="WFD-food-pol.html#cb163-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">prop_na =</span> num_na <span class="sc">/</span> num)</span></code></pre></div>
<p>Looking at this dataset we see that all values are missing until 1992, and then there are no missing values until 2012, when all are again missing. It’s probably clear by now that all values are missing until 1992 because Belarus only became an independent state in 1991. Likely there are lots of other countries in the dataset that have missing values for this reason.</p>
<p>There’s some stuff going on:</p>
<ul>
<li>Belgium and Luxembourg did not separately report data during the period 1992-1999, and instead reported jointly. Then from 2000 until 2011 reported separately, so there we have lots of missing values.</li>
<li>Some countries ceased to exist in their former state, e.g. Czechoslovakia after 1993 contains only missing values due to its dissolution into the Czech Republic and Slovakia.</li>
<li>Similarly, the USSR reports only missing values after 1991 when the USSR ceased to exist.</li>
</ul>
<p>And why more missing values from 2012 to 2015? Actually, the description of the data on the FAO web site says the data is from 1961 to only 2013, so it’s not surprising that 2014 and 2015 are empty. We will remove these years. We don’t know why there are more missing values in 2012 and 2013, so let’s also remove those:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="WFD-food-pol.html#cb164-1" aria-hidden="true" tabindex="-1"></a>fbs_long <span class="ot">&lt;-</span> <span class="fu">filter</span>(fbs_long, Year <span class="sc">&lt;</span> <span class="dv">2012</span>)</span></code></pre></div>
</div>
<div id="more-cleaning" class="section level3" number="7.7.6">
<h3><span class="header-section-number">7.7.6</span> More cleaning</h3>
<p>This seems still rather messy! Let’s aim for a dataset that contains only country/year combinations where a country actually existed (i.e. there were not all NAs reported). And also a dataset in which there is an entry for all 114 food items for each country-year combination (by putting zeros in for no reported item). (Note that this could be quite dangerous, as its possible that an item not being reported is not because it was not present in that country and year. It may have been not reported for other reasons.)</p>
<p>First we get a list of the years in which each country does not contain all missing values. This we will use as a master list of years and countries to include in our analysis. We will not include year/country combinations where there were only missing values (the reason we need to be this specific is that we will soon turn the missing values into zeros). Let’s get that list of country/year combinations to include:</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="WFD-food-pol.html#cb165-1" aria-hidden="true" tabindex="-1"></a>country_year_not_all_missing <span class="ot">&lt;-</span> fbs_long <span class="sc">%&gt;%</span></span>
<span id="cb165-2"><a href="WFD-food-pol.html#cb165-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country, Year) <span class="sc">%&gt;%</span></span>
<span id="cb165-3"><a href="WFD-food-pol.html#cb165-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">keep =</span> <span class="fu">n</span>() <span class="sc">!=</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(Food_Supply_Quantity))) <span class="sc">%&gt;%</span></span>
<span id="cb165-4"><a href="WFD-food-pol.html#cb165-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(keep) <span class="sc">%&gt;%</span></span>
<span id="cb165-5"><a href="WFD-food-pol.html#cb165-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>keep) <span class="sc">%&gt;%</span></span>
<span id="cb165-6"><a href="WFD-food-pol.html#cb165-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Country&#39;. You can override using the `.groups` argument.</code></pre>
<p>Does that look rather complicated? The difficult(ish) line is the summarise, in which we create a new variable <code>keep</code> that is TRUE or FALSE depending if all values of <code>Food_Supply_Quantity</code> are NA or not. The <code>n()</code> give the number of values, the <code>sum(is.na(Food_Supply_Quantity))</code> gives the number of NAs, and the <code>!=</code> asks if the two are not the same, and returns TRUE if so. The other lines should be possible for you to work out (though not necessarily easy).</p>
<p>Note that there are 8,272 combinations of years and countries in the dataset. This is an important number. It is the number of data points we should have data for after we calculate the diversity of food available in each country in each year.</p>
<p>Recall that we already decided to assume that when a country did not report a value for an item that this means there was always zero supply of that food item, so the country did not bother including it in the reported, i.e. it’s really a zero. Hence we’re going to pad out the data so that all countries report on all 114 items, with zero <code>Food Supply Quantity</code> for the items they did not report.</p>
<p>First we make a dataset with all combinations of <code>Country</code>, <code>Year</code>, and <code>Item</code>. It should have 182 * 51 * 182 = 1,058,148 rows. We use the quite lovely <code>expand.grid</code> function, which creates all possible combinations of the variables it’s given. We give it all the unique values of <code>Country</code>, <code>Year</code>, and <code>Item</code>, and it expands them to give all possible combinations. Each argument to <code>expand.grid</code> should be a name-value pair, and the name should be the same in the original data, to aid further operations:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="WFD-food-pol.html#cb167-1" aria-hidden="true" tabindex="-1"></a>all_cases <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Country =</span> <span class="fu">unique</span>(<span class="fu">pull</span>(fbs_long, Country)),</span>
<span id="cb167-2"><a href="WFD-food-pol.html#cb167-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Year =</span> <span class="fu">unique</span>(<span class="fu">pull</span>(fbs_long, Year)),</span>
<span id="cb167-3"><a href="WFD-food-pol.html#cb167-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Item =</span> <span class="fu">unique</span>(<span class="fu">pull</span>(fbs_long, Item))) </span></code></pre></div>
<p>Super. This has 1,058,148 rows as expected. Now we want to only keep from this the country/year combinations for which we already found there were countries that existed. There are 8,272 of these and each should have 114 items, so we should get 943,008 observations. We do this with a <code>left_join</code> to keep only the cases of the join that have values in the first (left) dataset in the join:</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="WFD-food-pol.html#cb168-1" aria-hidden="true" tabindex="-1"></a>temp2 <span class="ot">&lt;-</span> <span class="fu">left_join</span>(country_year_not_all_missing, all_cases)</span></code></pre></div>
<pre><code>## Joining, by = c(&quot;Country&quot;, &quot;Year&quot;)</code></pre>
<p>We get a warning, and know that we should never ignore warnings. The warning is <em>Column <code>Country</code> joining character vector and factor, coercing into character vector</em>. This is caused because <code>expand.grid</code> automatically converts character variables to factors. We can stop this happening (by adding the argument <code>stringsAsFactors = FALSE</code> in our call to <code>expand.grid</code> and hopefully the remove the warning:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="WFD-food-pol.html#cb170-1" aria-hidden="true" tabindex="-1"></a>all_cases <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Country =</span> <span class="fu">unique</span>(<span class="fu">pull</span>(fbs_long, Country)),</span>
<span id="cb170-2"><a href="WFD-food-pol.html#cb170-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Year =</span> <span class="fu">unique</span>(<span class="fu">pull</span>(fbs_long, Year)),</span>
<span id="cb170-3"><a href="WFD-food-pol.html#cb170-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Item =</span> <span class="fu">unique</span>(<span class="fu">pull</span>(fbs_long, Item)),</span>
<span id="cb170-4"><a href="WFD-food-pol.html#cb170-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb170-5"><a href="WFD-food-pol.html#cb170-5" aria-hidden="true" tabindex="-1"></a>temp2 <span class="ot">&lt;-</span> <span class="fu">left_join</span>(country_year_not_all_missing, all_cases)</span></code></pre></div>
<pre><code>## Joining, by = c(&quot;Country&quot;, &quot;Year&quot;)</code></pre>
<p>Perfect… and we still have the expected number of 943,008 observations.</p>
<p>Next we do another left join to add the food supply quantity data (in <code>fbs_long</code>) to the cases/observations we want to keep (in <code>temp2</code>)</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="WFD-food-pol.html#cb172-1" aria-hidden="true" tabindex="-1"></a>temp3 <span class="ot">&lt;-</span> <span class="fu">left_join</span>(temp2, fbs_long)</span></code></pre></div>
<pre><code>## Joining, by = c(&quot;Country&quot;, &quot;Year&quot;, &quot;Item&quot;)</code></pre>
<p>Good, we still have 943’008 observations.</p>
<p>The number of missing values is now 139,252 (please confirm this for yourself). Each of these is a case when a country reported values for some items in a year, but did not report values for others, and these others are given a value of NA. As we said above, we’re going to assume these are real zeros, and so we need to turn them all into zeros:</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="WFD-food-pol.html#cb174-1" aria-hidden="true" tabindex="-1"></a>fbs_final <span class="ot">&lt;-</span> temp3 <span class="sc">%&gt;%</span></span>
<span id="cb174-2"><a href="WFD-food-pol.html#cb174-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Food_Supply_Quantity =</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(Food_Supply_Quantity),</span>
<span id="cb174-3"><a href="WFD-food-pol.html#cb174-3" aria-hidden="true" tabindex="-1"></a>                                       Food_Supply_Quantity,</span>
<span id="cb174-4"><a href="WFD-food-pol.html#cb174-4" aria-hidden="true" tabindex="-1"></a>                                       <span class="dv">0</span>))</span></code></pre></div>
<p>No missing values now (again, please confirm this for yourself). And we have a dataset that we very well understand. Let’s check again though.</p>
<p>We should have 114 items reported per country per year:</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="WFD-food-pol.html#cb175-1" aria-hidden="true" tabindex="-1"></a>items_per_country_per_year <span class="ot">&lt;-</span> fbs_final <span class="sc">%&gt;%</span></span>
<span id="cb175-2"><a href="WFD-food-pol.html#cb175-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country, Year) <span class="sc">%&gt;%</span></span>
<span id="cb175-3"><a href="WFD-food-pol.html#cb175-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num =</span> <span class="fu">length</span>(<span class="fu">unique</span>(Item)))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Country&#39;. You can override using the `.groups` argument.</code></pre>
<p>And we should have varying numbers of countries per year:</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="WFD-food-pol.html#cb177-1" aria-hidden="true" tabindex="-1"></a>countries_per_year <span class="ot">&lt;-</span> fbs_final <span class="sc">%&gt;%</span></span>
<span id="cb177-2"><a href="WFD-food-pol.html#cb177-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb177-3"><a href="WFD-food-pol.html#cb177-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num =</span> <span class="fu">length</span>(<span class="fu">unique</span>(Country)))</span></code></pre></div>
<p>And the sum of the number of countries per year multiplied by 114 should equal 943,008:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="WFD-food-pol.html#cb178-1" aria-hidden="true" tabindex="-1"></a>countries_per_year <span class="sc">%&gt;%</span></span>
<span id="cb178-2"><a href="WFD-food-pol.html#cb178-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">sum</span>(num) <span class="sc">*</span> <span class="dv">114</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##    total
##    &lt;dbl&gt;
## 1 943008</code></pre>
<p>Yes! Wow! Can you believe so much effort was needed to make a solid foundation of data! And we’re not even there yet… we still have a particularly “involved” bit of wrangling work to do: we need to merge/join the FAO and the Polity datasets. But first…</p>
</div>
<div id="calculating-our-response-variables" class="section level3" number="7.7.7">
<h3><span class="header-section-number">7.7.7</span> Calculating our response variables</h3>
<p>The final step of preparation of the FAO data is to calculate our response variables. Our question is about food diversity so we need response variables that quantify this. We will use number of items available per year, and diversity of items available per year, where diversity accounts for the amount of each item as well as number of items using the Shannon index.</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="WFD-food-pol.html#cb180-1" aria-hidden="true" tabindex="-1"></a>fbs_div <span class="ot">&lt;-</span> fbs_final <span class="sc">%&gt;%</span></span>
<span id="cb180-2"><a href="WFD-food-pol.html#cb180-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country, Year) <span class="sc">%&gt;%</span></span>
<span id="cb180-3"><a href="WFD-food-pol.html#cb180-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">richness =</span> <span class="fu">sum</span>(Food_Supply_Quantity<span class="sc">&gt;</span><span class="dv">0</span>),</span>
<span id="cb180-4"><a href="WFD-food-pol.html#cb180-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">diversity =</span> <span class="fu">diversity</span>(Food_Supply_Quantity,</span>
<span id="cb180-5"><a href="WFD-food-pol.html#cb180-5" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">index =</span> <span class="st">&quot;shannon&quot;</span>))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Country&#39;. You can override using the `.groups` argument.</code></pre>
<p>Excellent. We have 8,272 data points, exactly as we should. (We previously saw this was the number of combinations of country and year for which not all data was NA. I.e. the number of rows in <code>country_year_not_all_missing</code>).</p>
<p>We will now save this dataset so we don’t have to run all that code every time:</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="WFD-food-pol.html#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(fbs_div, <span class="st">&quot;data/fbs_div.RDS&quot;</span>)</span></code></pre></div>
</div>
</div>
<div id="merge-the-two-datasets-aaaaaargh" class="section level2" number="7.8">
<h2><span class="header-section-number">7.8</span> Merge the two datasets (aaaaaargh!!)</h2>
<p>The <em>aaaaaargh</em> above is because things now get a little sketchy, tedious, and generally unsatisfactory. The reason is that the two datasets do not use the same country names or codes–i.e. they are not interoperable. And it turns out to be a real pain to make them so. We do, but hang on, its a bit ugly and complicated. If you learn only one thing, it should be the importance of building interoperability into dataset from the beginning, which can only be achieved with <a href="data-analysis-concepts.html#interoperability">semantic standards</a>.</p>
<p>First let’s clear R and reload the two datasets:</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="WFD-food-pol.html#cb183-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>()) <span class="co"># clear R</span></span>
<span id="cb183-2"><a href="WFD-food-pol.html#cb183-2" aria-hidden="true" tabindex="-1"></a>pol <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">&quot;data/pol.rds&quot;</span>)</span>
<span id="cb183-3"><a href="WFD-food-pol.html#cb183-3" aria-hidden="true" tabindex="-1"></a>fbs_div <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">&quot;data/fbs_div.RDS&quot;</span>)</span></code></pre></div>
<p>The final step of data preparation is to merge the Polity and FAO data. The main issue we must deal with before we do the merge is to make the country names in the two dataset <strong>interoperable</strong>. That is, we must ensure that we can match country names. If both datasets had been made with <strong>interoperability</strong> in mind, they would have used a standard naming of countries, such as ISO (International Organisation for Standardization) 3166-1 (this code denotes the standard for country naming).</p>
<p>At present we have a <code>Country</code> variable in both datasets. This contains an English language name for each country. Take a look at some of the names in the FAO derived food diversity dataset; here we find names containing the string <code>United</code>:</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="WFD-food-pol.html#cb184-1" aria-hidden="true" tabindex="-1"></a>fbs_div <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">str_detect</span>(Country, <span class="st">&quot;United&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb184-2"><a href="WFD-food-pol.html#cb184-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Country) <span class="sc">%&gt;%</span></span>
<span id="cb184-3"><a href="WFD-food-pol.html#cb184-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>## [1] &quot;United Arab Emirates&quot;       
## [2] &quot;United Kingdom&quot;             
## [3] &quot;United Republic of Tanzania&quot;
## [4] &quot;United States of America&quot;</code></pre>
<p>And also in the Polity dataset the counrty names containing <code>United</code>:</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="WFD-food-pol.html#cb186-1" aria-hidden="true" tabindex="-1"></a>pol <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">str_detect</span>(Country, <span class="st">&quot;United&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb186-2"><a href="WFD-food-pol.html#cb186-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Country) <span class="sc">%&gt;%</span></span>
<span id="cb186-3"><a href="WFD-food-pol.html#cb186-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>## [1] &quot;United Kingdom&quot;     &quot;United Province CA&quot;
## [3] &quot;United States&quot;</code></pre>
<p>The FAO data uses “United States of America” while the polity data uses “United States.”</p>
<p>Here’s another example:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="WFD-food-pol.html#cb188-1" aria-hidden="true" tabindex="-1"></a>pol <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">str_detect</span>(Country, <span class="st">&quot;Tanz&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb188-2"><a href="WFD-food-pol.html#cb188-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Country) <span class="sc">%&gt;%</span></span>
<span id="cb188-3"><a href="WFD-food-pol.html#cb188-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>## [1] &quot;Tanzania&quot;</code></pre>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="WFD-food-pol.html#cb190-1" aria-hidden="true" tabindex="-1"></a>fbs_div <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">str_detect</span>(Country, <span class="st">&quot;Tanz&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb190-2"><a href="WFD-food-pol.html#cb190-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Country) <span class="sc">%&gt;%</span></span>
<span id="cb190-3"><a href="WFD-food-pol.html#cb190-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>## [1] &quot;United Republic of Tanzania&quot;</code></pre>
<p>What a mess!!! These are not the only mismatches. We need a standard.</p>
<p>Both <em>original</em> datasets contain country <em>codes</em> as well as names. First look at the FAO food balance raw data. It contains the variable “Country Code” (beware that the code reads in the original 200 MB data file):</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="WFD-food-pol.html#cb192-1" aria-hidden="true" tabindex="-1"></a>fbs_temp <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/FoodBalanceSheets_E_All_Data.csv&quot;</span>,</span>
<span id="cb192-2"><a href="WFD-food-pol.html#cb192-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">locale =</span> <span class="fu">locale</span>(<span class="at">encoding =</span> <span class="st">&#39;ISO-8859-1&#39;</span>))</span>
<span id="cb192-3"><a href="WFD-food-pol.html#cb192-3" aria-hidden="true" tabindex="-1"></a>fbs_country <span class="ot">&lt;-</span> fbs_temp <span class="sc">%&gt;%</span></span>
<span id="cb192-4"><a href="WFD-food-pol.html#cb192-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Country, <span class="at">Country_Code=</span><span class="st">&#39;Country Code&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb192-5"><a href="WFD-food-pol.html#cb192-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() <span class="sc">%&gt;%</span></span>
<span id="cb192-6"><a href="WFD-food-pol.html#cb192-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Country_Code <span class="sc">&lt;</span> <span class="dv">5000</span>)</span></code></pre></div>
<p>Let us put the code into the <code>fbs_div</code> dataset. There both contain the common <code>Country</code> variable we want to merge by:</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="WFD-food-pol.html#cb193-1" aria-hidden="true" tabindex="-1"></a>fbs_div <span class="ot">&lt;-</span> <span class="fu">left_join</span>(fbs_div, fbs_country)</span></code></pre></div>
<pre><code>## Joining, by = &quot;Country&quot;</code></pre>
<p>It is not immediately clear what this code is, however, i.e. what standard. Digging into their metadata a bit we can find a page of <em>Definitions and Standards</em>: <a href="http://www.fao.org/faostat/en/#definitions" class="uri">http://www.fao.org/faostat/en/#definitions</a>. In the tab <em>Country/Region</em> we find a dataset with country names and various country codes, including ISO2 and ISO3 codes (of ISO 3166-1). Excellent. We downloaded this dataset and now read it into R and merge with the food balance sheet dataset <code>fbs_div</code>:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="WFD-food-pol.html#cb195-1" aria-hidden="true" tabindex="-1"></a>FAO_country_standards <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/FAOSTAT_data_country_name_standards.csv&quot;</span>, <span class="at">na =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ───────────────────────────────
## cols(
##   `Country Code` = col_double(),
##   Country = col_character(),
##   `M49 Code` = col_double(),
##   `ISO2 Code` = col_character(),
##   `ISO3 Code` = col_character(),
##   `Start Year` = col_double(),
##   `End Year` = col_double()
## )</code></pre>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="WFD-food-pol.html#cb197-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(FAO_country_standards) <span class="ot">&lt;-</span> <span class="fu">str_replace_all</span>(<span class="fu">names</span>(FAO_country_standards), <span class="fu">c</span>(<span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="st">&quot;_&quot;</span>))</span>
<span id="cb197-2"><a href="WFD-food-pol.html#cb197-2" aria-hidden="true" tabindex="-1"></a>FAO_country_standards <span class="ot">&lt;-</span> FAO_country_standards <span class="sc">%&gt;%</span></span>
<span id="cb197-3"><a href="WFD-food-pol.html#cb197-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Country_name_FAO =</span> Country) <span class="sc">%&gt;%</span></span>
<span id="cb197-4"><a href="WFD-food-pol.html#cb197-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Country_Code <span class="sc">&lt;</span> <span class="dv">5000</span>)</span></code></pre></div>
<p>Before we do the merge, take a look at this:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="WFD-food-pol.html#cb198-1" aria-hidden="true" tabindex="-1"></a>FAO_country_standards <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">str_detect</span>(Country_name_FAO, <span class="st">&quot;Swaz&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 0 x 7
## # … with 7 variables: Country_Code &lt;dbl&gt;,
## #   Country_name_FAO &lt;chr&gt;, M49_Code &lt;dbl&gt;,
## #   ISO2_Code &lt;chr&gt;, ISO3_Code &lt;chr&gt;,
## #   Start_Year &lt;dbl&gt;, End_Year &lt;dbl&gt;</code></pre>
<p>In the standard (ISO) there is no country named “Swaziland.” There is in the FAO food balance sheet dataset, however:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="WFD-food-pol.html#cb200-1" aria-hidden="true" tabindex="-1"></a>fbs_div <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">str_detect</span>(Country, <span class="st">&quot;Swaz&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb200-2"><a href="WFD-food-pol.html#cb200-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Country) <span class="sc">%&gt;%</span></span>
<span id="cb200-3"><a href="WFD-food-pol.html#cb200-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span></code></pre></div>
<pre><code>## [1] &quot;Swaziland&quot;</code></pre>
<p>A quick search tells us that Swaziland changed name to Eswatini. And here we find it in the ISO standard list:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="WFD-food-pol.html#cb202-1" aria-hidden="true" tabindex="-1"></a>FAO_country_standards <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">str_detect</span>(Country_name_FAO, <span class="st">&quot;Esw&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   Country_Code Country_name_FAO M49_Code ISO2_Code
##          &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt;    
## 1          209 Eswatini              748 SZ       
## # … with 3 more variables: ISO3_Code &lt;chr&gt;,
## #   Start_Year &lt;dbl&gt;, End_Year &lt;dbl&gt;</code></pre>
<p>The implication is that even two datasets from the same source (UN stats) used different English language names for the same country. Standards are critical!!</p>
<p>So, we are going to do the merge by the <code>Country_code</code> variable. The variable renaming we previously did has resulted in no other variables common between the two dataset, so we are good to go!</p>
<p>If we merge the FAO country standards dataset into the food balance data, we should get the same number of rows as in the food balance data. Anything less would indicate the standards data does not include some country codes that are the food balance data.</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="WFD-food-pol.html#cb204-1" aria-hidden="true" tabindex="-1"></a>fbs_div_stand <span class="ot">&lt;-</span> <span class="fu">left_join</span>(fbs_div, FAO_country_standards) <span class="sc">%&gt;%</span></span>
<span id="cb204-2"><a href="WFD-food-pol.html#cb204-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Start_Year, <span class="sc">-</span>End_Year)</span></code></pre></div>
<pre><code>## Joining, by = &quot;Country_Code&quot;</code></pre>
<p>Excellent, the <code>fbs_div</code> dataset now contains the ISO standard codes. Now we need to get the standards into the Polity data.</p>
<div id="polity-standardisation" class="section level3" number="7.8.1">
<h3><span class="header-section-number">7.8.1</span> Polity standardisation</h3>
<p>Good. Now let us look at the polity data. The original data file contains various country codes. Looking in the Polity user manual and a bit of further sleuthing reveals that the country codes are from the “Correlates of War” project: <a href="https://correlatesofwar.org/data-sets/cow-country-codes" class="uri">https://correlatesofwar.org/data-sets/cow-country-codes</a>. The dataset there `COW country codes.csv" was developed before the ISO country codes, and so has does not use an international standard (a personal communication with a developer confirmed this).</p>
<p>We decided, therefore, to make our own dataset that mapped the Polity country names to ISO standards. The steps to do this were to export the Polity country names as a csv file and import then into a spreadsheet programme (e.g. Excel). We then copy-pasted in the ISO standards. And then over about four hours of manual matching work made as many correspondences as possible. Yes, we did manipulate data in Excel… but the “data” is just the country names and codes. It was horrid, tedious, and risky (i.e. errors could easily be made and not seen) work. The resulting mapping carries no guarantees. It should be double, triple and quadruple checked. We will use it with great caution here…</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="WFD-food-pol.html#cb206-1" aria-hidden="true" tabindex="-1"></a>pol_iso_mapping <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/pol_iso_mapping.csv&quot;</span>,</span>
<span id="cb206-2"><a href="WFD-food-pol.html#cb206-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">na =</span> <span class="st">&quot;.&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb206-3"><a href="WFD-food-pol.html#cb206-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Country =</span> Country_pol)</span></code></pre></div>
<div class="beaware">
<p>
<strong>Be aware</strong> You may have noticed that in the <code>read_csv</code> just above we wrote <code>na = “.”</code>. This is because when we created the spreadsheet of mapping between Polity and ISO country names we used “.” and not “NA” as the missing value indicator. Can you guess why we did not use “NA?” The reason is that “NA” is the ISO2 code for Namibia. If we had used NA for missing value then Namibia would have been given a missing value for the ISO2 code. The general message here is to be careful when a variable contains entries that might include “NA” as a real value.
</p>
</div>
<p>Merge the ISO codes into the polity data:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="WFD-food-pol.html#cb207-1" aria-hidden="true" tabindex="-1"></a>pol_stand <span class="ot">&lt;-</span> <span class="fu">left_join</span>(pol, pol_iso_mapping)</span></code></pre></div>
<pre><code>## Joining, by = &quot;Country&quot;</code></pre>
</div>
<div id="the-final-merge" class="section level3" number="7.8.2">
<h3><span class="header-section-number">7.8.2</span> The final merge</h3>
<p>We are about as ready as we ever will be to merge the two datasets. Lets just go for it and see what happens (though better would be to see before doing so what we should expect). We will use <code>inner_join</code> to get keep only the rows with entries for both food diversity and polity. There can be a maximum number of rows of the smaller dataset, here 8’272 for the food diversity dataset. (We also select and rename variables–a bit of cleaning.)</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="WFD-food-pol.html#cb209-1" aria-hidden="true" tabindex="-1"></a>fbs_pol <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(fbs_div_stand,</span>
<span id="cb209-2"><a href="WFD-food-pol.html#cb209-2" aria-hidden="true" tabindex="-1"></a>                     pol_stand,</span>
<span id="cb209-3"><a href="WFD-food-pol.html#cb209-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;ISO2_Code&quot;</span> <span class="ot">=</span> <span class="st">&quot;ISO2_Code&quot;</span>,</span>
<span id="cb209-4"><a href="WFD-food-pol.html#cb209-4" aria-hidden="true" tabindex="-1"></a>                            <span class="st">&quot;Year&quot;</span> <span class="ot">=</span> <span class="st">&quot;Year&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb209-5"><a href="WFD-food-pol.html#cb209-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">Country =</span> Country.x,</span>
<span id="cb209-6"><a href="WFD-food-pol.html#cb209-6" aria-hidden="true" tabindex="-1"></a>         Year,</span>
<span id="cb209-7"><a href="WFD-food-pol.html#cb209-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">Richness =</span> richness,</span>
<span id="cb209-8"><a href="WFD-food-pol.html#cb209-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">Diversity =</span> diversity,</span>
<span id="cb209-9"><a href="WFD-food-pol.html#cb209-9" aria-hidden="true" tabindex="-1"></a>         Polity2,</span>
<span id="cb209-10"><a href="WFD-food-pol.html#cb209-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">Official_name_en =</span> official_name_en,</span>
<span id="cb209-11"><a href="WFD-food-pol.html#cb209-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">M49_Code =</span> M49_Code.x,</span>
<span id="cb209-12"><a href="WFD-food-pol.html#cb209-12" aria-hidden="true" tabindex="-1"></a>         ISO2_Code,</span>
<span id="cb209-13"><a href="WFD-food-pol.html#cb209-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">ISO3_Code =</span> ISO3_Code.x) <span class="sc">%&gt;%</span></span>
<span id="cb209-14"><a href="WFD-food-pol.html#cb209-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<p>This merged dataset has 7472 rows, because some of the country-year combinations in the food diversity dataset are not in the polity dataset. Note that many more of the country-year combinations in the polity data are not in the food diversity dataset. This is largely due to the polity data covering many more years, but also because it contains some countries that are not in the food diversity dataset.</p>
</div>
</div>
<div id="tidying-up" class="section level2" number="7.9">
<h2><span class="header-section-number">7.9</span> Tidying up</h2>
<p>Again, we have a lot of objects in R’s brain. We only need one: <code>fbs_pol</code>. We can remove all the other variables. We don’t need to run all the code above every time we do an analysis. Save the <code>fbs_pol</code> dataset, and in the next section we will start anew.</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="WFD-food-pol.html#cb210-1" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(fbs_pol, <span class="st">&quot;data/fbs_pol.Rdata&quot;</span>)</span></code></pre></div>
</div>
<div id="shapes-1" class="section level2" number="7.10">
<h2><span class="header-section-number">7.10</span> Shapes</h2>
<p>We will not look at the shapes of the distributions of the variables. As usual, start by loading libraries and our dataset:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="WFD-food-pol.html#cb211-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb211-2"><a href="WFD-food-pol.html#cb211-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb211-3"><a href="WFD-food-pol.html#cb211-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb211-4"><a href="WFD-food-pol.html#cb211-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb211-5"><a href="WFD-food-pol.html#cb211-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb211-6"><a href="WFD-food-pol.html#cb211-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb211-7"><a href="WFD-food-pol.html#cb211-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb211-8"><a href="WFD-food-pol.html#cb211-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vegan)</span>
<span id="cb211-9"><a href="WFD-food-pol.html#cb211-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggbeeswarm)</span>
<span id="cb211-10"><a href="WFD-food-pol.html#cb211-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb211-11"><a href="WFD-food-pol.html#cb211-11" aria-hidden="true" tabindex="-1"></a><span class="co"># load dataset</span></span>
<span id="cb211-12"><a href="WFD-food-pol.html#cb211-12" aria-hidden="true" tabindex="-1"></a>fbs_pol <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;data/fbs_pol.Rdata&quot;</span>)</span></code></pre></div>
<p>First the distribution of number of food items available in each country, across all countries and all years. The code for this you are quite familiar with by now, using <code>ggplot</code> and <code>geom_histogram</code> (Figure <a href="WFD-food-pol.html#fig:fbs-pol2">7.6</a>:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="WFD-food-pol.html#cb212-1" aria-hidden="true" tabindex="-1"></a>fbs_pol <span class="sc">%&gt;%</span></span>
<span id="cb212-2"><a href="WFD-food-pol.html#cb212-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb212-3"><a href="WFD-food-pol.html#cb212-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> Richness), <span class="at">bins =</span> <span class="dv">10</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol2"></span>
<img src="insights_website_files/figure-html/fbs-pol2-1.svg" alt="Frequency distribution of richness of food items across all countries and years." width="384" />
<p class="caption">
FIGURE 7.6: Frequency distribution of richness of food items across all countries and years.
</p>
</div>
<p>Some countries in some years have only between 30 and 40 food items available, others have over 90. This is a large difference. The most common number is around 80. The distribution is somewhat left skewed, with a longer tail of smaller values. The distribution is not, however, horribly asymmetric.</p>
<p>And looking at the distribution of diversity of food item quantities with the following code (Figure <a href="WFD-food-pol.html#fig:fbs-pol3">7.7</a>:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="WFD-food-pol.html#cb213-1" aria-hidden="true" tabindex="-1"></a>fbs_pol <span class="sc">%&gt;%</span></span>
<span id="cb213-2"><a href="WFD-food-pol.html#cb213-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb213-3"><a href="WFD-food-pol.html#cb213-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> Diversity), <span class="at">bins =</span> <span class="dv">10</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol3"></span>
<img src="insights_website_files/figure-html/fbs-pol3-1.svg" alt="Frequency distribution of diversity of food items across all countries and years." width="384" />
<p class="caption">
FIGURE 7.7: Frequency distribution of diversity of food items across all countries and years.
</p>
</div>
<p>The diversity distribution is quite similar to the richness distribution, with a bit of left skew, but not too much. The values of diversity are rather arbitrary—not as intuitive as richness. Higher values indicate some combination of high richness and high evenness in the quantities of the items.</p>
<p>And looking at the distribution of the Polity variable with the following code (Figure <a href="WFD-food-pol.html#fig:fbs-pol3x">7.8</a>:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="WFD-food-pol.html#cb214-1" aria-hidden="true" tabindex="-1"></a>fbs_pol <span class="sc">%&gt;%</span></span>
<span id="cb214-2"><a href="WFD-food-pol.html#cb214-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb214-3"><a href="WFD-food-pol.html#cb214-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> Polity2), <span class="at">bins =</span> <span class="dv">10</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol3x"></span>
<img src="insights_website_files/figure-html/fbs-pol3x-1.svg" alt="Frequency distribution of Polity2 all countries and years." width="384" />
<p class="caption">
FIGURE 7.8: Frequency distribution of Polity2 all countries and years.
</p>
</div>
<p>Is this what you were expecting? A rather bimodal distribution with most countries either very autocratic (low scores) or very democratic (high scores). Perhaps this in itself is an interesting pattern, though political scientists may find it obvious. Probably the creators of the Polity2 data have commented on it.</p>
<p>We can also make the three histograms more efficiently by first gathering all the variables into one column and then creating a graph with a facet for each of the original variables (Figure <a href="WFD-food-pol.html#fig:fbs-pol3x1">7.9</a>:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="WFD-food-pol.html#cb215-1" aria-hidden="true" tabindex="-1"></a>fbs_pol <span class="sc">%&gt;%</span></span>
<span id="cb215-2"><a href="WFD-food-pol.html#cb215-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Richness, Diversity, Polity2) <span class="sc">%&gt;%</span></span>
<span id="cb215-3"><a href="WFD-food-pol.html#cb215-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">&quot;Variable&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb215-4"><a href="WFD-food-pol.html#cb215-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">col =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) <span class="sc">%&gt;%</span></span>
<span id="cb215-5"><a href="WFD-food-pol.html#cb215-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb215-6"><a href="WFD-food-pol.html#cb215-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Value), <span class="at">bins =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb215-7"><a href="WFD-food-pol.html#cb215-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>( <span class="sc">~</span> Variable, <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">scales =</span> <span class="st">&quot;free&quot;</span>, )</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol3x1"></span>
<img src="insights_website_files/figure-html/fbs-pol3x1-1.svg" alt="Frequency distribution of Polity2 all countries and years." width="576" />
<p class="caption">
FIGURE 7.9: Frequency distribution of Polity2 all countries and years.
</p>
</div>
</div>
<div id="relationships-1" class="section level2" number="7.11">
<h2><span class="header-section-number">7.11</span> Relationships</h2>
<p>This is what we’ve been waiting for. We are about to answer our question. Can you believe it has been so long to get here. All the work was worthwhile, however. We understand our data; it is neat and tidy.</p>
<p>First we’ll look at the relationship between richness and diversity. We might imagine that they’re quite closely associated since 1) diversity includes richness, and 2) their distributions look quite similar. By now the following code to make a scatter plot of richness against diversity should be familiar, though we add some transparency to the points since lots lie on top of each other (Figure <a href="WFD-food-pol.html#fig:fbs-pol4">7.10</a>:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="WFD-food-pol.html#cb216-1" aria-hidden="true" tabindex="-1"></a>fbs_pol <span class="sc">%&gt;%</span></span>
<span id="cb216-2"><a href="WFD-food-pol.html#cb216-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb216-3"><a href="WFD-food-pol.html#cb216-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Richness, <span class="at">y =</span> Diversity),</span>
<span id="cb216-4"><a href="WFD-food-pol.html#cb216-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol4"></span>
<img src="insights_website_files/figure-html/fbs-pol4-1.svg" alt="Relationship between the two response variables, richness of items and diversity of items, across all countries and years." width="480" />
<p class="caption">
FIGURE 7.10: Relationship between the two response variables, richness of items and diversity of items, across all countries and years.
</p>
</div>
<p>We can also visualise the relationship with a two-dimensional histogram, such as that show in figure <a href="WFD-food-pol.html#fig:fbs-pol4">7.10</a> that was created with the following code:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="WFD-food-pol.html#cb217-1" aria-hidden="true" tabindex="-1"></a>fbs_pol <span class="sc">%&gt;%</span></span>
<span id="cb217-2"><a href="WFD-food-pol.html#cb217-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb217-3"><a href="WFD-food-pol.html#cb217-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hex</span>(<span class="fu">aes</span>(<span class="at">x =</span> Richness, <span class="at">y =</span> Diversity))</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol4-1"></span>
<img src="insights_website_files/figure-html/fbs-pol4-1-1.svg" alt="Relationship between the two response variables, richness of items and diversity of items, across all countries and years." width="480" />
<p class="caption">
FIGURE 7.11: Relationship between the two response variables, richness of items and diversity of items, across all countries and years.
</p>
</div>
<p>Not quite as close a relationship between richness and diversity as we expected. There is certainly enough spread that we could get different insights from looking at each of the variables separately… they don’t have to tell the same story.</p>
<p>And now, drum-roll, for the answer to our question. Is there a relationship between the political system of a country and the richness of food available for human consumption? Again, by now the R-code is hopefully no challenge for you (and gives Figure <a href="WFD-food-pol.html#fig:fbs-pol5">7.12</a>):</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="WFD-food-pol.html#cb218-1" aria-hidden="true" tabindex="-1"></a>fbs_pol <span class="sc">%&gt;%</span></span>
<span id="cb218-2"><a href="WFD-food-pol.html#cb218-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb218-3"><a href="WFD-food-pol.html#cb218-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Polity2, <span class="at">y =</span> Richness),</span>
<span id="cb218-4"><a href="WFD-food-pol.html#cb218-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.05</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol5"></span>
<img src="insights_website_files/figure-html/fbs-pol5-1.svg" alt="Richness of food items available versus Polity score, across all countries and all available years." width="480" />
<p class="caption">
FIGURE 7.12: Richness of food items available versus Polity score, across all countries and all available years.
</p>
</div>
<p>What do you think? Is there a relationship? And how confident are you that the relationship is not just the result of chance? Before we conclude, let’s look at the relationship for diversity of food items (Figure <a href="WFD-food-pol.html#fig:fbs-pol6">7.13</a>).</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="WFD-food-pol.html#cb219-1" aria-hidden="true" tabindex="-1"></a>fbs_pol <span class="sc">%&gt;%</span></span>
<span id="cb219-2"><a href="WFD-food-pol.html#cb219-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb219-3"><a href="WFD-food-pol.html#cb219-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Polity2, <span class="at">y =</span> Diversity),</span>
<span id="cb219-4"><a href="WFD-food-pol.html#cb219-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.05</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol6"></span>
<img src="insights_website_files/figure-html/fbs-pol6-1.svg" alt="Diversit of food items available versus Polity score, across all countries and all available years." width="480" />
<p class="caption">
FIGURE 7.13: Diversit of food items available versus Polity score, across all countries and all available years.
</p>
</div>
<p>Well, to our eyes, it certainly looks like the countries with high Polity scores have higher richness and diversity of food available than the countries with low Polity scores. There is also <em>a lot</em> of variation, such that any country (regardless of Polity) can have nearly the highest or lowest observed diversity of richness.</p>
<p>We are being a little bit naughty, however. Each country can be contributing multiple data points to these graphs, one for each year it is present in the dataset. Countries with more years will tend to influence our conclusions more than those with fewer years. And the different years of data from one country are not independent… they are repeated measures. Let’s remove this non-independence and differential contributions of different countries in one of the crudest (though very simple and effective) ways—by getting the average value for each country. The <code>group_by</code>, <code>summarise</code> we use should be familiar:</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="WFD-food-pol.html#cb220-1" aria-hidden="true" tabindex="-1"></a>fbs_pol_year <span class="ot">&lt;-</span> fbs_pol <span class="sc">%&gt;%</span></span>
<span id="cb220-2"><a href="WFD-food-pol.html#cb220-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country) <span class="sc">%&gt;%</span></span>
<span id="cb220-3"><a href="WFD-food-pol.html#cb220-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Ave_Polity2 =</span> <span class="fu">mean</span>(Polity2),</span>
<span id="cb220-4"><a href="WFD-food-pol.html#cb220-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">Ave_Richness =</span> <span class="fu">mean</span>(Richness),</span>
<span id="cb220-5"><a href="WFD-food-pol.html#cb220-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">Ave_Diversity =</span> <span class="fu">mean</span>(Diversity))</span></code></pre></div>
<p>We have gone from a dataset with 7,472 observations to one with 159, one data point for each country in the data. Here’s the code for the graphs of Polity score and richness/diversity for this country level data:</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="WFD-food-pol.html#cb221-1" aria-hidden="true" tabindex="-1"></a>fbs_pol_year <span class="sc">%&gt;%</span></span>
<span id="cb221-2"><a href="WFD-food-pol.html#cb221-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb221-3"><a href="WFD-food-pol.html#cb221-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Ave_Polity2, <span class="at">y =</span> Ave_Richness))</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol7"></span>
<img src="insights_website_files/figure-html/fbs-pol7-1.svg" alt="Richness of food items available versus Polity score; average value for each country." width="480" />
<p class="caption">
FIGURE 7.14: Richness of food items available versus Polity score; average value for each country.
</p>
</div>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="WFD-food-pol.html#cb222-1" aria-hidden="true" tabindex="-1"></a>fbs_pol_year <span class="sc">%&gt;%</span></span>
<span id="cb222-2"><a href="WFD-food-pol.html#cb222-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb222-3"><a href="WFD-food-pol.html#cb222-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Ave_Polity2, <span class="at">y =</span> Ave_Diversity))</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol8"></span>
<img src="insights_website_files/figure-html/fbs-pol8-1.svg" alt="Diversity of food items available versus Polity score; average value for each country." width="480" />
<p class="caption">
FIGURE 7.15: Diversity of food items available versus Polity score; average value for each country.
</p>
</div>
<p>The country level data (Figures <a href="WFD-food-pol.html#fig:fbs-pol7">7.14</a> and <a href="WFD-food-pol.html#fig:fbs-pol8">7.15</a>) appear to show stronger evidence of a positive relationship between polity score and richness/diversity of food available, with more democratic countries (higher polity scores) having more diversity of food available than less democratic ones.</p>
<p>Let’s look at the data another way, by categorising the Polity score. To do this we make a new variable using <code>mutate</code> and use the <code>cut</code> function to cut the Polity scores into five categories, and we name the categories:</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="WFD-food-pol.html#cb223-1" aria-hidden="true" tabindex="-1"></a>fbs_pol_year <span class="ot">&lt;-</span> fbs_pol_year <span class="sc">%&gt;%</span></span>
<span id="cb223-2"><a href="WFD-food-pol.html#cb223-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Ave_Polity2_cat =</span> <span class="fu">cut</span>(Ave_Polity2,</span>
<span id="cb223-3"><a href="WFD-food-pol.html#cb223-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">11</span>, <span class="dv">11</span>, <span class="at">length =</span> <span class="dv">6</span>),</span>
<span id="cb223-4"><a href="WFD-food-pol.html#cb223-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Very autocratic&quot;</span>,</span>
<span id="cb223-5"><a href="WFD-food-pol.html#cb223-5" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">&quot;Quite autocratic&quot;</span>,</span>
<span id="cb223-6"><a href="WFD-food-pol.html#cb223-6" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">&quot;Neutral&quot;</span>,</span>
<span id="cb223-7"><a href="WFD-food-pol.html#cb223-7" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">&quot;Quite democratic&quot;</span>,</span>
<span id="cb223-8"><a href="WFD-food-pol.html#cb223-8" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">&quot;Very democratic&quot;</span>)))</span></code></pre></div>
<p>Here, we will only show the figure for the richness of food items (Figures <a href="WFD-food-pol.html#fig:fbs-pol7">7.14</a>) and not diversity (you can make that graph yourself):</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="WFD-food-pol.html#cb224-1" aria-hidden="true" tabindex="-1"></a>fbs_pol_year <span class="sc">%&gt;%</span></span>
<span id="cb224-2"><a href="WFD-food-pol.html#cb224-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb224-3"><a href="WFD-food-pol.html#cb224-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Ave_Polity2_cat, <span class="at">y =</span> Ave_Richness)) <span class="sc">+</span></span>
<span id="cb224-4"><a href="WFD-food-pol.html#cb224-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_beeswarm</span>(<span class="fu">aes</span>(<span class="at">x =</span> Ave_Polity2_cat, <span class="at">y =</span> Ave_Richness)) <span class="sc">+</span></span>
<span id="cb224-5"><a href="WFD-food-pol.html#cb224-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Dietary richness</span><span class="sc">\n</span><span class="st">[number of food items]&quot;</span>) <span class="sc">+</span></span>
<span id="cb224-6"><a href="WFD-food-pol.html#cb224-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Type of political system&quot;</span>) <span class="sc">+</span></span>
<span id="cb224-7"><a href="WFD-food-pol.html#cb224-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol9"></span>
<img src="insights_website_files/figure-html/fbs-pol9-1.svg" alt="Frequency distribution of diversity of food items across all countries and years." width="480" />
<p class="caption">
FIGURE 7.16: Frequency distribution of diversity of food items across all countries and years.
</p>
</div>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="WFD-food-pol.html#cb225-1" aria-hidden="true" tabindex="-1"></a>fbs_pol_year <span class="sc">%&gt;%</span></span>
<span id="cb225-2"><a href="WFD-food-pol.html#cb225-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb225-3"><a href="WFD-food-pol.html#cb225-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Ave_Polity2_cat, <span class="at">y =</span> Ave_Diversity)) <span class="sc">+</span></span>
<span id="cb225-4"><a href="WFD-food-pol.html#cb225-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_beeswarm</span>(<span class="fu">aes</span>(<span class="at">x =</span> Ave_Polity2_cat, <span class="at">y =</span> Ave_Diversity)) <span class="sc">+</span></span>
<span id="cb225-5"><a href="WFD-food-pol.html#cb225-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Dietary diversity</span><span class="sc">\n</span><span class="st">[Shannon diversity of food items]&quot;</span>) <span class="sc">+</span></span>
<span id="cb225-6"><a href="WFD-food-pol.html#cb225-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Type of political system&quot;</span>) <span class="sc">+</span></span>
<span id="cb225-7"><a href="WFD-food-pol.html#cb225-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:fbs-pol10"></span>
<img src="insights_website_files/figure-html/fbs-pol10-1.svg" alt="Frequency distribution of diversity of food items across all countries and years." width="480" />
<p class="caption">
FIGURE 7.17: Frequency distribution of diversity of food items across all countries and years.
</p>
</div>
<p>This tells more or less the same story, though the figure might be considered a bit nicer as it shows the meaning of the Polity score. Note that there is considerable imbalance in the number of countries per Polity group. In particular there are quite few countries with very autocratic governance.</p>
</div>
<div id="wrapping-up-1" class="section level2" number="7.12">
<h2><span class="header-section-number">7.12</span> Wrapping up</h2>
<p>So it does appear that more democratic countries have more diversity food available to its citizens. We cannot, however, say that the political system <em>causes</em> this pattern… the relationship is “only” a correlation. There is probably some causal pathway linking the two, but it could be via a third variable.</p>
<p>We’re certain that you notice the huge effort preparing the data, and then only a little (mostly graphs) looking at shapes and relationships? We spent much more time and effort making sure we knew the data inside out, that we had prepared it appropriately, and it was a solid foundation for the question we wanted to answer.</p>
<p>That said, we were rather shallow in the part about gaining the insights from the data (the Relationships section). There is much much more we could have looked at. For example, we could look at relationships within countries across time, especially if there is a big shift in polity. Does the shift in polity precede a shift in diversity of food availability?</p>
<p>There are also lots of other explanatory variables we could have included in our analysis, for example national GDP, geographical location, and so on. Lots of this data is freely available on the internet. A simply fantastic place to get lost in such data and visualisation is the <a href="https://ourworldindata.org/">Our World in Data</a> website.</p>
<p>Other things you could think about analysing, for which data are available (though we couldn’t say exactly where):</p>
<ul>
<li>Biodiversity.</li>
<li>Latitudinal gradients.</li>
<li>Species (country) area relationship.</li>
<li>GDP diversity relationship.</li>
<li>Causality by time lag relationships.</li>
<li>FAO Macroeconomic statistics (e.g. GDP by country by year) (<a href="http://www.fao.org/faostat/en/#data" class="uri">http://www.fao.org/faostat/en/#data</a>)</li>
<li>FAO Population data (e.g. population size by country by year) (<a href="http://www.fao.org/faostat/en/#data" class="uri">http://www.fao.org/faostat/en/#data</a>)</li>
<li>World Bank, e.g. country land area <a href="https://data.worldbank.org/indicator/AG.LND.TOTL.K2" class="uri">https://data.worldbank.org/indicator/AG.LND.TOTL.K2</a></li>
<li>Maybe: SDG indicators: <a href="http://data.un.org/Explorer.aspx?d=SDGs" class="uri">http://data.un.org/Explorer.aspx?d=SDGs</a></li>
</ul>
</div>
<div id="and-a-challenge-for-you" class="section level2" number="7.13">
<h2><span class="header-section-number">7.13</span> And a challenge for you…</h2>
<p>Check to see if GDP or GDP per capita can explain variation in dietary diversity? What, if anything, would you imagine is the causation among political system, GDP, and dietary diversity (you might use the data to try to infer this, or just think about it)? You can get the GDP data from here: <a href="http://www.fao.org/faostat/en/#data/MK" class="uri">http://www.fao.org/faostat/en/#data/MK</a></p>
<p>Our solution (code only) is at the <a href="##foodpolgdp">end of Answers chapter</a> of this web site.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="WFD-dietdiv-effect.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="WFD-diet-restrict.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/opetchey/insights_website/blob/development/06-wfdemo-polity-fooddiv.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
